Repository demos-europe/demosplan-core, pull requests merged in 2023-09, with the labels that each got.

#1887 Mark LoadData classes as deprecated
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadCategoryData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadMailTemplateData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadMigrationVersionData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureTypeData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadRolesData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadUserData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/ProdFixture.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadAddressBookEntryData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadBoilerplateData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadCategoryData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadConsultationTokenData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadContextualHelpData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadCustomerData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadDraftStatementData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadElementsData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadEntityContentChangeData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadFaqData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadFileData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadForumData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadGlobalContentData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadLocationData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadMailData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadManualListSortData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadMapData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadMasterToebData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadNewsData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadOpenGeoDbData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureBehaviorDefinitionData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedurePersonData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureProposalData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureSubscriptionData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureTypeData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureUiDefinitionData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadReportData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSegmentData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSettingData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadStatementAttributeData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadStatementData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadStatementFormDefinitionData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadStatementVoteData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSurveyData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSurveyVoteData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadTagData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadUserData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadWorkflowPlaceData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/TestFixture.php
Labels: review:backend, quick-win

#1807 chore: use base container for ci tests
  Jenkinsfile
Labels: devops

#1810 chore: use shared elasticsearch and rabbitmq
  docker/elasticsearch7/Dockerfile
  docker/elasticsearch7/elasticsearch.yml
  docker/rabbitmq/Dockerfile
  docker/rabbitmq/definitions-raw.json
  docker/rabbitmq/rabbitmq.conf
  docker/rabbitmq/start.sh
Labels: devops

#1486 feat(refs T29585): Move recommendation modal to addon and insert hook
  client/js/bundles/procedure/administrationDashboard.js
  client/js/components/addon/AddonWrapper.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
  client/js/components/statement/segments/DpInsertableRecommendation.vue
  client/js/components/statement/segments/DpRecommendationModal.vue
  client/js/lib/addon/loadAddonComponents.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_modal.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_width.scss
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#1947 bug(refs T34442): Only center map again if there are features
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
Labels: type:bug, review:frontend

#1957 fix: make icons appear centered within buttons
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#1966 bug(refs T34578): Close modal after insert
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#1967 bug(refs: t34576): add missing icon and badge
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#1940 feature (T32026) : remove unused attribute from handler
  demosplan/DemosPlanCoreBundle/Logic/User/OrgaHandler.php
Labels: type:bug, review:backend

#1987 feat: when used as a library the project path differs
  demosplan/DemosPlanCoreBundle/Utilities/DemosPlanPath.php
Labels: review:backend

#1958 Delete procedure and all related things command (via SQL)
  demosplan/DemosPlanCoreBundle/Command/Data/DeleteProcedureCommand.php
Labels: review:backend, type:enhancement

#1914 feat: allow rabbitmq_dsn to be overridden by env var
  .env
  config/packages/old_sound_rabbit_mq.yaml
  config/parameters_default.yml
Labels: review:backend

#1897 refactor: avoid entity wrapping for twig
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureTypeController.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureTypeService.php
Labels: review:backend

#1972 chore (refs T34581): Define Entity to ensure field length
  demosplan/DemosPlanCoreBundle/Entity/Sessions.php
Labels: review:backend

#2001 chore: fix deprecated trim on null
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementFragment.php
Labels: review:backend, quick-win

#1990 feat (refs T34644): remove subdomains_allowed
  composer.lock
  config/parameters_default.yml
  config/parameters_test.yml
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
  demosplan/DemosPlanCoreBundle/Services/SubdomainHandler.php
  tests/backend/core/Procedure/Functional/SubdomainHandlerTest.php
Labels: review:backend

#1989 chore: rename composer package
  composer.json
Labels: devops

#2005 feat(refs T34626): adds addon wrapper to core template
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: type:bug, review:frontend, quick-win

#2007 bug(refs T34969): Fix addon hook for maillaine in basic settings
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
Labels: type:bug, review:frontend

#2008 fix (refs T34642): On create a new tag, check for already existing tag in procedure
  demosplan/DemosPlanCoreBundle/Logic/Statement/TagService.php
  demosplan/DemosPlanCoreBundle/Repository/TagRepository.php
  tests/backend/core/Statement/Functional/TagServiceTest.php
Labels: review:backend

#2017 fix(refs T34626): rolls back maennchen/zipStream
  composer.json
  composer.lock
Labels: type:bug, review:backend, quick-win

#2026 chore (refs T33326): Add DpToggleForm to Core.
  client/js/bundles/user/unregisteredPublicagencyList.js
  client/js/components/user/ToggleForm.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/unregistered_publicagency_list.html.twig
Labels: review:frontend, quick-win, type:enhancement

#2027 bug(refs T34708): Fix moving list items
  client/js/components/map/admin/DpAdminLayerListItem.vue
Labels: type:bug, review:frontend

#1999 fix(T34655): add tooltip on the Beta-Version text
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend, quick-win

#2028 fix: removes gdpr email addresses from orphan email removal
  demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php
Labels: type:bug, review:backend, quick-win

#2025 bug(refs T30049): Add import center for project
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
Labels: type:bug, review:frontend

#1935 F event documentation
  demosplan/DemosPlanCoreBundle/Command/Documentation/EventFinder.php
  demosplan/DemosPlanCoreBundle/ValueObject/EventMatch.php
  demosplan/DemosPlanCoreBundle/ValueObject/UnnamedEventMatch.php
  tests/backend/core/Core/Functional/EventFinderTest.php
Labels: review:backend

#2033 chore: update to twig 3
  composer.json
  composer.lock
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_list_entry_nojs.html.twig
Labels: review:frontend

#2034 bug(refs T34738): Fix user filter sets
  client/js/components/statement/assessmentTable/DpFilterModal.vue
Labels: type:bug, review:frontend

#2035 bug(refs T34691): Fix wrong trans key
  client/js/components/procedure/basicSettings/ExportSettings.vue
Labels: type:bug, review:frontend, quick-win

#2038 feat: improves RPC route exception logging
  demosplan/DemosPlanCoreBundle/Controller/GenericRpcController.php
Labels: review:backend, quick-win, type:enhancement

#1663 Use local pdflatex api & docx import container instead of java service
  config/config_core.yml
  config/config_dev_container.yml
  demosplan/DemosPlanCoreBundle/Tools/DocxImporterHttp.php
Labels: review:backend, lifecycle:do-not-merge

#2042 chore (T34770): allow authenticated ai user to access procedure in hidden phases
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: type:bug, review:backend

#2039 chore: restore orga/department change verify page
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
Labels: review:backend

#2043 chore: fix permission test setup after introducing ProcedureAccessEvaluator
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: type:bug, review:backend

#2044 chore: use global loglevel in dev logs
  config/packages/dev/monolog.yaml
Labels: review:backend, quick-win

#2040 chore: set user and group for generated cache and log files to current user
  composer.json
  tests/backend/bootstrap.php
Labels: devops, review:backend

#2018 F catch handle error when tag name already exist
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
  demosplan/DemosPlanCoreBundle/Exception/DuplicatedTagTitleException.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/TagService.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend

#2048 chore (refs T32796): fix faulty unique index on procedure_message.procedure_id
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/09/Version20230925135949.php
Labels: type:bug, review:backend

#1164 F extract delete statement methods
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AbstractRpcStatementBulkAction.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceStorage.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/RpcBulkDeleteStatements.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementDeleter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  tests/backend/core/Statement/Functional/StatementDeleterTest.php
  tests/backend/core/Statement/Functional/StatementMoverTest.php
  tests/backend/core/Statement/Functional/StatementServiceTest.php
Labels: review:backend

#2058 chore: simplify monolog config
  config/packages/dev/monolog.yaml
  config/packages/monolog.yaml
  config/packages/prod/monolog.yaml
  config/packages/test/monolog.yaml
  demosplan/DemosPlanCoreBundle/EventListener/ExceptionListener.php
Labels: review:backend

#1531 chore(refs T19759): Use the new way to init Vue3
  client/js/InitVue.js
  client/js/components/statement/assessmentTable/DpFilterModal.vue
Labels: review:frontend, type:enhancement

#1983 feature : refactor permission base on EWM project
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: review:backend

#2074 feat (refs T30599): allow addons to have their own DoctrineMigrations
  demosplan/DemosPlanCoreBundle/Addon/AddonDoctrineMigrationsPass.php
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
Labels: review:backend

#2069 F add statements similar submitters to export
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePerson.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#2077 F adjust methods parameters und returntypes
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePerson.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Labels: support:backend

#1978 chore: Upgrade ancient geo library
  composer.json
  demosplan/DemosPlanCoreBundle/Logic/Map/GeoJsonToFeaturesConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Maps/WktToGeoJsonConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementGeoService.php
  demosplan/DemosPlanCoreBundle/Utilities/Map/MapScreenshotter.php
  demosplan/DemosPlanCoreBundle/ValueObject/Map/Feature.php
  phpstan.dist.neon
  symfony.lock
  tests/backend/core/Map/Unit/WktToGeoJsonConverterTest.php
Labels: review:backend
