Repository demos-europe/demosplan-core, pull requests merged in 2023-04, with the labels that each got.

#1116 feature (refs T30254): remove an unnecessary method
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/Transformer/BaseTransformer.php
Labels: review:backend, quick-win

#1123 feature (refs T30254): update composer.lock
  composer.lock
Labels: review:backend

#1127 refactor (refs T30254): detect invalid state early
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
Labels: type:bug, review:backend

#1126 fix (refs T32124): Always show published documents to owning orga
  demosplan/DemosPlanDocumentBundle/Logic/DocumentHandler.php
Labels: review:backend

#1124 fix (refs T32046): simplify sidemenu item extras
  demosplan/DemosPlanCoreBundle/Logic/MenuBuilder/MenuBuilder.php
Labels: review:backend, quick-win

#1129 chore (refs T30525): anonymous user name needs to be set
  demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
Labels: review:backend, quick-win

#1112 F remove top level interface from services yaml
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: review:backend

#1135 F 30254 adjust service yml
  composer.lock
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: review:backend

#1137 feature (refs T30254): update services.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: review:backend

#1138 fix request format for extra email addresses
  client/js/components/procedure/basicSettings/DpAllowedSenderEmailList.vue
Labels: review:frontend, quick-win

#1139 feature (refs T30254): instantiate paramter in constructor before usage.
  demosplan/DemosPlanCoreBundle/EventSubscriber/HandleEmailAddressSubscriber.php
Labels: review:backend

#1140 feature (refs T30254): instantiate array as empty before eventually filling it with values
  demosplan/DemosPlanCoreBundle/EventSubscriber/HandleEmailAddressSubscriber.php
Labels: review:backend

#1142 fix (refs T31989): exclude pseudo-organisation from `Orga` resources
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
Labels: type:bug, review:backend

#1148 minor (refs T31740): adds logging
  demosplan/DemosPlanUserBundle/Logic/UserMapperDataportGatewayHH.php
Labels: review:backend, quick-win

#1149 fix invalid request data for extra email addresses
  client/js/components/procedure/basicSettings/DpAllowedSenderEmailList.vue
Labels: review:frontend

#1102 T30866 administer imprint and privacy settings as customer master user
  client/js/components/user/DpOrganisationFormFields.vue
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrgaController.php
  demosplan/DemosPlanCoreBundle/Entity/User/Role.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
  demosplan/DemosPlanUserBundle/Logic/OrgaHandler.php
  demosplan/DemosPlanUserBundle/Logic/UserHandler.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story

#1150 Fix(refs T31995): no institution data displayed in form fields
  client/js/components/user/DpUserFormFields.vue
Labels: review:frontend

#1152 feature (refs T30254):Tag Interface in Service.yml & remove unused EventSubscriber
  demosplan/DemosPlanCoreBundle/EventSubscriber/HandleEmailAddressSubscriber.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: review:backend

#1154 feature (refs T30254): update composer.lock due to changes in demosplan-addon
  composer.lock
Labels: review:backend

#1163 F T32181 adjust required date permission
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  demosplan/DemosPlanCoreBundle/Resources/config/permissions.yml
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: review:backend

#1171 feat(refs: T30866): use correct permissions to edit orga imprint and data protection
  client/js/components/user/DpOrganisationFormFields.vue
Labels: review:frontend

#1179 fix: add addon wrapper to basic settings entrypoint
  client/js/bundles/procedure/administrationEdit.js
  client/js/components/procedure/basicSettings/DpAllowedSenderEmailList.vue
Labels: review:frontend

#1181 Bump demosplan UI to 0.0.19
  yarn.lock
Labels: review:frontend

#1180 Persist SimilarStatementSubmitter state locally
  client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue
Labels: type:bug, review:frontend

#1182 fix: remove DpAllowedSenderEmailList.vue from DpBasicSettings
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
Labels: review:frontend

#1184 F_T31959 adjust core permissions
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: type:bug, review:backend, quick-win

#1165 chore: Delete VueBus
  client/fe/webpack/plugins.js
  client/js/InitVue.js
  client/js/VueConfigBus.js
  client/js/components/map/publicdetail/controls/MapTools.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
  client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue
  client/js/components/statement/fragment/Edit.vue
  client/js/components/statement/fragmentList/Fragment.vue
  client/js/lib/core/ExtendedVueEvents.js
  client/js/lib/core/lib_documentation.md
  client/js/lib/core/libs/ToggleAnything.js
  client/js/lib/procedure/DPWizard.js
  client/js/plugins/DPVueBus.js
  client/js/plugins/DPVueCore.js
  demosplan/DemosPlanCoreBundle/Resources/client/js/VueConfigLocal.js
  eslintrc.js
Labels: review:frontend, type:enhancement

#1190 fix(refs T32259): AddonWrapper needs to be imported in DpBasicSettings
  client/js/bundles/procedure/administrationEdit.js
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
Labels: review:frontend, quick-win

#1191 feature (refs T32257): Remove a duplicated entry in Service.yml
  composer.lock
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: review:backend

#1192 Use correct button label
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
Labels: type:bug, review:frontend

#1189 F_T30603 remove wrong use statement
  demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
Labels: review:backend, quick-win

#1193 fix (refs T30866): Permissions needs to be available by exposing them.
  demosplan/DemosPlanCoreBundle/Resources/config/permissions.yml
Labels: quick-win, type:story

#1210 chore: adjust method to match updated interface
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
Labels: review:backend, quick-win

#1212 F fix twigs paths
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_detail.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_index.html.twig
Labels: review:backend

#1213 chore: only add addon controllers if addons have them
  demosplan/DemosPlanCoreBundle/Addon/AddonRoutingLoader.php
Labels: review:backend

#1194 Fix tooltip positioning
  client/js/components/map/map/DpOlMapEditFeature.vue
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_tooltip.scss
  yarn.lock
Labels: type:bug, review:frontend

#1219 bug(refs T28356): Software components with no url
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/components_entry.html.twig
Labels: type:bug, review:frontend, quick-win

#1211 feat: Clear cache out of band
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend, type:enhancement

#728 chore: fix return type covariance issues
  demosplan/DemosPlanCoreBundle/Logic/ArrayObject.php
  demosplan/DemosPlanCoreBundle/Logic/LinkMessageSerializable.php
  demosplan/DemosPlanCoreBundle/Logic/MessageSerializable.php
  demosplan/DemosPlanCoreBundle/ValueObject/ToBy.php
Labels: review:backend

#1224 B t22439 for release ewm
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementResourceTypeService.php
  demosplan/DemosPlanCoreBundle/Resources/config/permissions.yml
  demosplan/DemosPlanStatementBundle/Logic/StatementDeleter.php
  demosplan/DemosPlanStatementBundle/Logic/StatementHandler.php
  demosplan/DemosPlanStatementBundle/Logic/StatementService.php
  tests/backend/core/Statement/Functional/StatementDeleterTest.php
Labels: review:backend

#1226 Fix: Remove double data property
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
Labels: review:frontend, quick-win

#1231 F_remove unnecessary interface defintion
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: review:backend

#1223 feature (refs T32200): avoid null as param client in FileService in addonContext
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: type:bug, review:backend

#1242 fix (refs T31336): correct spelling of referenced service.
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: type:bug, review:backend, quick-win

#1243 Feat(refs:T32012): order v bind vue3 migration
  client/js/components/addon/AddonWrapper.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  client/js/components/statement/publicStatementLists/DpPublicStatement.vue
  client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  client/js/components/user/DpCreateItem.vue
  yarn.lock
Labels: review:frontend, type:enhancement

#1217 F T32245 move survey bundle to core
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Controller/Survey/SurveyController.php
  demosplan/DemosPlanCoreBundle/Controller/Survey/SurveyVoteAPIController.php
  demosplan/DemosPlanCoreBundle/Entity/Survey/Survey.php
  demosplan/DemosPlanCoreBundle/Entity/Survey/SurveyVote.php
  demosplan/DemosPlanCoreBundle/Exception/SurveyInputDataException.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyCreateHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyNewHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyService.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyShowHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyUpdateHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyVoteCreateHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyVoteHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Survey/SurveyVoteService.php
  demosplan/DemosPlanCoreBundle/Repository/SurveyRepository.php
  demosplan/DemosPlanCoreBundle/Repository/SurveyVoteRepository.php
  demosplan/DemosPlanCoreBundle/Resources/config/Survey/survey-schema-create.json
  demosplan/DemosPlanCoreBundle/Resources/config/Survey/survey-schema-update.json
  demosplan/DemosPlanCoreBundle/Resources/config/Survey/surveyvote-schema-create.json
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services_repositories.yml
  demosplan/DemosPlanCoreBundle/Validator/SurveyValidator.php
  demosplan/DemosPlanCoreBundle/Validator/SurveyVoteValidator.php
  demosplan/DemosPlanSurveyBundle/DemosPlanSurveyBundle.php
  tests/backend/core/Survey/Unit/ProcedureMatchSurveyTest.php
  tests/backend/core/Survey/Unit/SurveyConfigurationTest.php
  tests/backend/core/Survey/Unit/SurveyCreateHandlerTest.php
  tests/backend/core/Survey/Unit/SurveyHandlerTest.php
  tests/backend/core/Survey/Unit/SurveyNewHandlerTest.php
  tests/backend/core/Survey/Unit/SurveyServiceTest.php
  tests/backend/core/Survey/Unit/SurveyShowHandlerTest.php
  tests/backend/core/Survey/Unit/SurveyTestUtils.php
  tests/backend/core/Survey/Unit/SurveyUpdateHandlerTest.php
  tests/backend/core/Survey/Unit/SurveyValidJsonTest.php
  tests/backend/core/Survey/Unit/SurveyVoteCreateHandlerTest.php
  tests/backend/core/Survey/Unit/SurveyVoteHandlerTest.php
  tests/backend/core/Survey/Unit/SurveyVoteValidatorTest.php
Labels: review:backend

#1220 F T32247 move report bundle to core
  demosplan/DemosPlanCoreBundle/Controller/Report/DemosPlanReportController.php
  demosplan/DemosPlanCoreBundle/Entity/Report/ReportEntry.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/ReportSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/Report/AbstractReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ExportReportService.php
  demosplan/DemosPlanCoreBundle/Logic/Report/MasterPublicAgencyReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Report/OrganisationReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ProcedureReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ProcedureUpdateReportMessageBuilder.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ReportMessageConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ReportService.php
  demosplan/DemosPlanCoreBundle/Logic/Report/StatementReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementAnonymizeService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopyAndMoveService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementDeleter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementMover.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/SubmitterService.php
  demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Repository/ReportRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ReportEntryResourceType.php
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services_autowire.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services_repositories.yml
  demosplan/DemosPlanCoreBundle/ValueObject/Report/ProcedureFinalMailReportEntryData.php
  demosplan/DemosPlanCoreBundle/ValueObject/Report/RegisteredInvitationReportEntryData.php
  demosplan/DemosPlanCoreBundle/ValueObject/Report/StatementFinalMailReportEntryData.php
  demosplan/DemosPlanCoreBundle/ValueObject/Report/UnregisteredInvitationReportEntryData.php
  demosplan/DemosPlanProcedureBundle/Logic/ExportService.php
  demosplan/DemosPlanProcedureBundle/Logic/PrepareReportFromProcedureService.php
  demosplan/DemosPlanProcedureBundle/Logic/ServiceStorage.php
  demosplan/DemosPlanReportBundle/DemosPlanReportBundle.php
  demosplan/DemosPlanUserBundle/Logic/MasterToebService.php
  demosplan/DemosPlanUserBundle/Logic/OrgaService.php
  demosplan/DemosPlanUserBundle/Logic/UserService.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanReport/list.html.twig
  tests/backend/core/Procedure/Functional/PrepareReportFromProcedureServiceTest.php
  tests/backend/core/Procedure/Functional/ProcedureServiceTest.php
  tests/backend/core/Report/Functional/ReportMessageConverterTest.php
  tests/backend/core/Report/Functional/ReportServiceTest.php
Labels: review:backend

#1248 fix (refs T32244 & T32245): Remove old use statements of moved bundles.
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Labels: type:bug, review:backend, quick-win

#1253 fix(refs T32449): load statement text instead if permission is not granted for segments
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
Labels: review:frontend

#1250 Feat(refs:T32012): vue3 migration -> add key and change v-if logic
  client/js/bundles/core/api_documentation.js
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
  client/js/components/statement/DpStatementAnonymize.vue
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  client/js/components/user/DpOrganisationFormFields.vue
  yarn.lock
Labels: review:frontend, type:enhancement

#1255 fix(refs T32449): remove access to segments for ahb
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
Labels: review:frontend

#1256 refs T32414: add csrf token to registration
  client/js/components/user/citizenRegisterForm/CitizenRegisterForm.vue
  client/js/components/user/orgaRegisterForm/OrgaRegisterForm.vue
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrgaController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
  demosplan/DemosPlanCoreBundle/Logic/SessionHandler.php
  demosplan/DemosPlanUserBundle/Logic/UserHandler.php
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/citizen_register_form.html.twig
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/orga_register_form.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, security

#1277 Feat(refs:32012): Remove prop and native modifier - migration to vue3
  client/js/components/statement/assessmentTable/ConsolidateModal.vue
  client/js/components/statement/assessmentTable/CopyStatementModal.vue
  client/js/components/statement/assessmentTable/DpMoveStatementModal.vue
  client/js/components/statement/assessmentTable/TiptapEditText.vue
Labels: review:frontend, type:enhancement

#1275 Feat(refs:T322012): vue3 migration - usage of template tag/element
  client/js/components/document/DpMapSettingsPreview.vue
  client/js/components/procedure/SegmentsList/CustomSearch.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
  client/js/components/procedure/imageAnnotator/DpLabelModal.vue
  client/js/components/procedure/splitStatement/SplitStatementView.vue
  client/js/components/statement/DpBoilerPlateModal.vue
  client/js/components/statement/assessmentTable/DpFilterModal.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
  client/js/components/statement/publicStatementLists/DpPublicStatement.vue
  client/js/components/statement/segments/DpRecommendationModal.vue
  client/js/components/statement/statement/DpVersionHistory.vue
  client/js/components/statement/statement/DpVersionHistoryDay.vue
Labels: review:frontend, type:enhancement

#1222 feat(refs T31974): Add pager for statements and segments
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend

#1241 fix (refs T32390): allow procedure access for planning offices
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
Labels: type:bug, review:backend
