Repository demos-europe/demosplan-core, pull requests merged in 2023-05, with the labels that each got.

#1292 fix(refs T32449): upgrade demosplan-ui to v0.0.21
  yarn.lock
Labels: review:frontend

#1305 bug(refs T32505): center map
  client/js/components/map/map/DpOlMapDrawFeature.vue
  client/js/components/map/map/DpOlMapEditFeature.vue
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
Labels: type:bug, review:frontend

#1310 Fix(refs: T32450) make radio buttons reactive without clicking in the form
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
Labels: review:frontend

#1303 chore: trim is not allowed to be called with null
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
Labels: review:backend, quick-win

#1265 feat: add default map to prod fixtures
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadCustomerData.php
Labels: review:backend, quick-win

#1266 feat: remove rollup migration preparation code
  demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php
Labels: review:backend

#1267 chore: reduce authenticator method visibility
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/LoginFormAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiHHAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiHHStaticAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiSHAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiSHStaticAuthenticator.php
Labels: review:backend, quick-win

#1294 F use event interface instead event path
  demosplan/DemosPlanCoreBundle/EventSubscriber/ParametersProviderSubscriber.php
Labels: review:backend

#1314 fix (refs T32390): use current syntax after merge from very old branch
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
Labels: type:bug, review:backend

#1254 F t32212 adjustments to support inteface method type declarations
  composer.lock
  demosplan/DemosPlanCoreBundle/Entity/Branding.php
  demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
  demosplan/DemosPlanCoreBundle/Entity/File.php
  demosplan/DemosPlanCoreBundle/Entity/Help/ContextualHelp.php
  demosplan/DemosPlanCoreBundle/Entity/Map/GisLayer.php
  demosplan/DemosPlanCoreBundle/Entity/Map/GisLayerCategory.php
  demosplan/DemosPlanCoreBundle/Entity/Slug.php
  demosplan/DemosPlanCoreBundle/Entity/SluggedEntity.php
  demosplan/DemosPlanCoreBundle/Entity/User/Address.php
  demosplan/DemosPlanCoreBundle/Entity/User/AddressBookEntry.php
  demosplan/DemosPlanCoreBundle/Entity/User/Department.php
  demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTag.php
  demosplan/DemosPlanCoreBundle/Entity/User/MasterToeb.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/Entity/User/OrgaStatusInCustomer.php
  demosplan/DemosPlanCoreBundle/Entity/User/OrgaType.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/Transformer/BaseTransformer.php
  demosplan/DemosPlanCoreBundle/Services/ApiResourceService.php
Labels: review:backend

#1315 feature (refs T32390): add missing log statements
  demosplan/DemosPlanCoreBundle/Logic/FileUploadService.php
Labels: review:backend

#1295 feat: use default elasticsearch indexing instead of SearchIndexTask
  demosplan/DemosPlanCoreBundle/Addon/AddonRoutingLoader.php
  demosplan/DemosPlanCoreBundle/Command/MaintenanceCommand.php
  demosplan/DemosPlanCoreBundle/Command/SearchIndexCommand.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentStatementFragmentController.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSeachTaskData.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/05/Version20230504164844.php
  demosplan/DemosPlanCoreBundle/Entity/SearchIndexTask.php
  demosplan/DemosPlanCoreBundle/EventListener/DemosPlanResponseListener.php
  demosplan/DemosPlanCoreBundle/EventListener/UpdateElasticaStatementPostListener.php
  demosplan/DemosPlanCoreBundle/Logic/JsonApiActionService.php
  demosplan/DemosPlanCoreBundle/Logic/SearchIndexTaskService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementAnonymizeHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementClusterService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementDeleter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFragmentService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementMover.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxSegmentImport.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxStatementImport.php
  demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Repository/SearchIndexTaskRepository.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
  demosplan/DemosPlanCoreBundle/Resources/config/packages/fos_elastica.yaml
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services_repositories.yml
  demosplan/DemosPlanCoreBundle/ValueObject/QueueStatus.php
  tests/backend/core/Core/Functional/SearchIndexTaskServiceTest.php
Labels: review:backend

#1257 Add csrf token to login form
  client/js/components/user/samlLoginForm/SamlLoginForm.vue
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/LoginFormAuthenticator.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/alternative_login.html.twig
Labels: review:frontend, review:backend, security

#1271 feat: extract initialize logic to event subscriber
  demosplan/DemosPlanCoreBundle/EventSubscriber/DetermineProcedureSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/InitializeService.php
  demosplan/DemosPlanCoreBundle/Logic/SessionHandler.php
Labels: review:backend

#1272 feat: remove DemosToken
  config/packages/security.yaml
  config/services.yml
  demosplan/DemosPlanCoreBundle/Entity/User/SecurityUser.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/CheckOrgadataMissingSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssignService.php
  demosplan/DemosPlanCoreBundle/Logic/User/CurrentUserService.php
  demosplan/DemosPlanCoreBundle/Logic/User/OrgaService.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/UserFromSecurityUserProvider.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Token/DemosToken.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Token/NotAuthenticatedToken.php
  demosplan/DemosPlanCoreBundle/Security/Firewall/Listener/DemosAuthenticationListener.php
  tests/backend/base/AbstractApiTest.php
  tests/backend/base/FunctionalTestCase.php
  tests/backend/core/Core/Functional/ProcedureExtensionTest.php
Labels: review:backend

#1322 chore: remove obsolete manual ES statement indexing
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementResourceTypeService.php
Labels: review:backend

#1318 feature (refs T32200): avoid null for parameter
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: review:backend, quick-win

#1329 chore: fix addon route path as it may be called differently
  demosplan/DemosPlanCoreBundle/Addon/AddonRoutingLoader.php
Labels: review:backend, quick-win

#1335 F adjust dependency version
  composer.json
  composer.lock
Labels: review:backend, quick-win

#1317 F T28477 incorrect display of the title when exporting statements
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/ProcedureExtension.php
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export.tex.twig
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_anonymous.tex.twig
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_condensed.tex.twig
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_condensed_anonymous.tex.twig
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_fragments_anonymous.tex.twig
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/export_original.tex.twig
Labels: type:bug, review:backend

#1338 F adjust dependency version
  composer.json
  composer.lock
Labels: review:backend

#1340 feat (refs T32606): Adjust services.yml for UserResourceTypeInterface
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: type:bug, review:backend

#1167 chore: Move VueCore to regular Vue
  client/fe/webpack/optimization.js
  client/fe/webpack/plugins.js
  client/js/InitVue.js
  client/js/VueConfigCore.js
  client/js/loadSentry.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_tooltip.scss
Labels: review:frontend, type:enhancement

#1351 bug(refs T32572): fix special characters appearing at the end of stri…
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend

#1307 fix (refs T30974): edit variables naming for box-shadow.
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_base.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_actionbox.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_actionmenu.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_callout.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_card.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_convert-annotated-pdf.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_editor-menububble.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_notify.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_pageheader.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_public-statement.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_sidemenu.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_slidebar.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitbutton.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitstatement.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_statement.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_styled-html.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tabs.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_timepicker.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_multiselect.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_openlayers.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/core_style.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_badge.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_button.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_form.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_modal.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_notification-badge.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_tooltip.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_wizard.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/token/_box-shadow.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/token/_font-size.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/token/_rounded.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/token/index.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_border-radius.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_box-shadow.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_font-size.scss
Labels: review:frontend, type:enhancement

#1328 chore: avoid error when elasticsearch has some issues
  demosplan/DemosPlanCoreBundle/Logic/Statement/ElasticSearchService.php
Labels: review:backend, quick-win

#1365 feat(refs T32601): automatically use dates in pdf import confirmation view
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
Labels: review:frontend

#1367 fix(refs T32601): fix initialization error
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
Labels: review:frontend

#1366 bug(refs T32785): Add css selector to savelist
  client/fe/config/config.js
Labels: type:bug, review:frontend, quick-win

#1342 bug(refs T32727): Add storage key for pagination
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/shared/mixins/paginationMixin.js
  client/js/components/statement/listStatements/ListStatements.vue
Labels: type:bug, review:frontend

#1386 fix T32606 resrouce types interfaces have to be set public
  config/services.yml
  config/services_autowire.yml
Labels: review:backend

#1387 chore: fix relative path after refactoring
  config/services_deployment.yml
Labels: review:backend

#581 Improve docker setup
  .gitignore
  config/config_dev_container.yml
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
  docker-compose-prod.dist.yml
  docker-compose.dist.yml
  docker/elasticsearch7/Dockerfile
  docker/elasticsearch7/elasticsearch.yml
  docker/javaservice/Dockerfile
  docker/javaservice/override.properties
  docker/javaservice/start.sh
  docker/nginx/site.conf
  docker/php8.1-cli-development/Dockerfile
  docker/php8.1-cli-development/files/ssh_host_dsa_key
  docker/php8.1-cli-development/files/ssh_host_dsa_key.pub
  docker/php8.1-cli-development/files/ssh_host_ed25519_key
  docker/php8.1-cli-development/files/ssh_host_ed25519_key.pub
  docker/php8.1-cli-development/sshd_config
  docker/php8.1-cli-development/start.sh
  docker/php8.1-cli-development/zshenv
  docker/php8.1-cli-development/zzz-dplan.ini
  docker/php8.1-cli-maintenance/Dockerfile
  docker/php8.1-cli-maintenance/start.sh
  docker/php8.1-cli-maintenance/zzz-dplan.ini
  docker/php8.1-fpm-xdebug/Dockerfile
  docker/php8.1-fpm-xdebug/xdebug.conf
  docker/php8.1-fpm-xdebug/zzz-dplan.ini
  docker/php8.1-fpm/Dockerfile
  docker/php8.1-fpm/zzz-dplan.ini
  docker/rabbitmq/Dockerfile
  docker/rabbitmq/definitions-raw.json
  docker/rabbitmq/rabbitmq.conf
  docker/rabbitmq/start.sh
Labels: devops

#1352 F adjust dependency version
  composer.json
  composer.lock
Labels: review:backend

#1391 fix (refs T32858): Allow overwriting filenames on tus upload
  demosplan/DemosPlanCoreBundle/EventSubscriber/TusUploadEventSubscriber.php
Labels: review:backend

#1392 F t32879 avoid type error
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
Labels: review:backend, quick-win

#1389 Feat(refs: T32135): new responsive styling header nav
  client/js/InitVue.js
  client/js/components/button/HamburgerMenuButton.vue
  client/js/lib/core/libs/GlobalEventListener.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_hamburgermenubutton.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/index.scss
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#1393 bug(refs T32855): Fix multiselect
  client/js/components/faq/DpFaqItem.vue
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  client/js/components/statement/DpBoilerPlate.vue
  client/js/components/statement/assessmentTable/AssignEntityModal.vue
  client/js/components/statement/assessmentTable/ConsolidateModal.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/assessmentTable/DpEditFieldMultiSelect.vue
  client/js/components/statement/assessmentTable/DpEditFieldSingleSelect.vue
  client/js/components/statement/assessmentTable/DpFilterModal.vue
  client/js/components/statement/assessmentTable/FilterModalSelectItem.vue
  client/js/components/statement/fragment/Edit.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  client/js/components/statement/statement/SelectStatementCluster.vue
  client/js/components/user/DpUserFormFields.vue
  client/js/components/user/MasterToebListMerge/MasterToebListMerge.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_cluster_detail_statement_data.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/fragment_list_filter.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/fragment_statement_form.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_edit_boilerplate.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_edit_master.html.twig
Labels: type:bug, review:frontend, lifecycle:do-not-merge

#1397 feat update demosplan_ui
  yarn.lock
Labels: review:frontend

#1331 chore: make the number of logfiles to keep configurable
  demosplan/DemosPlanCoreBundle/Resources/config/packages/monolog.yaml
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
Labels: review:backend, quick-win

#1399 bug(refs T32855): Import Vue
  client/js/store/procedure/SplitStatementStore.js
Labels: type:bug, review:frontend

#1403 refactor(refs T30969): move DpRegisterFlyout
  client/js/bundles/core/publicDetail.js
  client/js/bundles/faq/faqlist.js
  client/js/bundles/map/publicDetail.js
  client/js/bundles/misccontent/dataProtection.js
  client/js/bundles/misccontent/genericBundle.js
  client/js/bundles/procedure/publicIndexMapFull.js
  client/js/bundles/user/alternativeLogin.js
  client/js/bundles/user/citizenRegisterForm.js
  client/js/bundles/user/listOrgas.js
  client/js/bundles/user/listUser.js
  client/js/bundles/user/orgaRegisterForm.js
  client/js/bundles/user/resetPassword.js
  client/js/bundles/user/setPassword.js
  client/js/components/user/DpCreateItem.vue
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
  client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue
  client/js/components/user/DpUserList/DpUserFormFields.vue
  client/js/components/user/DpUserList/DpUserList.vue
  client/js/components/user/DpUserList/DpUserListItem.vue
  client/js/components/user/RegisterFlyout.vue
Labels: review:frontend, type:enhancement

#1404 Fix(refs:T32828): styling of checkmark is incorrect
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitstatement.scss
Labels: type:bug, review:frontend

#1407 Use distinct filenames for css entry points
  config.webpack.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig
Labels: type:bug, review:frontend

#1412 F T32871 new map layer cannot be created
  demosplan/DemosPlanCoreBundle/Logic/Maps/GetCapabilitesRpcMethodSolver.php
Labels: type:bug, review:backend, quick-win

#1413 Fix(refs:32940): incorrect view by fullscreen
  client/js/components/map/map/DpOlMap.vue
Labels: type:bug, review:frontend

#1362 chore: do not be overly specific in user provider
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/UserFromSecurityUserProvider.php
Labels: review:backend, quick-win

#1363 feat (refs T32782): simplify WeakPassword check
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/LoginFormAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/WeakPasswordCheckerBadge.php
  demosplan/DemosPlanCoreBundle/Security/HTTP/EventListener/WeakPasswordCheckerEventListener.php
Labels: type:bug, review:backend

#1437 fix (refs T32934): Improve performance on check permissions
  demosplan/DemosPlanCoreBundle/Permissions/PermissionResolver.php
Labels: review:backend

#1441 fix (refs T32994): Add E2E Hook/Selector.
  client/js/components/statement/assessmentTable/TocView/SearchAndSorting.vue
Labels: review:frontend, quick-win, type:enhancement

#1414 bug(refs T32938): fix dropdown does not show correct value
  client/js/components/map/map/DpOlMapScaleSelect.vue
Labels: type:bug, review:frontend
