Repository demos-europe/demosplan-core, pull requests merged in 2023-08, with the labels that each got.

#1791 chore: keycloak group role string needs to be configurable
  config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
  demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakUserData.php
Labels: review:backend

#1794 bug(refs T34112): Import missing component
  client/js/bundles/document/elementsAdminList.js
Labels: type:bug, review:frontend

#1798 Fix(T34156): name is not displayed completely (AT)
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
Labels: review:frontend, quick-win

#1799 fix (refs T34139): allow resource type code reusabiliy
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/DoctrineOrmPartialDTOProvider.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/DqlFluentQuery.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/EntityFetcher.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/FluentProcedureQuery.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/FluentStatementQuery.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiResourceTypeService.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/PartialDTO.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/DplanResourceType.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/DplanResourceTypeTrait.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFragmentService.php
  demosplan/DemosPlanCoreBundle/Repository/CoreRepository.php
  demosplan/DemosPlanCoreBundle/Repository/FluentRepository.php
  demosplan/DemosPlanCoreBundle/Repository/FragmentElasticsearchRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/BoilerplateResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ContextualHelpResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/FileResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/GlobalNewsResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/MasterToebResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureNewsResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/RoleResourceType.php
  demosplan/DemosPlanCoreBundle/ValueObject/APIPagination.php
Labels: type:bug, review:backend

#1788 Activate missing permission for fragments in robobsh and remove it from core and all other projects
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: type:bug, review:backend, type:enhancement

#1801 Fix(T34174): issue with lists and their numbering
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_at.scss
Labels: review:frontend

#1808 chore: Fix jest tests
  tests/frontend/unit/__snapshots__/SearchModal.spec.js.snap
Labels: review:frontend

#1806 chore (refs T34194): fix anonymous user login
  demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/ApiUserProvider.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php
Labels: type:bug, review:backend

#1823 chore (refs T34139): fix connection to data services
  demosplan/DemosPlanCoreBundle/Entity/User/AiApiUser.php
  demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
  demosplan/DemosPlanCoreBundle/Entity/User/FunctionalUser.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/AiApiUserProvider.php
Labels: type:bug, review:backend

#1822 Fix(T34155): console issue: uncaught (in promise) DOMException
  client/js/lib/statement/AssessmentTableOriginal.js
Labels: review:frontend

#1802 Fix(refs:34175): docx export is empty
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
Labels: type:bug, review:frontend

#1835 fix(refs T34274): Safely generate imprint route
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanCustomerController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/customer_settings.html.twig
Labels: type:bug, review:frontend, review:backend

#1840 upgrade demosplan-ui to the latest 0.1.11 version
  yarn.lock
Labels: review:frontend, quick-win

#1841 update yarl.lock file with the right version of the demosplan-ui
  yarn.lock
Labels: review:frontend

#1842 Fix(T34174): bulleted and numbered lists issue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_public-statement.scss
Labels: review:frontend

#1805 chore: refs T33926 fix votes
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  tests/backend/core/Statement/Functional/StatementServiceTest.php
Labels: type:bug, review:backend

#1853 feature: split too long line
  demosplan/DemosPlanCoreBundle/Logic/CurrentContextProvider.php
  demosplan/DemosPlanCoreBundle/Logic/User/CustomerService.php
Labels: review:backend, quick-win, type:enhancement

#1843 feature (refs T33365): Set DocX language to german
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ExportReportService.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Labels: review:backend

#1849 Fix(refs:T34211): publicdetail style incomplete
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
Labels: type:bug, review:frontend

#1854 fix(refs T34313): Set active Tab
  client/js/bundles/statement/listFinalGroup.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/proceduremenu_statements.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_final_group.html.twig
Labels: type:bug, review:frontend

#1490 F t29585 adding addon controller paths
  demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php
  demosplan/DemosPlanCoreBundle/Addon/AddonRoutingLoader.php
  demosplan/DemosPlanCoreBundle/Addon/ManifestConfiguration.php
Labels: review:backend, type:enhancement, type:story

#1855 chore (refs T33945): add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_boilerplate.html.twig
Labels: review:frontend, type:enhancement

#1857 feature (refs T34299): disable core permission 'field_statement_polygon'
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: type:bug, review:backend

#1856 chore (refs T33948): add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate_group.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1852 Fix:(T34286) incorrect time in the statement versions
  demosplan/DemosPlanCoreBundle/Repository/DraftStatementRepository.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/versions_of_statement.html.twig
Labels: review:frontend, review:backend

#1785 Use demosplan-ui z-index vars + Tailwind utilities
  client/js/components/map/map/DpOlMapEditFeature.vue
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
  client/js/components/procedure/publicindex/drawer/Drawer.vue
  client/js/components/procedure/publicindex/map/Map.vue
  client/js/components/statement/DpBoilerPlate.vue
  client/js/components/statement/segments/DpInsertableRecommendation.vue
  client/js/components/user/DpUserList/DpUserListItem.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_actionmenu.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_at.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_flyout.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_jumpnav.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_loading.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_nav.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_notify.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_slidebar.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitbutton.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitstatement.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_timepicker.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_treelist.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/core_style.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_flyout.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_modal.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_simple-toggle.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_toggle.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_tooltip.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_wizard.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_z-index.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/index.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_list.html.twig
Labels: review:frontend, type:enhancement

#1860 chore (refs T34082): add missing Hooks/Selectors & E2E Props.
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1868 chore (refs T34037): add E2E Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/sidemenu.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1862 fix(refs T29585): improves the default value handling for addon controller_paths
  demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php
  demosplan/DemosPlanCoreBundle/Addon/ManifestConfiguration.php
Labels: review:backend, quick-win, type:enhancement

#1650 feat: Adds dplanPermissions attribute
  demosplan/DemosPlanCoreBundle/Annotation/DplanPermissions.php
  demosplan/DemosPlanCoreBundle/Attribute/DplanPermissions.php
  demosplan/DemosPlanCoreBundle/EventListener/CheckPermissionListener.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: review:backend, type:enhancement

#1866 fix(refs T34144): Make Request syncronouse again
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#1871 refactor(refs T31187): move DpDashboardTaskCard to demosplan
  client/js/bundles/procedure/administrationDashboard.js
  client/js/components/procedure/DpDashboardTaskCard.vue
Labels: review:frontend, type:enhancement

#1861 fix(refs T34317): Add Hours to timestamp
  client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
Labels: type:bug, review:frontend

#1890 Rename component to use agnostic name
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/EditableText.vue
  client/js/components/statement/assessmentTable/Fragment.vue
Labels: review:frontend

#1874 fix(refs T33908): Prevent map from panning/zooming out of extent
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#1891 fix(refs T34194): Fix jwt calls
  demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/ApiUserProvider.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php
Labels: type:bug, review:backend

#1892 fix: correct some rather small padding issues
  client/js/components/user/samlLoginForm/SamlLoginForm.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_form.scss
Labels: review:frontend

#1893 fix(refs T33908): use set extent to stay within the allowed area of the map
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#1876 chore: Refactor `createLayerSource()`
  client/js/components/map/publicdetail/Map.vue
Labels: review:frontend, type:enhancement

#1898 feature (refs T32983): adjust composer.lock
  composer.lock
Labels: review:backend

#1899 feature (refs T32983): Use ProcedureInterface instead of Procedure
  demosplan/DemosPlanCoreBundle/Addon/RpcAddonAssetsLoader.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AbstractRpcStatementBulkAction.php
  demosplan/DemosPlanCoreBundle/Logic/Consultation/RpcManualTokenCreator.php
  demosplan/DemosPlanCoreBundle/Logic/Document/RpcElementsBulkEditor.php
  demosplan/DemosPlanCoreBundle/Logic/Elements/RpcElementsListReorderer.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureGeolocatorRpcMethod.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/RpcProcedureAnalytics.php
  demosplan/DemosPlanCoreBundle/Logic/RpcElasticsearchDefinitionFetcher.php
  demosplan/DemosPlanCoreBundle/Logic/RpcProcedureCoupleTokenUsageChecker.php
  demosplan/DemosPlanCoreBundle/Logic/RpcStatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcBulkEditor/RpcSegmentsBulkEditor.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcSegmentFacetsProvider.php
  demosplan/DemosPlanCoreBundle/Logic/Workflow/RpcPlaceListReorder.php
Labels: review:backend

#1870 feature (refs T29719): fix for csv exports
  demosplan/DemosPlanCoreBundle/Controller/Admin/DemosPlanAdminController.php
  demosplan/DemosPlanCoreBundle/Controller/Forum/DemosPlanReleaseController.php
Labels: review:backend, quick-win

#1875 F t29719 fix orga user statistic export
  demosplan/DemosPlanCoreBundle/Controller/Admin/DemosPlanAdminController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAdmin/statistics.csv.twig
Labels: review:frontend, review:backend

#1902 feature (T28333) : add new error message for wrong selected xls impor…
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend

#1909 chore: Remove unused prosemirror
  client/fe/webpack/resolveAliases.js
  client/js/lib/procedure/prosemirrorRanges/commands.js
  client/js/lib/procedure/prosemirrorRanges/marks.js
  client/js/lib/procedure/prosemirrorRanges/plugins.js
  client/js/lib/procedure/prosemirrorRanges/utilities.js
  package.json
  yarn.lock
Labels: review:frontend, type:enhancement

#1910 feature (refs T33807): fix path within the services.yml
  config/services.yml
Labels: type:bug, quick-win

#1923 chore: External orga id from identity provider can be longer than 36 chars
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/08/Version20230830135400.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
Labels: type:bug, review:backend, quick-win

#1934 bump demosplan-ui 0.1.13
  yarn.lock
Labels: review:frontend
