Repository demos-europe/demosplan-core, pull requests merged in 2023-02, with the labels that each got.

#665 fix (refs T30603): remove leftovers from bunde refactoring
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  demosplan/DemosPlanCoreBundle/Resources/config/services_autowire.yml
  demosplan/DemosPlanFaqBundle/DemosPlanFaqBundle.php
  demosplan/DemosPlanMiscContentBundle/DemosPlanMiscContentBundle.php
Labels: review:backend

#708 feature (refs T25539): display actual date instead of ### in xlsx export
  demosplan/DemosPlanCoreBundle/Logic/Consultation/BulkLetterExporter.php
Labels: type:bug, review:backend, quick-win

#730 feature (refs T26712): put empty filters back to es aggregations
  demosplan/DemosPlanStatementBundle/Logic/StatementService.php
Labels: type:bug, review:backend

#766 bug(refs T31159): Add check for empty array
  client/js/components/map/map/DpOlMap.vue
Labels: type:bug, review:frontend, quick-win

#738 fix(refs T31070): fix accuracy in measure tools
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#736 feat: addon frontend loading
  client/js/bundles/procedure/administrationDashboard.js
  client/js/components/addon/AddonWrapper.vue
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_dashboard.html.twig
Labels: review:frontend

#762 feat(refs T31218): Fix docx encoding
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
Labels: type:bug, review:backend, quick-win

#726 refactor: reduce method complexity and duplication
  demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
Labels: review:backend

#753 feature (refs T25516): add bom at start of csv file in order to make MS-excel display umlauts correctly
  demosplan/DemosPlanCoreBundle/Controller/Admin/DemosPlanAdminController.php
  demosplan/DemosPlanCoreBundle/Controller/Forum/DemosPlanReleaseController.php
Labels: type:bug, review:backend, quick-win

#751 Fix(refs:T25930): Add boilerplate and link-button in tiptap for consideration
  client/js/components/statement/assessmentTable/Fragment.vue
Labels: type:bug, review:frontend

#785 fix(refs T31229): add wysiwyg filter
  templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/new_public_participation_statement_vote.html.twig
Labels: type:bug, review:frontend, quick-win

#787 Improve display of statement count
  client/js/components/procedure/admin/AdministrationProceduresList.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#788 Use correct import syntax
  client/js/bundles/faq/faqlist.js
Labels: type:bug, review:frontend

#793 Add spacing to button row
  templates/bundles/DemosPlanStatementBundle/DemosPlanAssessment/cluster_detail.html.twig
Labels: type:bug, review:frontend

#760 fix(refs:T25931): Add strikethrough and remove insertAndDelete
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
Labels: type:bug, review:frontend, quick-win

#790 Fix(refs:T31192): Move the files from DemosPlanMiscContentBundle to DemosPlanCoreBundle
  demosplan/DemosPlanCoreBundle/Controller/MiscContent/DemosPlanMiscContentController.php
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/accessibility_explanation.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/components.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/components_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/contact.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/contact_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/data_protection.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/data_protection_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/data_protection_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/documents.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/how_to_login.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/imprint.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/imprint_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/information.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/sign_language.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/simple_language.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/term-of-use.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/terms_of_use.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/xplan.html.twig
Labels: type:bug, review:frontend, review:backend

#796 fix(refs T31291, T31301): Catch undefined Reset measuretools
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#768 feature (refs T31096): Show statement attachments in originalSTNView
  client/js/store/statement/Statement.js
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/DplanResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementAttachmentResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Labels: type:bug, review:frontend, review:backend

#797 Make pagination + selection work within orig-stn-list
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  client/js/store/statement/Statement.js
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/dhtml/v1/assessment_table_original_view.html.twig
Labels: type:bug, review:frontend

#804 fix(refs T31311): bump demosplan-ui
  yarn.lock
Labels: type:bug, review:frontend

#803 fix(refs T29992): disable button if statement is not claimed
  client/js/components/statement/listStatements/ListStatements.vue
Labels: type:bug, review:frontend

#782 feature (refs T31210): include email in authorizedUsersExport
  demosplan/DemosPlanCoreBundle/Logic/Consultation/BulkLetterExporter.php
Labels: type:bug, review:backend, quick-win

#752 Feat(refs T30254): New addon
  client/js/bundles/procedure/administrationNew.js
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureListController.php
  demosplan/DemosPlanCoreBundle/Resources/config/permissions.yml
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_new.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#806 feature (refs T31171): show flash messages again
  demosplan/DemosPlanAssessmentTableBundle/Logic/AssessmentTableServiceStorage.php
  demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
  demosplan/DemosPlanCoreBundle/Logic/CoreHandler.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeDisplayHandler.php
  demosplan/DemosPlanCoreBundle/Logic/LegacyFlashMessageCreator.php
  demosplan/DemosPlanMapBundle/Logic/MapHandler.php
Labels: type:bug, review:backend

#729 chore: add missing override hook to permissions
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: review:backend

#664 refactor (refs T30603): integrate ForumBundle into CoreBundle
  demosplan/DemosPlanCoreBundle/Controller/Forum/DemosPlanForumBaseController.php
  demosplan/DemosPlanCoreBundle/Controller/Forum/DemosPlanReleaseController.php
  demosplan/DemosPlanCoreBundle/Entity/Forum/DevelopmentRelease.php
  demosplan/DemosPlanCoreBundle/Entity/Forum/DevelopmentUserStory.php
  demosplan/DemosPlanCoreBundle/Entity/Forum/DevelopmentUserStoryVote.php
  demosplan/DemosPlanCoreBundle/Entity/Forum/ForumEntry.php
  demosplan/DemosPlanCoreBundle/Entity/Forum/ForumEntryFile.php
  demosplan/DemosPlanCoreBundle/Entity/Forum/ForumThread.php
  demosplan/DemosPlanCoreBundle/Logic/Forum/ForumHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Forum/ForumService.php
  demosplan/DemosPlanCoreBundle/Repository/DevelopmentReleaseRepository.php
  demosplan/DemosPlanCoreBundle/Repository/DevelopmentUserStoryRepository.php
  demosplan/DemosPlanCoreBundle/Repository/DevelopmentUserStoryVoteRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ForumEntryFileRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ForumEntryRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ForumThreadRepository.php
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services_repositories.yml
  demosplan/DemosPlanForumBundle/DemosPlanForumBundle.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_index.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_export.csv.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_list_card.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_threadentry_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_threadentry_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_threadentry_list_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_threadentry_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_send_moderator_notification_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/forum_send_author_notification_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/forum_send_moderator_notification_email.html.twig
  tests/backend/core/Forum/Functional/ForumDevelopmentTest.php
  tests/backend/core/Forum/Functional/ForumServiceTest.php
Labels: review:frontend, review:backend

#809 Make optgroup appear bold
  client/js/components/statement/assessmentTable/DpEditFieldMultiSelect.vue
  templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/includes/fragment_statement_form.html.twig
Labels: type:bug, review:frontend, quick-win

#802 fix(refs T31312): Allow access to hashedQuery via API
  demosplan/DemosPlanCoreBundle/ResourceTypes/HashedQueryResourceType.php
Labels: type:bug, review:backend

#805 fix (refs T31312): use correct access modifier in value object
  demosplan/DemosPlanStatementBundle/ValueObject/CountyNotificationData.php
Labels: type:bug, review:backend

#808 Also use initial filters to show fragment toggle
  client/js/components/statement/assessmentTable/DpFragmentsSwitcher.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/store/statement/Filter.js
Labels: type:bug, review:frontend

#816 Fix: remove DemosPlanFaq from configs yaml
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
Labels: type:bug, review:backend, quick-win

#810 fix (refs T31331): move UI-logic into twig
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php
  templates/bundles/DemosPlanStatementBundle/DemosPlanAssessment/view_statement.html.twig
Labels: review:frontend, review:backend

#827 fix: fixtures should use proper Dependency Injection instead of container
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/DemosFixture.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadUserData.php
Labels: review:backend

#830 fix: restore needed constant
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadUserData.php
Labels: type:bug, review:backend

#825 bug(refs: T29346): fix map modal is not toggling
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
Labels: review:frontend

#826 bug(refs: T31401): fix wrong translation in master toeb list
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig
Labels: review:frontend, quick-win

#833 feat (refs T31375): use env var to connect to rabbitmq
  .env
  demosplan/DemosPlanCoreBundle/Resources/config/config_dev_container.yml
  demosplan/DemosPlanCoreBundle/Resources/config/packages/old_sound_rabbit_mq.yaml
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
Labels: review:backend

#851 feature (refs T31310): addShould does not
  demosplan/DemosPlanStatementBundle/Logic/StatementService.php
Labels: type:bug, review:backend

#727 Fix phpstan issues with isset
  demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
  demosplan/DemosPlanCoreBundle/Entity/File.php
  demosplan/DemosPlanCoreBundle/Entity/Report/ReportEntry.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementMeta.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeRollbackVersionService.php
  demosplan/DemosPlanCoreBundle/Logic/ZipExportService.php
  demosplan/DemosPlanCoreBundle/ValueObject/LegacyResult.php
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureToLegacyConverter.php
  demosplan/DemosPlanReportBundle/Logic/ReportMessageConverter.php
  demosplan/DemosPlanStatementBundle/Logic/DraftStatementService.php
  demosplan/DemosPlanStatementBundle/Logic/ElasticSearchService.php
  demosplan/DemosPlanStatementBundle/Logic/StatementFragmentService.php
Labels: review:backend

#853 build: Disallow discovery composer plugin
  composer.json
Labels: devops, quick-win

#293 feat: integrate flood control addon into core
  demosplan/DemosPlanCoreBundle/Controller/Procedure/ConsultationController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Entity/Flood.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/FloodControlEventSubscriber.php
  demosplan/DemosPlanCoreBundle/Exception/CookieException.php
  demosplan/DemosPlanCoreBundle/Exception/FloodException.php
  demosplan/DemosPlanCoreBundle/Exception/HoneypotException.php
  demosplan/DemosPlanCoreBundle/Exception/IpFloodException.php
  demosplan/DemosPlanCoreBundle/Logic/FloodControlService.php
  demosplan/DemosPlanCoreBundle/Repository/FloodRepository.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
  demosplan/DemosPlanCoreBundle/Resources/config/packages/lexik_jwt_authentication.yaml
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services_repositories.yml
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/floodControl/honeypotFields.html.twig
  tests/backend/core/Core/Functional/FloodControlServiceTest.php
  tests/backend/core/Core/Functional/HoneypotTest.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#850 fix required follows optional parameter deprecation linkmessage
  demosplan/DemosPlanCoreBundle/Logic/LinkMessageSerializable.php
Labels: review:backend

#854 feature (refs T30295): allow to configure external links section
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
Labels: review:backend, type:story

#849 fix required follows optional parameter deprecation procedureservice
  demosplan/DemosPlanProcedureBundle/Form/AbstractProcedureFormType.php
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureHandler.php
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureService.php
  demosplan/DemosPlanProcedureBundle/Logic/ServiceOutput.php
  tests/backend/core/Procedure/Functional/ProcedureServiceTest.php
Labels: review:backend

#721 Feat T30254 more adjustments for addons
  .env
  client/js/bundles/document/elementsAdminList.js
  client/js/bundles/procedure/administrationNew.js
  client/js/components/addon/AddonWrapper.vue
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
  composer.lock
  demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
  demosplan/DemosPlanCoreBundle/Addon/RpcAddonAssetsLoader.php
  demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
  demosplan/DemosPlanCoreBundle/Command/Helpers/Helpers.php
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
  demosplan/DemosPlanCoreBundle/Controller/GenericRpcController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureListController.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/DemosFixture.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadUserData.php
  demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
  demosplan/DemosPlanCoreBundle/Event/Document/ElementsAdminListSaveEvent.php
  demosplan/DemosPlanCoreBundle/Event/EventConcernTrait.php
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostNewProcedureCreatedEvent.php
  demosplan/DemosPlanCoreBundle/Event/Procedure/PreNewProcedureCreatedEvent.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/ProcedureCoupleTokenSubscriber.php
  demosplan/DemosPlanCoreBundle/Resources/config/config_dev_container.yml
  demosplan/DemosPlanCoreBundle/Resources/config/packages/lock.yaml
  demosplan/DemosPlanCoreBundle/Resources/config/packages/old_sound_rabbit_mq.yaml
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Resources/config/permissions.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanDocumentBundle/Logic/ElementsService.php
  demosplan/DemosPlanDocumentBundle/Logic/SingleDocumentHandler.php
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureService.php
  demosplan/DemosPlanProcedureBundle/Logic/ServiceStorage.php
  package.json
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/elements_admin_list.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_new.html.twig
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig
  translations/messages+intl-icu.de.yml
  yarn.lock
Labels: review:backend, type:story

#862 feat: use relative path in addon to be compatible with different environments
  demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
  demosplan/DemosPlanCoreBundle/Addon/Registrator.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
Labels: review:backend

#868 chore (refs T30974): change name of variables for (color brand main).
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-color-assignment.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-color-palette.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_trumps-3rd-party-resets.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_callout.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_proceduresearch.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitstatement.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_timepicker.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_multiselect.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_objects-cardboxes.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_switcher.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_wizard.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/token/_color.scss
Labels: review:frontend, type:enhancement

#870 bug(refs: T31401): fix edit menu does not trigger when selecting single statements in a-table
  client/js/components/statement/assessmentTable/TocView/AssessmentTableGroup.vue
Labels: review:frontend

#873 fix (refs T31518): Use Event that is triggered on manual login
  demosplan/DemosPlanCoreBundle/EventSubscriber/UserLoginSubscriber.php
Labels: review:backend

#874 Fix(refs:T31536): Change the naming from the button
  client/js/components/user/DpMasterToebList/DpInviteMasterToeb.vue
Labels: type:bug, review:frontend, quick-win

#878 fix: remove bogus import in Test
  tests/backend/core/Map/Functional/MapCapabilitiesLoaderTest.php
Labels: review:backend, quick-win

#879 fix: avoid syntax error in migrate command
  demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php
Labels: review:backend, quick-win

#877 bug(refs T23632): enable automatic name extraction in bimschg antrag x
  client/js/bundles/procedure/administrationNew.js
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  client/js/store/procedure/NewProcedure.js
Labels: review:frontend

#880 feat: Log errors that occur in rpc actions
  demosplan/DemosPlanCoreBundle/Logic/Rpc/RpcErrorGenerator.php
Labels: review:backend

#872 feature (refs T31435): delete boilerplates of boilerplateGroup on GroupDelete
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Labels: type:bug, review:backend

#856 Feat_T31342: adjust design: STN modal window - diplanbau
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
Labels: review:frontend

#871 Feat_(T31035): adjust design: global news list - diplanbau
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_index_globalnewslist.html.twig
Labels: review:frontend

#718 F t31116 add routing props from demosplan UI
  client/js/components/map/map/DpOlMap.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImport.vue
  client/js/components/procedure/AdministrationImport/StatementPdfImport/StatementPdfImport.vue
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/procedure/SegmentsList/CustomSearch.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/basicSettings/ProcedureCoordinateGeolocation.vue
  client/js/components/procedure/listSubscriptions/ListSubscriptions.vue
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/assessmentTable/TiptapEditText.vue
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig
  templates/bundles/DemosPlanCoreBundle/Extension/fileupload.html.twig
  templates/bundles/DemosPlanCoreBundle/UI/form/editor.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/includes/single_document_file_upload.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/paragraph_admin_new.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_dashboard.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_member_email.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_send_email.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/customer_settings_update_mail.html.twig
  yarn.lock
Labels: review:frontend, type:enhancement
