Repository demos-europe/demosplan-core, pull requests merged in 2023-12, with the labels that each got.

#2395 F T35528 make support contact work the same support email
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/11/Version20231129120204.php
  demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
  demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerContactResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerLoginSupportContactResourceType.php
Labels: review:frontend, review:backend

#2423 feature (refs T35690): rollback changes in CsrfSubscriber due to
  demosplan/DemosPlanCoreBundle/EventSubscriber/CsrfSubscriber.php
Labels: type:bug

#2331 feat (refs T33577): bring dplan-core into line with demosplan-addon changes
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/Logic/Document/DocumentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Document/ElementsService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/PrepareReportFromProcedureService.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryResourceType.php
  tests/backend/core/Core/Functional/CsrfSubscriberTest.php
  tests/backend/core/Document/Functional/ElementsServiceTest.php
Labels: review:backend

#2353 chore: change composer php constraint syntax
  composer.json
Labels: review:backend

#2365 refactor(refs T19759): make filter modal work again [vue 3 upgrade]
  .github/dependabot.yml
  client/fe/webpack/moduleRules.js
  client/js/InitVue.js
  client/js/VueConfigLocal.js
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/admin/InstitutionTagManagement.vue
  client/js/components/statement/assessmentTable/AssignEntityModal.vue
  client/js/components/statement/assessmentTable/ConsolidateModal.vue
  client/js/components/statement/assessmentTable/CopyStatementModal.vue
  client/js/components/statement/assessmentTable/DpExportModal.vue
  client/js/components/statement/assessmentTable/DpFilterModal.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
  client/js/components/statement/assessmentTable/DpMoveStatementModal.vue
  client/js/components/statement/assessmentTable/FilterModalSelectItem.vue
  client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue
  client/js/components/statement/assessmentTable/TocView/SearchAndSorting.vue
  client/js/store/statement/Filter.js
  package.json
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/includes/search_and_sorting.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig
  yarn.lock
Labels: review:frontend

#2425 feat(refs T32925): Add Fullscreen-mode for A-Table-item-rows
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/ItemRow.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_at.scss
Labels: review:frontend, type:story

#2424 F vue3 async components
  client/js/bundles/procedure/administrationProcedureTypeEdit.js
  client/js/bundles/procedure/institutionTagManagement.js
  client/js/bundles/user/customersettingsmail.js
  client/js/components/document/DpElementAdminEdit.vue
  client/js/components/document/ElementsList.vue
  client/js/components/map/publicdetail/DpPublicDetail.vue
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/procedure/StatementSegmentsList/SegmentCommentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
  client/js/components/procedure/basicSettings/DpMasterBasicSettings.vue
  client/js/components/procedure/listSubscriptions/ListSubscriptions.vue
  client/js/components/procedure/publicindex/Procedures.vue
  client/js/components/statement/DpPublicDetailNoMap.vue
  client/js/components/statement/assessmentTable/DetailView/DetailView.vue
  client/js/components/statement/assessmentTable/DetailView/DetailViewFinalEmailBody.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/EditableText.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/statement/DpStatementPublish.vue
  client/js/components/statement/statement/DpVersionHistory.vue
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue
  client/js/components/user/DpCreateItem.vue
  client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue
  client/js/components/user/DpUserList/DpUserList.vue
  client/js/components/user/DpUserListExtended.vue
Labels: review:frontend, support:frontend, type:enhancement

#2438 feature (refs T33578): update composer.lock to demosplan-addon v0.13
  composer.lock
Labels: review:backend

#2442 f text field is not required
  demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
Labels: review:backend, quick-win

#2445 chore (refs T35631): Filter out segments with less than 10 characters
  client/js/store/procedure/SplitStatementStore.js
Labels: review:frontend

#2439 Remove deprecated utility
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImportErrors.vue
  client/js/components/procedure/SegmentsBulkEdit/SelectedTagsList.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/SegmentComment.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/admin/AdministrationPlaces.vue
  client/js/components/procedure/admin/TagList.vue
  client/js/components/statement/DpBoilerPlate.vue
  client/js/components/statement/segments/DpInsertableRecommendation.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  client/js/components/user/MasterToebListMerge/MasterToebListMerge.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_border-radius.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/index.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_list.html.twig
Labels: review:frontend, type:enhancement

#2376 bug (refs T28449): Add tooltip for aggregation filter items
  client/js/bundles/procedure/administrationMemberList.js
  client/js/bundles/statement/listTags.js
  client/js/components/document/ElementsAdminItem.vue
  client/js/components/news/DpNewsAdminList.vue
  client/js/components/news/DpNewsItemStatus.vue
  client/js/components/procedure/SegmentsList/FilterFlyoutCheckbox.vue
  client/js/components/statement/DpStatementAnonymize.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
Labels: type:bug, review:frontend

#2437 F t19786 vue3 emits option
  client/js/components/map/map/DpOlMapDragZoom.vue
  client/js/components/map/map/DpOlMapDrawFeature.vue
  client/js/components/map/map/DpOlMapDrawPoint.vue
  client/js/components/map/map/DpOlMapEditFeature.vue
  client/js/components/map/map/DpOlMapLayerVector.vue
  client/js/components/map/map/DpOlMapSetExtent.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/map/publicdetail/controls/CustomLayer.vue
  client/js/components/map/publicdetail/controls/DpUnfoldToolbarControl.vue
  client/js/components/map/publicdetail/controls/MapTools.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListCategory.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListWrapper.vue
  client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue
  client/js/components/report/DpReportGroup.vue
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/CopyStatementModal.vue
  client/js/components/statement/assessmentTable/DetailView/DetailView.vue
  client/js/components/statement/assessmentTable/DpEditField.vue
  client/js/components/statement/assessmentTable/DpEditFieldMultiSelect.vue
  client/js/components/statement/assessmentTable/DpExportModal.vue
  client/js/components/statement/assessmentTable/DpFragmentsSwitcher.vue
  client/js/components/statement/assessmentTable/DpMoveStatementModal.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/FilterModalSelectItem.vue
  client/js/components/statement/assessmentTable/FragmentsButton.vue
  client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue
  client/js/components/statement/assessmentTable/StatementButton.vue
  client/js/components/statement/assessmentTable/TableCardFlyoutMenu.vue
  client/js/components/statement/assessmentTable/TocView/AssessmentTableToc.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
  client/js/components/statement/publicStatementLists/DpPublicStatement.vue
  client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  client/js/components/user/DpCreateItem.vue
  client/js/components/user/DpMasterToebList.vue
  client/js/components/user/DpMasterToebList/DpDeleteMasterToeb.vue
  client/js/components/user/DpMasterToebList/DpFilterMasterToeb.vue
  client/js/components/user/DpMasterToebList/DpNewMasterToeb.vue
  client/js/components/user/DpMasterToebList/DpNewOrgaModal.vue
  client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue
  client/js/components/user/DpUserListExtendedItem.vue
Labels: review:frontend, support:frontend, type:enhancement

#2450 chore refs T35737: fix duplicate csrf token
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new.html.twig
Labels: review:frontend

#2269 feature (refs t33577): additional import features
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentExportController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Documents/FakeDocumentGenerator.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Images/FakeImageGenerator.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
  demosplan/DemosPlanCoreBundle/Logic/Document/ElementsService.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/AbstractStatementSpreadsheetImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilder.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporterInterface.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxStatementImport.php
  demosplan/DemosPlanCoreBundle/Tools/DocxImporterHttp.php
  translations/messages+intl-icu.de.yml
  translations/validators.de.yml
Labels: review:frontend, review:backend, type:story

#2458 feature (ref 35620): ignore token from post request form to use array…
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
Labels: type:bug, review:backend

#2466 F T35841 statement release to vht not possible
  demosplan/DemosPlanCoreBundle/Logic/RpcStatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Validator/CorrectDateOrderConstraintValidator.php
  translations/validators.de.yml
Labels: review:backend

#2444 feature (ref 33679): create a column for original statement in xlx fi…
  config/statement/assessment_export_options.yml
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/ZipResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableZipExporter.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#2467 f T35837 remove draft json validation
  demosplan/DemosPlanCoreBundle/Constraint/SegmentDraftJsonConstraint.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementResourceTypeService.php
  demosplan/DemosPlanCoreBundle/Validator/SegmentDraftJsonConstraintValidator.php
  tests/backend/core/Statement/Functional/StatementResourceTypeServiceTest.php
  translations/validators.de.yml
Labels: review:backend

#2404 bug (refs T27614): Refactor user form fields
  client/js/components/user/DpCreateItem.vue
  client/js/components/user/DpUserList/DpUserFormFields.vue
Labels: type:bug, review:frontend

#2363 F t33578 zip import
  client/js/components/procedure/AdministrationImport/ParticipationImport/ParticipationImport.vue
  config/services.yml
  config/statement/assessment_export_options.yml
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/AbstractStatementFromRowBuilder.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/AbstractStatementSpreadsheetImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilder.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilderWithZipSupport.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporterWithZipSupport.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/SimplifiedStatement/SimplifiedStatementCreator.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxSegmentImport.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxStatementImport.php
  demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Logic/ZipImportService.php
  demosplan/DemosPlanCoreBundle/Repository/FileContainerRepository.php
  tests/backend/core/Import/Abwaegungstabelle_Export_Error_Testfile.zip
  tests/backend/core/Import/Abwaegungstabelle_Export_Testfile.zip
  tests/backend/core/Import/ZipImportServiceTest.php
  tests/backend/core/Statement/Functional/StatementImportTest.php
  translations/messages+intl-icu.de.yml
  translations/validators.de.yml
Labels: review:backend, type:story

#2477 feat (refs T33578): Refactor test for ZipImportServiceTest
  tests/backend/core/Import/Abwaegungstabelle_Export_Error_Testfile.zip
  tests/backend/core/Import/Abwaegungstabelle_Export_Testfile.zip
  tests/backend/core/Import/ZipImportServiceTest.php
Labels: review:backend

#2472 feature (ref 33579): test for assessmentTableZipExporter
  tests/backend/core/Statement/Functional/StatementExportTest.php
Labels: review:backend, type:story

#2481 fix: T35881 fix path to fix reordering of elements
  demosplan/DemosPlanCoreBundle/Logic/Elements/RpcElementsListReorderer.php
Labels: review:backend, quick-win

#2482 F t35878 fix spaces in filenames
  demosplan/DemosPlanCoreBundle/Logic/ZipImportService.php
Labels: review:backend

#2483 fix: fix changed type back to string as needed
  demosplan/DemosPlanCoreBundle/Logic/ZipImportService.php
Labels: review:backend
