Repository demos-europe/demosplan-core, pull requests merged in 2023-07, with the labels that each got.

#1632 chore: fix platform requirements syntax
  composer.json
Labels: devops, quick-win

#1631 feature (refs T33776): Adjust event dispatch and code readability
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
Labels: review:backend, type:story

#1291 feat: allow tex to pdf implementation via external service
  config/parameters_default.yml
  config/services.yml
  demosplan/DemosPlanCoreBundle/Tools/PdfCreatorHttp.php
  demosplan/DemosPlanCoreBundle/Tools/PdfCreatorInterface.php
  demosplan/DemosPlanCoreBundle/Tools/PdfCreatorRabbitmq.php
  demosplan/DemosPlanCoreBundle/Tools/ServiceImporter.php
Labels: review:backend

#1636 Fix(T33451): issue with the projection being set to EPSG:25832
  client/js/components/map/admin/LayerSettings.vue
Labels: review:frontend

#1639 feature (refs T33554): fix procedure export
  demosplan/DemosPlanCoreBundle/Logic/ZipExportService.php
Labels: review:backend

#1638 F t33495 fix update of orgas
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/Repository/CoreRepository.php
Labels: review:backend

#1640 chore: fix fatal error after merge
  demosplan/DemosPlanCoreBundle/Tools/ServiceImporter.php
Labels: review:backend, quick-win

#1634 fix adjust events
  demosplan/DemosPlanCoreBundle/Event/Procedure/GetDatasheetFilePathAbsoluteEvent.php
  demosplan/DemosPlanCoreBundle/Event/Procedure/GetDatasheetVersionEvent.php
Labels: review:backend, quick-win

#1641 fix (ref:T30158) Define Statements files accessibility
  client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImport.vue
  client/js/components/procedure/AdministrationImport/StatementPdfImport/StatementPdfImport.vue
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachmentsLink.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/fragmentList/Fragment.vue
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
  client/js/components/statement/publicStatementLists/DpPublicStatement.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
  demosplan/DemosPlanDocumentBundle/Tools/ServiceImporter.php
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/includes/single_document_file_upload.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/paragraph_admin_new.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/single_document_admin_new.html.twig
  templates/bundles/DemosPlanMapBundle/DemosPlanMap/map_public_participation_detail.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_detail_form_statement.html.twig
Labels: type:bug, review:frontend, review:backend

#1642 fix(refs T33576): use correct id
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_data_entry.html.twig
Labels: type:bug, review:frontend

#1647 Fix ref T33572 error while managing faq
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqService.php
Labels: review:backend, quick-win

#1633 chore: fix deprecation in migration template
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/migration.tpl
Labels: review:backend, quick-win

#1648 fix(T33575): issue with the table when a row is expanded
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_toggle.scss
Labels: review:frontend

#1657 fix(refs T33353): Change way of replacing \n\r with blanks
  client/js/components/core/DpEditor/libs/handleWordPaste.js
Labels: review:frontend

#1659 chore (refs T33621): use SecurityUser in Authentication
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
Labels: type:bug, review:backend

#1651 fix (refs T33506): Fix statement status data by adding missing necessary 'freq' key.
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Labels: help wanted, review:backend

#1645 feature (refs T33519): add agency main email address to service output
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
Labels: review:backend

#1660 chore: restore routes that where swallowed by refactoring
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
Labels: review:backend

#1664 feature (refs T32796): create Migration for procedureMessage Table
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/07/Version20230706091408.php
Labels: review:backend

#1652 F adjust user entity
  composer.lock
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
Labels: review:backend

#1666 Prevent 2px jump of button
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
Labels: type:bug, review:frontend

#1620 chore (refs T30980): add spacing class for DpDataTableExtended.
  client/js/components/procedure/admin/AuthorizedUsersList.vue
  client/js/components/procedure/admin/DpAddOrganisationList.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAdmin/statistics.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/alternative_login.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1618 chore (refs T30980): add spacing & layout classes for DpBulkEditHeader.
  client/js/components/document/ElementsAdminList.vue
  client/js/components/news/DpNewsAdminList.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend, quick-win, type:enhancement

#1609 chore (refs T30980): add spacing classes for DpFormRow.
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  client/js/components/procedure/admin/NewBlueprintForm.vue
  client/js/components/user/citizenRegisterForm/CitizenRegisterForm.vue
  client/js/components/user/orgaRegisterForm/OrgaRegisterForm.vue
  client/js/components/user/samlLoginForm/SamlLoginForm.vue
Labels: review:frontend, quick-win, type:enhancement

#1604 chore (refs T30980): add some component classes.
  client/js/components/statement/DpStatementAnonymize.vue
Labels: review:frontend, quick-win, type:enhancement

#1668 fix(refs T33640): update getcapabilities-url @blur, not @input
  client/js/components/map/admin/LayerSettings.vue
  yarn.lock
Labels: type:bug, review:frontend

#1682 feature (refs T32782): check for weak passwords only after succesful login
  demosplan/DemosPlanCoreBundle/Security/HTTP/EventListener/WeakPasswordCheckerEventListener.php
Labels: review:backend, quick-win

#1680 feature (refs T32960): Also create a version of the original draftSTN on first update
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
Labels: type:bug, review:backend

#1681 chore: fix errors introduced by flex upgrade
  config/packages/doctrine.yaml
  phpunit.xml
Labels: review:backend, quick-win

#1693 chore: fix debug console command
  demosplan/DemosPlanCoreBundle/Logic/TransformMessageBagService.php
Labels: type:bug, review:backend, quick-win

#1686 feat: Remove unused properties in StatementService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: review:backend, quick-win

#1692 chore: upgrade passwords during test login
  config/packages/security.yaml
Labels: review:backend, quick-win

#1679 chore (refs T31115): add Translator.trans to dp-select options.
  client/js/components/document/ElementsAdminBulkEdit/ElementsAdminBulkEdit.vue
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new_master.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/list_statement_nofity_contries.html.twig
Labels: review:frontend, type:enhancement

#1696 fix: add missing method call parameter
  demosplan/DemosPlanCoreBundle/Logic/Statement/NonAuthorizedAssignRemover.php
Labels: type:bug, review:backend

#1691 chore: add core project files to gitignore
  .gitignore
Labels: review:frontend, review:backend, quick-win

#1697 feature (refs T32796): remove procedure from procedure_message table
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/07/Version20230711125038.php
Labels: review:backend, support:backend

#1702 chore (refs T33763): add missing Hooks/Selectors.
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1703 feature (refs T33429): add datenerfassung role in dataMapper and difi…
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
Labels: review:backend

#1711 feature (refs T32776): update composer.lock
  composer.lock
Labels: review:backend

#1712 chore: Bump demosplan-ui to v0.1.9
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-color.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/core_style.scss
  package.json
  yarn.lock
Labels: dependencies:yarn

#1704 feat(refs T12070): New back to top button
  client/js/InitVue.js
  client/js/components/button/BackToTopButton.vue
  client/js/lib/core/libs/GlobalEventListener.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_aside.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:enhancement

#1573 fix remove duplicated method
  demosplan/DemosPlanCoreBundle/Controller/Admin/DemosPlanAdminController.php
  demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
  demosplan/DemosPlanCoreBundle/Controller/Forum/DemosPlanReleaseController.php
  demosplan/DemosPlanCoreBundle/Controller/News/DemosPlanNewsController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureExportController.php
  demosplan/DemosPlanCoreBundle/Controller/Report/DemosPlanReportController.php
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentStatementFragmentController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/DocxResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/FileResponseGeneratorAbstract.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/PdfResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/XlsResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/NameGenerator.php
  tests/backend/core/Procedure/Functional/NameGeneratorTest.php
Labels: review:backend, type:enhancement

#1715 chore: fix leftover from rector that leads to duplicate validation
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
Labels: type:bug, review:backend, quick-win

#1714 fix: add missing JSON:API deletion permission check
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/DeletableDqlResourceTypeInterface.php
  demosplan/DemosPlanCoreBundle/Logic/JsonApiActionService.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/GlobalNewsResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureNewsResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/SignLanguageOverviewVideoResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Labels: type:bug, review:backend

#1721 B t33543 export file
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/DocxResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/FileResponseGeneratorAbstract.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/PdfResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/XlsResponseGenerator.php
Labels: review:backend

#1722 Fix(T33720): missing import of DpBoilerPlateModal
  client/js/components/statement/assessmentTable/DetailView/DetailView.vue
Labels: review:frontend, quick-win

#1683 fix(T33134): improve accessibility of flash notifications
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/user/samlLoginForm/SamlLoginForm.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#1724 chore (refs T33596): add missing Hooks/Selectors.
  client/js/components/procedure/admin/NewBlueprintForm.vue
Labels: review:frontend, quick-win, type:enhancement

#1726 fix: adapt padding to larger select spacing
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_edit-field.scss
Labels: type:bug, review:frontend, quick-win

#1734 chore (refs T33661): add missing Hooks/Selectors.
  client/js/components/button/BackToTopButton.vue
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/administration_list_pageheader.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1743 chore (refs T33662): add missing Hooks/Selectors.
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
Labels: review:frontend, quick-win, type:enhancement

#1742 chore (refs T33659): add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/password_recover.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1737 feature: add `PermissionEvaluatorInterface::requireAllPermissions`
  demosplan/DemosPlanCoreBundle/Exception/AccessDeniedException.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: review:backend

#1746 chore refs (T33737): Real user object should be stored in Token
  demosplan/DemosPlanCoreBundle/Entity/User/SecurityUser.php
  demosplan/DemosPlanCoreBundle/Logic/User/CurrentUserService.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
Labels: review:backend

#1749 fix(refs T33843): add gisLayer to master template
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
Labels: review:backend, type:enhancement

#1747 chore: fix DataFactory namespaces
  config/services.yml
  demosplan/DemosPlanCoreBundle/Command/Data/ReplaceFilesCommand.php
Labels: type:bug, review:backend, quick-win

#1701 F 32776 k3 communication related adjustments core
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqHandler.php
  demosplan/DemosPlanCoreBundle/Logic/News/ProcedureNewsService.php
Labels: review:backend

#1705 fix(refs T33148): Send Batch to add multiple Toeb to toeblist
  client/js/components/procedure/admin/DpAddOrganisationList.vue
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceLinkageFactory.php
Labels: type:bug, review:frontend, review:backend

#1736 Fix(T33838): the list style issue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
Labels: review:frontend, quick-win

#1741 feat: Adjustments to PostProcedureUpdatedEvent
  composer.lock
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureUpdatedEvent.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
Labels: review:backend, type:story

#1758 Fix(refs:33913): remove sh link section in diplanrog
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/new_public_participation_statement_vote.html.twig
Labels: type:bug, review:frontend

#1738 feature (refs T33839): remove permission field_statement_public_allow…
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: type:bug, review:backend

#1760 Remove ancient letter spacing
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_base.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-fonts.dplan.scss
Labels: review:frontend

#1763 feat(refs T27593): remove box-shadow utility in favor of tailwind
  client/js/components/procedure/publicindex/drawer/Drawer.vue
  client/js/components/procedure/publicindex/drawer/Handle.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_actionbox.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_actionmenu.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_card.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_editor-menububble.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_notify.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_slidebar.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitbutton.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_modal.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_box-shadow.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/index.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanAdmin/statistics.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/public_elements_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_threadentry_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_dashboard.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/sign_language.html.twig
Labels: review:frontend, type:enhancement

#1767 feature: add missing getProcedure method
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureUpdatedEvent.php
Labels: review:backend

#1748 Fix(refs:33886): up scroll button doesnt work sometimes if display size changes
  client/js/components/button/BackToTopButton.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
Labels: type:bug, review:frontend

#1761 remove float utility styles in favor of tailwind responsive classes
  client/js/components/procedure/survey/DpPublicSurvey.vue
  client/js/components/statement/assessmentTable/ConsolidateModal.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings.breakpoints.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/core_style.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_float.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/index.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/listentry_header.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_users_statements.html.twig
Labels: review:frontend, type:enhancement

#1770 fix(refs T33917): fixes the lookup of available projections
  client/js/components/map/admin/LayerSettings.vue
Labels: type:bug, review:frontend, quick-win

#1771 Fix(refs: T33866): remove copy consideration from fragments part
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: type:bug, review:backend

#1769 chore (refs T33736, T33711): Fix SecurityUser in session
  demosplan/DemosPlanCoreBundle/EventListener/DemosPlanResponseListener.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
  demosplan/DemosPlanCoreBundle/Logic/User/CurrentUserService.php
  demosplan/DemosPlanCoreBundle/Repository/UserRepository.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/AiApiUserProvider.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/ApiUserProvider.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SamlUserProvider.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/public_paragraph_document.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_draft.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_released_group.html.twig
Labels: type:bug, review:backend

#1779 bug(refs T33913): Remove hint for changing profile data
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/new_public_participation_statement_vote_content.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/new_public_participation_statement_vote.html.twig
Labels: type:bug, review:frontend

#1732 chore refs (T32195): pass core version to frontend
  config/config_core.yml
  config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/js/dplan.settings.js.twig
Labels: review:backend

#1780 bug(refs T33913): Remove hint for changing user data
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/new_public_participation_statement_confirm_content.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/new_public_participation_statement_vote_content.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/new_public_participation_statement_confirm.html.twig
Labels: type:bug, review:frontend

#1786 fix (refs T33736, T33711): SecurityUser needs to provide real salt
  demosplan/DemosPlanCoreBundle/Entity/User/SecurityUser.php
Labels: type:bug, review:backend

#1783 feat (T32776): correct parameter type for internal event method
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureUpdatedEvent.php
Labels: review:backend, quick-win
