Repository demos-europe/demosplan-core, pull requests merged in 2023-11, with the labels that each got.

#2239 feat (refs T35204): Adjust input validation
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerResourceType.php
Labels: review:backend

#2243 feature (ref 31243): set right key name for column name
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Labels: type:bug, review:backend

#2246 feature (ref 31243): set new key for name in potential area
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Labels: review:backend

#2212 refactor(refs T34504): Use json api instead of form
  client/js/bundles/user/customerSettings.js
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
  client/js/components/user/CustomerSettings/CustomerSettingsMap.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue
  client/js/store/core/VuexApiRoutes.js
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/BrandingResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/SignLanguageOverviewVideoResourceType.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:enhancement

#2247 Fix(refs:35292): change one word and grammar
  translations/messages+intl-icu.de.yml
Labels: type:bug

#2248 Fix(refs:T35301): remove unused buttons
  client/js/components/user/CustomerSettings/CustomerSettings.vue
Labels: type:bug, review:frontend, type:story

#2221 refactor: Declare fields when fetching orgas and use the proper rels
  client/js/bundles/user/listOrgas.js
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
Labels: review:frontend, review:backend, type:enhancement

#2252 feat (T35051): Implement ParagraphServiceInterface
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphService.php
Labels: review:backend, quick-win

#2257 B t35312 adjust styling for support card
  client/js/components/support/DpSupport.vue
  client/js/components/support/DpSupportCard.vue
Labels: review:frontend

#2188 feat(refs T33577): Add new import tab
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  client/js/components/procedure/AdministrationImport/ParticipationImport/ParticipationImport.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Constraint/ConsistentAnonymousOrgaConstraint.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/TusUploadEventSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/AbstractStatementSpreadsheetImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ImportError.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilder.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporterInterface.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxSegmentImport.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxStatementImport.php
  demosplan/DemosPlanCoreBundle/Logic/XlsxStatementImporterFactory.php
  demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php
  demosplan/DemosPlanCoreBundle/Validator/ConsistentAnonymousOrgaConstraintValidator.php
  tests/backend/core/Statement/Functional/StatementExcelImporterTest.php
  tests/backend/core/Statement/Functional/StatementServiceTest.php
  translations/messages+intl-icu.de.yml
  translations/validators.de.yml
Labels: review:frontend, review:backend

#2256 fix(refs T35316): pass email address to support card
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/login_idp_error.html.twig
Labels: type:bug, review:frontend

#2251 Fix(T33137): accessible notifications
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaSnailMailOrEmail.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupPostalAndCity.vue
Labels: review:frontend

#2274 bug(refs T35342): Use the correct property for submitter city
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
Labels: type:bug, review:frontend, quick-win

#2270 fix(refs T35139): pass slots to dp-multiselect and use them
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  client/js/components/user/CustomerSettings/CustomerSettings.vue
Labels: type:bug, review:frontend

#2279 F T35366 errors while import with additional columns
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporter.php
Labels: review:backend, quick-win

#2280 T17360: fix generate statement command as functional user has no id
  demosplan/DemosPlanCoreBundle/DataGenerator/CustomFactory/FactoryBase.php
  demosplan/DemosPlanCoreBundle/Entity/User/FunctionalUser.php
Labels: review:backend

#2288 fix(refs T35369) Display contact cards for none admins
  client/js/components/support/DpSupport.vue
Labels: type:bug, review:frontend

#2254 chore refs T35309: add csrf protection listener
  demosplan/DemosPlanCoreBundle/EventSubscriber/CsrfSubscriber.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/csrf.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  tests/backend/core/Core/Functional/CsrfSubscriberTest.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#2291 feat (refs T35314): fix invalid form on update/create ProcedureType
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureTypeService.php
Labels: review:backend

#2292 feat (refs T35314): cleanup
  demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureTypeController.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureTypeService.php
Labels: review:backend

#2301 Fix(refs: t34474): incorrect welcomepage
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/gateway_newUser.html.twig
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#2245 chore (refs T34968): minor improvements in DpBulkEditHeader Props.
  client/js/components/document/ElementsAdminList.vue
  client/js/components/news/DpNewsAdminList.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/statement/listStatements/ListStatements.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend, lifecycle:do-not-merge, quick-win, type:enhancement

#2300 Fix(T35378): adjust styling/display support contacts issue
  client/js/components/support/DpSupport.vue
  client/js/components/support/DpSupportCard.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerContactResourceType.php
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_support.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/login_idp_error.html.twig
  tests/backend/core/Statement/Functional/StatementImportTest.php
Labels: review:frontend

#2290 bug: Only show office hours if there are office hours
  client/js/components/support/DpSupportCard.vue
Labels: type:bug, review:frontend, quick-win

#2321 F t35348 error message when adding text while editing sections
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcBulkEditor/RpcSegmentsBulkEditor.php
  demosplan/DemosPlanCoreBundle/Repository/SegmentRepository.php
Labels: type:bug, review:backend

#2306 chore: Add required prop to test
  tests/frontend/unit/DpPublicStatement.spec.js
Labels: review:frontend, quick-win, type:enhancement

#1851 fix(refs T34297): Use Permission 'area_admin_boilerplates' in FE
  client/js/bundles/news/newsAdminEdit.js
  client/js/bundles/news/newsAdminNew.js
  client/js/bundles/procedure/administrationMemberEmail.js
  client/js/bundles/procedure/administrationSegmentsBulkEdit.js
  client/js/bundles/procedure/administrationSendEmail.js
  client/js/bundles/procedure/administrationStatementSegmentsList.js
  client/js/bundles/procedure/administrationUnregisteredPublicagencyEmail.js
  client/js/bundles/statement/assessmentStatement.js
  client/js/bundles/statement/assessmentTableView.js
  client/js/bundles/statement/bulkEditStatement.js
  client/js/bundles/statement/bulkEditStatementFragment.js
  client/js/bundles/statement/listStatementFragments.js
  client/js/bundles/user/customersettingsmail.js
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/statement/DpBoilerPlateModal.vue
  client/js/components/statement/assessmentTable/DetailView/DetailViewFinalEmailBody.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/assessmentTable/EditableText.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/includes/news_editor_boilerplate_modal.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/email_editor_boilerplate_modal.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/customer_settings_update_mail.html.twig
Labels: type:bug, review:frontend, type:enhancement

#2133 fix(refs T19759): Make the page load.
  client/fe/webpack/moduleRules.js
  client/js/InitVue.js
  client/js/VueConfigLocal.js
  client/js/components/addon/AddonWrapper.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/admin/AdministrationProceduresList.vue
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
  client/js/components/statement/DpBoilerPlateModal.vue
  client/js/components/statement/DpStatementAnonymize.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/store/core/initStore.js
  client/js/store/core/utils/storeUtils.js
  client/js/store/map/Layers.js
  client/js/store/procedure/Procedure.js
  client/js/store/procedure/SegmentFilter.js
  client/js/store/procedure/SegmentSlidebar.js
  client/js/store/procedure/SplitStatementStore.js
  client/js/store/statement/AssessmentTable.js
  client/js/store/statement/Filter.js
  client/js/store/statement/Fragment.js
  client/js/store/statement/Statement.js
  client/js/store/statement/Voter.js
  package.json
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation.html.twig
  templates/bundles/DemosPlanCoreBundle/Extension/contextual_help.html.twig
  yarn.lock
Labels: review:frontend

#2325 f_T35396 fix assignee filter
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/ResourceTypes/DepartmentResourceType.php
Labels: type:bug, review:backend

#2330 feat(refs T33536): tweak import menu entry in sidemenu
  config/menus.yml
  translations/messages+intl-icu.de.yml
Labels: review:frontend, quick-win, type:story

#2335 feature (ref 35482): statement interface instead of segment interface
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
Labels: review:backend

#2338 f_T35396 fix assignee filter
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/ResourceTypes/DepartmentResourceType.php
Labels: type:bug, review:backend

#2339 feature (refs T35367): Used the same logic to format the authoredDate as pdfExporter does
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
Labels: type:bug, review:backend

#2253 Fix php tests
  demosplan/DemosPlanCoreBundle/Command/ContainerInitCommand.php
  tests/backend/base/MockMethodDefinition.php
  tests/backend/core/Core/Functional/ContainerInitCommandTest.php
  tests/backend/core/Core/Functional/HoneypotTest.php
  tests/backend/core/Core/Functional/MailTest.php
  tests/backend/core/Core/Functional/ProcedureExtensionTest.php
  tests/backend/core/Core/Functional/ResourceLinkageFactoryTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/DateExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/IsNotExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/JsonDecodeExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/UCFirstExtensionTest.php
Labels: review:backend

#2078 chore: remove useless non-existing migration
  demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php
Labels: review:backend, quick-win

#2347 feature (refs T35528): Adjust the unique-constraint for support_conta…
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/11/Version20231121091548.php
Labels: type:bug, review:backend

#2354 feature (ref 35509): set Permission in Core
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig
Labels: type:bug, review:frontend

#2357 fix(refs: T34709): adjust button placement on public detail document view
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/public_elements_list.html.twig
Labels: type:bug, review:frontend, quick-win

#2356 fix(refs: T35510): add flex class to wrapper to align button properly
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/statement_detail_subheader.html.twig
Labels: type:bug, review:frontend, quick-win

#2359 feat(refs: T35297): prevent link from being purged from gfi response
  demosplan/DemosPlanCoreBundle/Services/Map/GetFeatureInfo.php
Labels: review:backend, quick-win

#2337 feat T33578: zip export
  client/js/components/procedure/AdministrationImport/ParticipationImport/ParticipationImport.vue
  client/js/components/statement/assessmentTable/DpExportModal.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  config/parameters_default.yml
  config/services.yml
  config/statement/assessment_export_options.yml
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureExportController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureListController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentExportController.php
  demosplan/DemosPlanCoreBundle/Exception/AssessmentTableZipExportException.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/ZipResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ExportService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentExportOptions.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableZipExporter.php
  demosplan/DemosPlanCoreBundle/Logic/ZipExportService.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story

#2355 chore (refs T35309): WIP: add csrf protection attr for Vue Post forms.
  client/js/components/document/ElementsList.vue
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImport.vue
  client/js/components/procedure/AdministrationImport/ParticipationImport/ParticipationImport.vue
  client/js/components/procedure/AdministrationImport/StatementFormImport/StatementFormImport.vue
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  client/js/components/procedure/admin/NewBlueprintForm.vue
  client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue
  client/js/components/procedure/listSubscriptions/ListSubscriptions.vue
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/TocView/AssessmentTableGroup.vue
  client/js/components/statement/assessmentTable/TocView/AssessmentTableGroupList.vue
  client/js/components/statement/fragment/Edit.vue
  client/js/components/statement/fragmentList/DpFragmentList.vue
  client/js/components/statement/fragmentList/Fragment.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  client/js/components/user/citizenRegisterForm/CitizenRegisterForm.vue
  client/js/components/user/orgaRegisterForm/OrgaRegisterForm.vue
  client/js/components/user/portalUser/ChangePassword.vue
  client/js/components/user/portalUser/SetPassword.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_view.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_view.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_convert_annotated_pdf.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_import.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new_master.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/list_subscriptions.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_user.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/user_set_password.html.twig
Labels: review:frontend, type:enhancement

#2374 feature (ref 35610): use statementinterface except segmentinterface
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
Labels: type:bug, review:backend

#2322 fix(refs T19759): fix warnings/errors [vue 3 upgrade]
  client/js/InitVue.js
  client/js/components/faq/DpFaqItem.vue
  client/js/components/map/map/DpOlMap.vue
  client/js/components/map/publicdetail/controls/DpUnfoldToolbarControl.vue
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImportErrors.vue
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
  client/js/components/procedure/basicSettings/DpEmailList.vue
  client/js/components/procedure/basicSettings/ExportSettings.vue
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/ConsolidateModal.vue
  client/js/components/statement/assessmentTable/DpEditFieldMultiSelect.vue
  client/js/components/statement/assessmentTable/DpFilterModal.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/FilterModalSelectItem.vue
  client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue
  client/js/components/statement/statement/SelectStatementCluster.vue
  client/js/components/statement/voter/StatementVoter.vue
  client/js/components/user/DpMasterToebList.vue
  client/js/directives/saveAndReturn.js
  client/js/directives/scroller.js
  client/js/plugins/DPVueCore.js
  config.webpack.js
  yarn.lock
Labels: review:frontend

#2369 chore: fix faulty catch reaction
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend, quick-win

#2368 chore: add version to addon list command
  demosplan/DemosPlanCoreBundle/Addon/Registrator.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonListCommand.php
  tests/backend/core/Core/Functional/AddonListCommandTest.php
Labels: review:backend

#2386 fix: Use correct Option to exclude pacakges from pattern
  .github/dependabot.yml
Labels: review:frontend, type:enhancement

#2377 bug (refs T34935): Move tooltip outside of label
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig
Labels: type:bug, review:frontend, quick-win

#2378 bug (refs T34593): Add more margin to beta badge
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend, quick-win

#2373 fix(refs: T34613): add orga status filter
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
Labels: type:bug, review:frontend, quick-win

#2388 bug (refs T34593): Remove margin and adjust positioning right
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#2380 bug (refs T34273): Add prop selection controls to filter modal
  client/js/components/statement/assessmentTable/FilterModalSelectItem.vue
Labels: type:bug, review:frontend

#2390 bug (refs T34613): Fix filter orga status
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
Labels: type:bug, review:frontend

#2366 fix(refs: T35563) add register button to public detail view
  client/js/InitVue.js
  client/js/bundles/procedure/publicIndexMapAndList.js
Labels: type:bug, review:frontend, quick-win

#2393 feat (refs T35632): duplicate csrf token usage leads to error
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig
Labels: review:backend
