Repository demos-europe/demosplan-core, pull requests merged in 2023-01, with the labels that each got.

#531 add portal-vue dependency to dependabot.yml
  .github/dependabot.yml
Labels: review:frontend, devops, quick-win

#542 feat: use php 8.1 for reviewdog
  .github/workflows/reviewdog.yml
Labels: devops

#529 make addons activateable
  composer.lock
  demosplan/DemosPlanCoreBundle/Logic/FilterUiDataProvider.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: review:backend, type:enhancement, type:story

#544 ci: Disallow updates to Symfony 6
  .github/dependabot.yml
Labels: devops, review:backend

#500 feat: be more cautious about the existence of files in request
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
Labels: review:backend

#449 feat T29403 refactor keycloak authenticator
  demosplan/DemosPlanCoreBundle/Controller/Help/DemosPlanHelpController.php
  demosplan/DemosPlanCoreBundle/Controller/News/DemosPlanNewsController.php
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserLogin.php
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
  demosplan/DemosPlanCoreBundle/Traits/DI/ElasticsearchQueryTrait.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/WebpackBundleExtension.php
  demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakResponseValueObject.php
  demosplan/DemosPlanProcedureBundle/Logic/ExportService.php
  demosplan/DemosPlanProcedureBundle/Repository/ProcedureElasticsearchRepository.php
  demosplan/DemosPlanStatementBundle/Logic/ElasticSearchService.php
  demosplan/DemosPlanStatementBundle/Logic/StatementHandler.php
  demosplan/DemosPlanStatementBundle/Repository/FragmentElasticsearchRepository.php
  tests/backend/core/Core/Functional/ProcedureExtensionTest.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
  tests/backend/core/ExternalFileSaver/Functional/ExternalFileSaverTest.php
Labels: review:backend, type:enhancement

#543 fix(refs T30796): Prevent newly added e-Mails in Email-List to get overwritten
  client/js/components/procedure/admin/NewBlueprintForm.vue
  client/js/components/procedure/basicSettings/DpEmailList.vue
Labels: type:bug, review:frontend

#545 Update vendor licenses
  demosplan/DemosPlanCoreBundle/Resources/static/js_licenses.json
  demosplan/DemosPlanCoreBundle/Resources/static/php_licenses.json
  licenses/js_licenses.txt
  licenses/php_licenses.txt
  licenses/system.txt
Labels: review:frontend, devops, review:backend

#557 Temporarily use GitHub version of demosplan-ui v0.0.6
  client/setup/webpack/moduleRules.js
  package.json
  yarn.lock
Labels: type:bug, review:frontend

#478 refactor(refs T29004): pass label props as object
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImport.vue
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupCitizenOrInstitution.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupCountyReference.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaSnailMailOrEmail.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
  client/js/components/statement/voter/StatementVoter.vue
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/single_document_admin_edit.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/single_document_admin_new.html.twig
Labels: review:frontend, lifecycle:do-not-merge

#573 build: Disable virus scan in dev environment
  demosplan/DemosPlanCoreBundle/Resources/config/config_dev_container.yml
Labels: review:backend

#494 feat: fixes some Addon autoloading issues
  composer.lock
  demosplan/DemosPlanCoreBundle/Addon/AddonAutoloading.php
  demosplan/DemosPlanCoreBundle/Addon/AddonRegistry.php
  demosplan/DemosPlanCoreBundle/Addon/Composer/PackageInformation.php
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
  demosplan/DemosPlanCoreBundle/Application/FrontController.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
  demosplan/DemosPlanCoreBundle/Logic/FilterUiDataProvider.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
Labels: help wanted, review:backend, support:backend

#534 feat: ensure that project rollup migrations are performed
  demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php
Labels: review:backend

#547 feat: update test configuration to Elasticsearch 7 syntax
  demosplan/DemosPlanCoreBundle/Resources/config/packages/test/fos_elastica.yaml
Labels: devops, review:backend

#574 bug(refs T30833): Add translation for key
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, quick-win

#575 bug(refs T29194): Change translation key
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/unregistered_publicagency_list.html.twig
Labels: type:bug, review:frontend, quick-win

#576 Use demosplan-ui 0.0.7
  package.json
  yarn.lock
Labels: review:frontend

#579 Do not purge demosplan-utils generated css selectors
  client/setup/config.js
Labels: type:bug, review:frontend, quick-win

#556 fix(refs T30824): catches LockedByAssignmentException
  demosplan/DemosPlanCoreBundle/Controller/Segment/DraftsInfoController.php
Labels: type:bug, review:backend, quick-win

#457 fix: ExportFieldsConfiguration needs to be set on new procedures
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
Labels: review:backend, quick-win

#587 feat: halts jsrouting on 2.8.x
  .github/dependabot.yml
Labels: devops, review:backend, dependencies:composer, quick-win

#594 F_(ref:30834) fix slicer caching
  demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Services/HTMLFragmentSlicer.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/HeightLimitExtension.php
  templates/bundles/DemosPlanStatementBundle/DemosPlanAssessment/view_statement.html.twig
  tests/backend/core/Core/Unit/Utilities/Twig/HeightLimitExtensionTest.php
Labels: type:bug, review:backend

#596 chore (refs T22614): Move Plugins, VueConfig & VueEvents to client/js.
  client/js/VueConfigBus.js
  client/js/VueConfigCore.js
  client/js/lib/core/ExtendedVueEvents.js
  client/js/plugins/DPVueBus.js
  client/js/plugins/DPVueCore.js
  client/setup/webpack/plugins.js
Labels: review:frontend, quick-win, type:enhancement

#595 Fix (ref: T30823) make context help available
  demosplan/DemosPlanCoreBundle/Controller/Help/DemosPlanHelpController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanHelp/help_admin_contextual_help_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanHelp/help_admin_contextual_help_list.html.twig
Labels: type:bug, review:backend

#598 fix broken ES configuration, caused wrong format, caused by merge
  demosplan/DemosPlanCoreBundle/Resources/config/packages/fos_elastica.yaml
Labels: review:backend, quick-win

#546 F 30480 custom default publication of documentcategories
  client/js/bundles/document/elementsAdminImport.js
  client/js/bundles/document/elementsAdminList.js
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/FileExtension.php
  demosplan/DemosPlanDocumentBundle/Logic/DocumentHandler.php
  demosplan/DemosPlanDocumentBundle/Logic/ElementHandler.php
  templates/bundles/DemosPlanCoreBundle/Extension/fileupload.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/elements_admin_import.html.twig
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/elements_admin_import_entry.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#606 chore (refs T30892): Add Hook/Selector.
  templates/bundles/DemosPlanDocumentBundle/DemosPlanDocument/includes/actionbox.html.twig
Labels: review:frontend, quick-win, type:enhancement

#578 feat (refs T29639): replace webatlas by basemap
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/01/Version20230104090531.php
  demosplan/DemosPlanMapBundle/Utilities/MapScreenshotter.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#617 fix(refs T30455, T30939): Handle unset bounds
  client/js/lib/procedure/CreateProcedure.js
Labels: type:bug, review:frontend

#616 F remove flysystem dependency
  composer.json
  composer.lock
  demosplan/DemosPlanCoreBundle/Filesystem/FilesystemFlysystemAdapter.php
  demosplan/DemosPlanCoreBundle/Filesystem/FilesystemInterface.php
  demosplan/DemosPlanCoreBundle/Filesystem/LocalFilesystem.php
  demosplan/DemosPlanCoreBundle/Resources/config/bundles.php
  demosplan/DemosPlanCoreBundle/Resources/config/packages/flysystem.yaml
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanCoreBundle/Resources/static/php_licenses.json
  licenses/php_licenses.txt
  symfony.lock
Labels: review:backend, type:enhancement

#615 Fix(refs:T30875): Contexthelp is showing not the expected key description
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_detail.html.twig
Labels: type:bug, review:frontend

#626 Fix: setVisible is undefined error
  client/js/components/map/publicdetail/Map.vue
Labels: review:frontend, quick-win

#592 fix(refs T30808): Check Permissions for Branding propperly
  client/js/components/user/CustomerSettings/CustomerSettings.vue
Labels: type:bug, review:frontend

#627 Fix osi authenticator
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OsiAuthenticator.php
Labels: review:backend

#607 feature (refs T19171): also update procedureSettings::EmailTitle when updating the procedureName
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanProcedureBundle/Logic/ServiceStorage.php
Labels: review:backend

#639 fix(refs T31010): Catch undefined maxExtend
  client/js/components/map/map/DpOlMap.vue
Labels: type:bug, review:frontend

#597 bug(refs T30859): Add permission request for choosing county
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
Labels: type:bug, review:frontend

#628 bug(refs T30938): add permission for paragraphs in statements
  client/js/components/document/ElementsAdminList.vue
  client/js/components/statement/publicStatementLists/DpPublicStatement.vue
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/includes/listentry_content.html.twig
  templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/new_public_participation_statement_confirm_entry.html.twig
Labels: type:bug, review:frontend, review:backend

#637 bug (refs T30876): missing map drawings export
  demosplan/DemosPlanCoreBundle/Logic/TextIntoImageInserter.php
  demosplan/DemosPlanMapBundle/Logic/GeoJsonToFeaturesConverter.php
  demosplan/DemosPlanMapBundle/Logic/PolygonIntoMapLayerMerger.php
  demosplan/DemosPlanMapBundle/Utilities/MapScreenshotter.php
  tests/backend/core/Map/Functional/MapScreenshotterTest.php
Labels: type:bug, review:backend

#629 fix (refs T30865): Count normal statements of procedure
  client/js/components/procedure/admin/AdministrationProceduresList.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/AdminProcedureResourceType.php
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_width.scss
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureService.php
  demosplan/DemosPlanStatementBundle/Repository/StatementRepository.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#657 chore (refs T22614): Add NotificationStoreAdapter to client/js/store.
  client/js/InitVue.js
  client/js/store/core/NotificationStoreAdapter.js
Labels: quick-win, support:frontend, type:enhancement

#646 fix (refs T30990): Escape any special chars for output
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
Labels: type:bug, review:backend, quick-win

#641 feature (refs T25542): include negativeReport on publicParagraph Route
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
Labels: review:backend, quick-win

#663 chore: Bump demosplan-ui
  yarn.lock
Labels: type:bug, review:frontend, dependencies:yarn, quick-win

#580 feature (refs T30671): cockpit related tasks - adjust planningDocumentCategories - address bugs
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
Labels: review:backend

#648 bug(refs T27479): Fix bulk edit for documents
  client/js/components/document/ElementsAdminList.vue
  client/js/components/document/ElementsList.vue
Labels: type:bug, review:frontend

#670 Add missing mutation to original statements view
  client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
Labels: type:bug, review:frontend, quick-win

#671 bug(refs T27479): update demosplan-ui to implement the fix
  yarn.lock
Labels: review:frontend, lifecycle:do-not-merge

#666 F t30968 move some lib files to client js
  client/js/InitVue.js
  client/js/bundles/faq/faqlist.js
  client/js/bundles/procedure/administrationEdit.js
  client/js/bundles/procedure/administrationListBoilerplate.js
  client/js/bundles/procedure/administrationMemberList.js
  client/js/bundles/statement/listFinalGroup.js
  client/js/bundles/statement/listFinalGroupCitizen.js
  client/js/bundles/statement/listTags.js
  client/js/bundles/statement/viewStatement.js
  client/js/bundles/user/editOrga.js
  client/js/bundles/user/listOrgas.js
  client/js/components/statement/DpPublicDetailNoMap.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/utils/changeUrlforPager.js
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  client/js/directives/saveAndReturn.js
  client/js/lib/core/libs/CharCount.js
  client/js/lib/core/libs/CheckableItem.js
  client/js/lib/core/libs/FloodControlField.js
  client/js/lib/core/libs/FormActions.js
  client/js/lib/core/libs/GlobalEventListener.js
  client/js/lib/core/libs/HighlightHashLink.js
  client/js/lib/core/libs/Pager.js
  client/js/lib/core/libs/ToggleAnything.js
  client/js/lib/core/libs/ToggleSideMenu.js
  client/js/lib/core/libs/Tooltips.js
  client/js/lib/core/libs/index.js
  client/js/lib/core/libs/touchFriendlyUserbox.js
  client/js/lib/core/loadLibs.js
  client/js/lib/news/newsAdmin.js
  client/js/lib/shared/AnimateById.js
  client/js/lib/shared/UrlPreview.js
  client/js/lib/statement/Tabs.js
  tests/frontend/unit/changeUrlForPager.test.js
Labels: review:frontend, type:enhancement

#673 chore (refs T22614): Move core lib Docu.
  client/js/components/map/publicdetail/lib/lib_documentation.md
  client/js/lib/core/lib_documentation.md
  client/js/lib/statement/lib_documentation.md
  client/js/store/core/core_documentation.md
  demosplan/DemosPlanCoreBundle/Resources/client/js/lib/lib_documentation.md
Labels: review:frontend, quick-win, type:enhancement

#640 Refactor addon registration and installation
  .gitignore
  addons/.gitignore
  demosplan/DemosPlanCoreBundle/Addon/AddonAutoloading.php
  demosplan/DemosPlanCoreBundle/Addon/AddonBundleGenerator.php
  demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php
  demosplan/DemosPlanCoreBundle/Addon/AddonManifestCollection.php
  demosplan/DemosPlanCoreBundle/Addon/AddonRegistry.php
  demosplan/DemosPlanCoreBundle/Addon/Composer/PackageInformation.php
  demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
  demosplan/DemosPlanCoreBundle/Addon/LoadAddonInfoCompilerPass.php
  demosplan/DemosPlanCoreBundle/Addon/ManifestConfiguration.php
  demosplan/DemosPlanCoreBundle/Addon/Registrator.php
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
  demosplan/DemosPlanCoreBundle/Command/CoreCommand.php
  demosplan/DemosPlanCoreBundle/Exception/AddonException.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  tests/backend/core-application/app/config/config_test.yml
Labels: review:backend, type:enhancement

#683 Improve addon contract wiring
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  composer.lock
  demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php
  demosplan/DemosPlanCoreBundle/Addon/AddonManifestCollection.php
  demosplan/DemosPlanCoreBundle/Addon/AddonRegistry.php
  demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
  demosplan/DemosPlanCoreBundle/Addon/LoadAddonInfoCompilerPass.php
  demosplan/DemosPlanCoreBundle/Addon/Registrator.php
  demosplan/DemosPlanCoreBundle/Addon/RpcAddonAssetsLoader.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  symfony.lock
Labels: review:backend

#658 fix: removes tagged_iterator argument for addonInfoProviders
  demosplan/DemosPlanCoreBundle/DependencyInjection/ServiceTagAutoconfigurator.php
Labels: review:backend, type:enhancement

#672 Feat(T30784): add street address to the submitter list
  client/js/components/procedure/DpSubmitterList.vue
Labels: review:frontend

#694 F t30977 edit permission components in demosplan UI
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/Fragment.vue
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
  templates/bundles/DemosPlanStatementBundle/DemosPlanStatement/includes/fragment_statement_form.html.twig
Labels: review:frontend, type:enhancement

#717 fix: Repair addons.yaml format
  demosplan/DemosPlanCoreBundle/Addon/Registrator.php
Labels: type:bug, review:backend

#720 feature (refs T64495): fix order of columns for submitter exports.
  demosplan/DemosPlanProcedureBundle/Logic/SubmitterExporter.php
Labels: type:bug, review:backend, quick-win

#722 feature (refs T31157): added deletion of statements to procedure report export
  demosplan/DemosPlanReportBundle/Logic/ExportReportService.php
Labels: review:backend, quick-win

#695 feature (refs T28038) bulk edit workflow place ewm
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcBulkEditor/RpcSegmentsBulkEditor.php
  demosplan/DemosPlanCoreBundle/Resources/config/json-schemas/segment/rpc-segment-bulk-edit-schema.json
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story
