Repository demos-europe/demosplan-core, pull requests merged in 2023-06, with the labels that each got.

#1401 refactor: rename MultistepNav
  client/js/components/statement/publicStatementModal/StatementModal.vue
Labels: review:frontend, lifecycle:do-not-merge

#1449 feat (refs T32934): Improve performance on Assessment Table by adding database index
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/06/Version20230601095828.php
Labels: review:backend

#1416 feat (refs T32954): Do not save user object in session
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/DplanAuthenticator.php
  demosplan/DemosPlanUserBundle/Logic/UserMapperDataportGatewayHH.php
Labels: review:backend

#1468 fix: also define color for hover state
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_link.scss
Labels: review:frontend

#1476 feature (refs T33075): add zero to datasheetversion variable
  demosplan/DemosPlanCoreBundle/Event/Procedure/GetDatasheetVersionEvent.php
Labels: review:backend

#1474 Fix Language for PhpWord generated Docx exports
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Export/PhpWordConfigurator.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
Labels: type:bug, review:backend

#1330 chore: update deprecated RouteCollectionBuilder
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
Labels: review:backend, quick-win

#235 Re-add frontend tests
  babel.config.js
  client/js/VueConfigLocal.js
  client/setup/jest/setup.js
  jest.config.js
  tests/frontend/unit/DpAdminLayerList.spec.js
  tests/frontend/unit/DpAutofillSubmitterData.spec.js
  tests/frontend/unit/DpBulkEdit.spec.js
  tests/frontend/unit/DpClaim.spec.js
  tests/frontend/unit/DpEditFieldMultiSelect.spec.js
  tests/frontend/unit/DpLayerLegend.spec.js
  tests/frontend/unit/DpProcedureCoordinateInput.spec.js
  tests/frontend/unit/DpPublicLayerList.spec.js
  tests/frontend/unit/DpPublicLayerListCategory.spec.js
  tests/frontend/unit/DpPublicStatement.spec.js
  tests/frontend/unit/FilterModalSelectItem.spec.js
  tests/frontend/unit/SearchModal.spec.js
  tests/frontend/unit/Status.spec.js
  tests/frontend/unit/__mocks__/DpAutofillSubmitterData.json
  tests/frontend/unit/__mocks__/Filter.mock.js
  tests/frontend/unit/__mocks__/MapLayer.mock.js
  tests/frontend/unit/__mocks__/dplan_api_map_options_admin.json
  tests/frontend/unit/__mocks__/layer_json.mock.js
  tests/frontend/unit/__mocks__/wordContentSnippets.mock.js
  tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap
  tests/frontend/unit/__snapshots__/DpPublicLayerListCategory.spec.js.snap
  tests/frontend/unit/__snapshots__/SearchModal.spec.js.snap
  tests/frontend/unit/store/Filter.spec.js
  tests/frontend/unit/store/Layers.spec.js
  tests/frontend/unit/store/Notify.spec.js
  tests/frontend/unit/store/Statement.spec.js
  tests/frontend/unit/store/storeHelpers/SplitStatementStore/HTMLIdxToProsemirrorIdx.spec.js
  tests/frontend/unit/utils.spec.js
Labels: review:frontend, type:enhancement

#1470 Use replacing placeholder in exports
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Map/MapService.php
  demosplan/DemosPlanCoreBundle/Utilities/Map/MapScreenshotter.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_original_entry.tex.twig
  translations/messages+intl-icu.de.yml
Labels: review:backend

#1485 fix(refs T33015): implement date validation check
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
Labels: type:bug, review:frontend

#1495 feat (refs T33162): fix year replacement of copyright
  client/js/components/map/map/DpOlMapLayer.vue
  client/js/components/map/publicdetail/Map.vue
  demosplan/DemosPlanCoreBundle/Logic/Map/MapService.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation.html.twig
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, review:backend, quick-win

#1378 F t32212 add addon interfaces add necessary interfaces
  composer.lock
  demosplan/DemosPlanCoreBundle/Entity/Document/Paragraph.php
  demosplan/DemosPlanCoreBundle/Entity/Document/ParagraphVersion.php
  demosplan/DemosPlanCoreBundle/Entity/Document/SingleDocument.php
  demosplan/DemosPlanCoreBundle/Entity/Document/SingleDocumentVersion.php
  demosplan/DemosPlanCoreBundle/Entity/ExportFieldsConfiguration.php
  demosplan/DemosPlanCoreBundle/Entity/FileContainer.php
  demosplan/DemosPlanCoreBundle/Entity/Map/GisLayer.php
  demosplan/DemosPlanCoreBundle/Entity/OriginalStatementAnonymization.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Boilerplate.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/BoilerplateCategory.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/BoilerplateGroup.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/NotificationReceiver.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureBehaviorDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureCategory.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePerson.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureType.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureUiDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/StatementFieldDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/StatementFormDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/County.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/DraftStatement.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/DraftStatementFile.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/GdprConsent.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Municipality.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/PriorityArea.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Segment.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/SegmentComment.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementAttribute.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementFragment.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementFragmentVersion.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementLike.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementMeta.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementVersionField.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementVote.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Tag.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/TagTopic.php
  demosplan/DemosPlanCoreBundle/Entity/StatementAttachment.php
  demosplan/DemosPlanCoreBundle/Entity/Survey/Survey.php
  demosplan/DemosPlanCoreBundle/Entity/Survey/SurveyVote.php
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Entity/User/CustomerCounty.php
  demosplan/DemosPlanCoreBundle/Entity/User/FunctionalUser.php
  demosplan/DemosPlanCoreBundle/Entity/User/OrgaStatusInCustomer.php
  demosplan/DemosPlanCoreBundle/Entity/User/OrgaType.php
  demosplan/DemosPlanCoreBundle/Entity/User/Role.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/Entity/User/UserRoleInCustomer.php
  demosplan/DemosPlanCoreBundle/Entity/Video.php
  demosplan/DemosPlanCoreBundle/Entity/Workflow/Place.php
Labels: review:backend

#1480 chore: add missing env var to allow cli debugging
  docker/php8.1-cli-development/zshenv
Labels: devops

#1496 chore: remove vendor that is not needed
  composer.json
Labels: devops, review:backend

#1482 bug(refs T33031): Hide upload files when editable is false
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
Labels: type:bug, review:frontend

#1503 feature (refs T32342): delete rejected flag&Reason when submitting draftStatement(s)
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
Labels: review:backend

#1321 fix (refs T32108): correctly calculate status percentages
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/ElasticsearchFilterArrayTransformer.php
  demosplan/DemosPlanCoreBundle/ValueObject/MovedStatementData.php
  demosplan/DemosPlanCoreBundle/ValueObject/PriorityPair.php
  demosplan/DemosPlanCoreBundle/ValueObject/StatementMovement.php
  demosplan/DemosPlanCoreBundle/ValueObject/StatementMovementCollection.php
  demosplan/DemosPlanStatementBundle/Logic/ElasticSearchService.php
  demosplan/DemosPlanStatementBundle/Logic/MultiTermsAggregation.php
  demosplan/DemosPlanStatementBundle/Logic/StatementService.php
Labels: type:bug, review:backend

#1507 F remove fs margin
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss
Labels: type:bug, review:frontend

#1513 fix(refs T31372): Add Missing Confirmmassge when creating a manual STN
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php
Labels: type:bug, review:backend

#1515 bug(refs T33031): Hide upload files when editable is false (#1482)
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
Labels: review:frontend, quick-win

#1502 fix (refs T33172): Replace '{currentYear}' with an actual value. (PDF export)
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/statement_macros.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
Labels: review:frontend

#1518 fix (refs T33109): Fix adding of similar statement submitters
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
Labels: review:backend

#1465 Fix tests and reanimate jenkins
  Jenkinsfile
  composer.json
  config/packages/test/fos_elastica.yaml
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/TransformMessageBagService.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserMapper.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/LoginFormAuthenticator.php
  phpunit.xml
  tests/backend/base/FunctionalTestCase.php
  tests/backend/core/AssessmentTable/AssessmentHandlerTest.php
  tests/backend/core/Core/Functional/CommandTesterTrait.php
  tests/backend/core/Core/Functional/ContainerInitCommandTest.php
  tests/backend/core/Core/Functional/FilterUiDataProviderTest.php
  tests/backend/core/Core/Functional/GenerateCustomerCommandTest.php
  tests/backend/core/Core/Functional/HoneypotTest.php
  tests/backend/core/Core/Functional/JsonApiClientTest.php
  tests/backend/core/Core/Functional/ProcedureExtensionTest.php
  tests/backend/core/Core/Functional/SamlUserFactoryTest.php
  tests/backend/core/Core/Functional/UserLoginSubscriberTest.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/RouterTest.php
  tests/backend/core/Document/Unit/DocumentBundleImporterTest.php
  tests/backend/core/Map/Functional/MapCoordinateDataFetcherTest.php
  tests/backend/core/Map/Unit/MapProjectionConverterTest.php
  tests/backend/core/Statement/Functional/SimiliarStatementSubmitterTest.php
  tests/backend/core/User/Functional/MasterToebServiceTest.php
Labels: review:backend

#1524 Bump demosplan-ui plus some cherrypicks
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_segmentlist.scss
  yarn.lock
Labels: type:bug, review:frontend

#1505 feat(refs T33153): Revert custom label for multiselect
  client/js/components/faq/DpFaqItem.vue
  client/js/components/statement/assessmentTable/AssignEntityModal.vue
  client/js/components/statement/assessmentTable/ConsolidateModal.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/statement/SelectStatementCluster.vue
  client/js/components/user/DpUserList/DpUserFormFields.vue
Labels: type:bug, review:frontend

#1525 chore: Upgrade demosplan-ui
  yarn.lock
Labels: review:frontend

#1528 fix/refs T33256): Break segments overflow
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#1530 fix (refs T33142): uses parent statement submit date
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
Labels: review:backend

#1529 fix(refs T31372): Add confirm message to confirm mstn
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php
Labels: type:bug, review:backend

#1532 chore(refs T32012): Bump PortalVue to 3
  package.json
  yarn.lock
Labels: review:frontend, type:enhancement

#1534 chore: Bump demosplan-ui to 0.1.4
  yarn.lock
Labels: review:frontend, type:enhancement

#1477 Use new interfaces
  demosplan/DemosPlanCoreBundle/Logic/Map/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureTypeService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
Labels: review:backend

#1542 chore: fix methods after interface BC breaks
  composer.lock
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Permissions/ProjectPermissions.php
Labels: review:backend

#1540 chore: remove unused twig block
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
Labels: review:frontend, quick-win

#1551 feat: remove redundant components from core
  client/js/components/procedure/AdministrationImport/EmailImport/DpBadge.vue
  client/js/components/procedure/AdministrationImport/EmailImport/EmailImport.vue
  client/js/components/procedure/AdministrationImport/EmailImport/EmailImportDate.vue
  client/js/components/procedure/AdministrationImport/EmailImport/EmailImportHint.vue
  client/js/components/procedure/AdministrationImport/EmailImport/EmailImportStatusBadge.vue
  client/js/components/procedure/AdministrationImport/StatementPdfImport/StatementPdfImport.vue
  client/js/components/procedure/AdministrationImport/StatementPdfImport/StatementPdfImportList.vue
Labels: review:frontend

#1521 Change config to use tailwind
  client/fe/config/config.js
  client/fe/webpack/moduleRules.js
  config.webpack.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings-color.dplan.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/core_style.scss
  package.json
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig
  yarn.lock
Labels: review:frontend

#1409 refactor(refs T30969): replace CopyPasteButton
  client/js/components/statement/statement/DpCreateStatementFragment.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/fragment_statement.html.twig
Labels: review:frontend, lifecycle:do-not-merge, type:enhancement

#1546 refactor(refs T30969): add ChangeStateAtDate
  client/js/bundles/news/newsAdminEdit.js
  client/js/bundles/news/newsAdminNew.js
  client/js/components/news/ChangeStateAtDate.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig
Labels: review:frontend, type:enhancement

#1552 fix adjust demosplan addon version:
  composer.json
  composer.lock
Labels: review:backend, quick-win

#1553 chore: use distinct addon contract version
  composer.json
  composer.lock
Labels: review:backend

#1554 chore: fix missing abstract method by updating addon contracts
  composer.lock
Labels: review:backend

#1558 chore: update dependencies, update composer.lock with php 8.2
  composer.json
  composer.lock
Labels: review:backend

#1561 chore: downgrade incompatible library
  composer.json
  composer.lock
Labels: review:backend

#1562 fix(refs T33234): Remove incorrect late permission evaluation
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
Labels: review:frontend, review:backend

#1429 chore (refs T27388): upgrade request header deprecation
  demosplan/DemosPlanCoreBundle/EventSubscriber/TrustedProxiesSubscriber.php
Labels: review:backend, quick-win

#1564 feat(refs T33234): Add rudimentary support for exposing addon permissions
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Permissions/ResolvablePermissionCollection.php
Labels: review:backend

#1565 fix: Allow complete permission evaluation without valid user
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Permissions/PermissionResolver.php
Labels: review:backend

#1567 fix remove unused permission
  config/permissions.yml
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: review:backend, quick-win

#1575 bug(refs T33391): Fix z-index for tooltip
  client/js/components/map/map/DpOlMapEditFeature.vue
Labels: type:bug, review:frontend

#1519 chore: delete unused pipeline definitions
  azure-pipelines-1.yml
  azure-pipelines.yml
Labels: devops, quick-win

#1588 F t33374 add e2e hooks
  client/js/components/user/citizenRegisterForm/CitizenRegisterForm.vue
  client/js/components/user/orgaRegisterForm/OrgaRegisterForm.vue
Labels: review:frontend, quick-win, type:enhancement

#1586 chore (refs T33426): avoid eternal login loop
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend

#1589 Bump demosplan-ui to v0.1.6
  yarn.lock
Labels: type:bug, review:frontend

#1590 chore (refs T32856): add missing hook/selector.
  client/js/components/statement/publicStatementModal/StatementModal.vue
Labels: review:frontend, quick-win, type:enhancement

#1594 chore (refs T33309): add missing Footer hook/selector.
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_footer.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1580 chore (refs T33424): avoid unnecessary user set
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
Labels: type:bug, review:backend, quick-win

#1587 fix (refs T33375): Login as citizen via keycloak
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
Labels: type:bug, review:backend

#1579 chore: only try to add constraint when it does not exist
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/06/Version20230601095828.php
Labels: type:bug, review:backend

#1596 chore (refs T33309): add missing header hook/selector.
  client/js/components/user/RegisterFlyout.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header_nav_item_sign_language.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header_nav_item_simple_language.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header_userbox.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_oeb_header_userbox.html.twig
Labels: review:frontend, quick-win, type:enhancement

#1595 B t33440 fix header layout
  client/js/InitVue.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_color.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header_nav_item_simple_language.html.twig
Labels: review:frontend

#1576 fix remove unused permission
  config/permissions.yml
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: review:backend, quick-win

#1607 Fix:(T33457): permanently expanded basic settings
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend

#1487 Ref(T32651): Vue migration: adjust AdministrationPlaces component to new version of DpDataTable
  client/js/components/procedure/admin/AdministrationPlaces.vue
Labels: review:frontend

#1581 fix(T33011): access getCapabilities directly in the FE utilizing externalAPI method
  client/js/components/map/admin/LayerSettings.vue
  client/js/components/map/publicdetail/Map.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#1608 chore: Backmerge of release_ewm_3.0
  client/js/components/faq/DpFaqItem.vue
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/statement/assessmentTable/AssignEntityModal.vue
  client/js/components/statement/assessmentTable/ConsolidateModal.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/statement/SelectStatementCluster.vue
  client/js/components/user/DpUserList/DpUserFormFields.vue
  composer.lock
  demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Permissions/PermissionResolver.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Permissions/ResolvablePermissionCollection.php
  translations/messages+intl-icu.de.yml
  yarn.lock
Labels: review:frontend, review:backend

#1612 fix(refs T33500): bump demosplan-ui to latest version
  yarn.lock
Labels: review:frontend

#1614 fix(refs T33507): raise specificity
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_toggle.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
Labels: review:frontend

#1610 Use higher specificity for showing elements within wizard
  client/js/lib/procedure/DPWizard.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_wizard.scss
Labels: review:frontend

#1615 f move the parameter 'datasheetFilePath' from core to Datasheets addon
  demosplan/DemosPlanCoreBundle/Event/Procedure/GetDatasheetFilePathAbsoluteEvent.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementGeoService.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
Labels: review:backend

#1617 chore: updates lcobucci dependency
  composer.lock
Labels: review:backend, dependencies:composer, quick-win

#1621 Fix(T33521): add notification for invalid service type
  client/js/components/map/admin/LayerSettings.vue
  client/js/components/map/publicdetail/controls/CustomLayer.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#1623 fix adjust demosplan addon version
  composer.json
  composer.lock
Labels: support:backend

#1563 feature (refs T33011): remove getCapabilities related code -BE
  config/json-schema/rpc-map-get-capbilities-schema.json
  demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
  demosplan/DemosPlanCoreBundle/Logic/Maps/GetCapabilitesRpcMethodSolver.php
  demosplan/DemosPlanCoreBundle/Logic/Maps/MapCapabilitiesLoader.php
  demosplan/DemosPlanCoreBundle/ValueObject/Map/MapCapabilities.php
  tests/backend/core/Map/Functional/MapCapabilitiesLoaderTest.php
Labels: review:backend

#1622 feature (refs T33011): adjusted faq move interface into addon so they…
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Entity/Faq.php
  demosplan/DemosPlanCoreBundle/Entity/FaqCategory.php
  demosplan/DemosPlanCoreBundle/Entity/PlatformFaq.php
  demosplan/DemosPlanCoreBundle/Entity/PlatformFaqCategory.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqCategoryInterface.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqInterface.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqService.php
Labels: review:backend, lifecycle:do-not-merge, type:story

#1627 Fix(T33542): missing user menu
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/error.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/public_newsdetail.html.twig
Labels: review:frontend

#1624 feat T32776 add and adjust procedure related events
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureDeletedEvent.php
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureUpdatedEvent.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
Labels: review:backend, lifecycle:do-not-merge, type:story

#1629 fix adjust parameter type
  demosplan/DemosPlanCoreBundle/Entity/PlatformFaq.php
Labels: review:backend, quick-win

#1430 core (refs T27388): update simple flex recipes
  .env
  .gitignore
  config/packages/debug.yaml
  config/packages/dev/debug.yaml
  config/packages/dev/jms_serializer.yaml
  config/packages/dev/web_profiler.yaml
  config/packages/jms_serializer.yaml
  config/packages/lexik_jwt_authentication.yaml
  config/packages/prod/jms_serializer.yaml
  config/packages/prod/routing.yaml
  config/packages/routing.yaml
  config/packages/security.yaml
  config/packages/test/twig.yaml
  config/packages/test/validator.yaml
  config/packages/test/web_profiler.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  config/packages/validator.yaml
  config/packages/web_profiler.yaml
  config/routes/dev/web_profiler.yaml
  config/routes/web_profiler.yaml
  demosplan/DemosPlanCoreBundle/Application/FrontController.php
  phpunit.xml
  symfony.lock
Labels: review:backend

#1431 chore (refs T27388): update sentry flex recipe
  config/packages/monolog.yaml
  config/packages/sentry.yaml
  config/services.yml
  phpunit.xml
  symfony.lock
Labels: review:backend

#1432 chore (refs T27388): update doctrine related flex recipes
  .env
  config/packages/doctrine.yaml
  config/packages/doctrine_migrations.yaml
  config/packages/prod/doctrine.yaml
  config/packages/stof_doctrine_extensions.yaml
  config/packages/test/doctrine.yaml
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadCategoryData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadMailTemplateData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadMigrationVersionData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureTypeData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadRolesData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadUserData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadAddressBookEntryData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadBoilerplateData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadCategoryData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadContextualHelpData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadCustomerData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadDraftStatementData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadElementsData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadEntityContentChangeData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadFaqData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadFileData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadForumData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadGlobalContentData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadLocationData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadMailData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadManualListSortData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadMapData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadMasterToebData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadNewsData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadOpenGeoDbData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureProposalData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureSubscriptionData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadReportData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSegmentData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSettingData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadStatementAttributeData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadStatementData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadStatementVoteData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSurveyData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadSurveyVoteData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadTagData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadUserData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadWorkflowPlaceData.php
  symfony.lock
Labels: review:backend

#1628 fix (refs: T33353): adds fix to core
  client/js/components/core/DpEditor/libs/handleWordPaste.js
Labels: type:bug, review:frontend, quick-win

#1290 feat: allow docx importer implementation via external service
  config/parameters_default.yml
  config/services.yml
  demosplan/DemosPlanCoreBundle/Tools/DocxImporterHttp.php
  demosplan/DemosPlanCoreBundle/Tools/DocxImporterInterface.php
  demosplan/DemosPlanCoreBundle/Tools/DocxImporterRabbitmq.php
  demosplan/DemosPlanCoreBundle/Tools/ServiceImporter.php
Labels: review:backend
