Repository demos-europe/demosplan-core, pull requests merged in 2023-03, with the labels that each got.

#905 bug(refs T30632): Create baselayers always with layersource
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#906 Fix(refs:T31512): Replace consideration with considerationadvice
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#909 Add styles to fix layout jump
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_card.scss
Labels: review:frontend

#875 feat(refs T31492): refactor editor
  client/js/bundles/procedure/administrationEditBoilerplate.js
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/statement/DpBoilerPlate.vue
  client/js/components/statement/DpBoilerPlateModal.vue
  client/js/components/statement/assessmentTable/DetailView/DetailViewFinalEmailBody.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/assessmentTable/TiptapEditText.vue
  client/js/components/statement/segments/DpInsertableRecommendation.vue
  client/js/components/statement/segments/DpRecommendationModal.vue
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig
  templates/bundles/DemosPlanCoreBundle/UI/form/editor.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_edit_boilerplate.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_member_email.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_send_email.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/customer_settings_update_mail.html.twig
  yarn.lock
Labels: review:frontend, type:enhancement

#910 bug (refs T31261): fix import of docx paragraph-elements.
  demosplan/DemosPlanDocumentBundle/Repository/ParagraphRepository.php
  demosplan/DemosPlanDocumentBundle/Tools/ServiceImporter.php
Labels: type:bug, review:backend

#908 bug (refs T31604): fix occurrences of "Web-Atlas" in blueprints by replacing them with "basemap"
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/03/Version20230301094921.php
Labels: type:bug, review:backend

#928 refactor (refs T31722): add missing exception causes
  demosplan/DemosPlanCoreBundle/Twig/Extension/ProcedureExtension.php
  demosplan/DemosPlanProcedureBundle/Repository/ProcedureProposalRepository.php
  demosplan/DemosPlanStatementBundle/Repository/StatementFragmentRepository.php
Labels: type:bug, review:backend

#929 Fix(refs:T31701): platform settings are not loading
  client/js/components/user/CustomerSettings/CustomerSettings.vue
Labels: type:bug, review:frontend

#933 fix (refs T31730): cc email addresses may be a list of emails
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
Labels: review:backend

#864 F t31336 addon related adjustements
  composer.lock
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
  demosplan/DemosPlanCoreBundle/Entity/Document/SingleDocument.php
  demosplan/DemosPlanCoreBundle/Entity/Help/ContextualHelp.php
  demosplan/DemosPlanCoreBundle/Entity/Map/GisLayer.php
  demosplan/DemosPlanCoreBundle/Entity/Map/GisLayerCategory.php
  demosplan/DemosPlanCoreBundle/Entity/StatementAttachment.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/Event/Statement/StatementCreatedEvent.php
  demosplan/DemosPlanCoreBundle/Event/Statement/StatementUpdatedEvent.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/StatementCreationConsultationSubscriber.php
  demosplan/DemosPlanCoreBundle/Exception/ContentMandatoryFieldsException.php
  demosplan/DemosPlanCoreBundle/Exception/ResourceNotFoundException.php
  demosplan/DemosPlanCoreBundle/Logic/Factory/GisLayerFactory.php
  demosplan/DemosPlanCoreBundle/Logic/TransactionService.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryResourceType.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanCoreBundle/Resources/config/services_repositories.yml
  demosplan/DemosPlanDocumentBundle/Logic/DocumentHandler.php
  demosplan/DemosPlanDocumentBundle/Logic/ElementsService.php
  demosplan/DemosPlanDocumentBundle/Logic/SingleDocumentService.php
  demosplan/DemosPlanDocumentBundle/Tools/ServiceImporter.php
  demosplan/DemosPlanMapBundle/Repository/GisLayerCategoryRepository.php
  demosplan/DemosPlanMapBundle/Repository/MapRepository.php
  demosplan/DemosPlanProcedureBundle/Exception/PreNewProcedureCreatedEventConcernException.php
  demosplan/DemosPlanProcedureBundle/Form/AbstractProcedureFormType.php
  demosplan/DemosPlanProcedureBundle/Logic/PrepareReportFromProcedureService.php
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureService.php
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureTypeService.php
  demosplan/DemosPlanProcedureBundle/Logic/ServiceStorage.php
  demosplan/DemosPlanProcedureBundle/Repository/ProcedureRepository.php
  demosplan/DemosPlanStatementBundle/Logic/StatementService.php
  demosplan/DemosPlanUserBundle/Exception/OrgaNotFoundException.php
  demosplan/DemosPlanUserBundle/Exception/UserNotFoundException.php
  tests/backend/core/Document/Functional/ElementsServiceTest.php
Labels: review:backend

#925 feat: perform migrations and elasticsearch populate
  demosplan/DemosPlanCoreBundle/Command/ContainerInitCommand.php
Labels: review:backend

#969 bug(refs T31795): add slots for boilerplate
  client/js/bundles/news/newsAdminEdit.js
  client/js/bundles/news/newsAdminNew.js
  client/js/bundles/procedure/administrationMemberEmail.js
  client/js/bundles/procedure/administrationSendEmail.js
  client/js/bundles/procedure/administrationUnregisteredPublicagencyEmail.js
  client/js/bundles/statement/assessmentStatement.js
  client/js/bundles/user/customersettingsmail.js
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/statement/DpBoilerPlateModal.vue
  client/js/components/statement/assessmentTable/DetailView/DetailViewFinalEmailBody.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/assessmentTable/TiptapEditText.vue
  templates/bundles/DemosPlanAssessmentTableBundle/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_member_email.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_send_email.html.twig
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/customer_settings_update_mail.html.twig
Labels: type:bug, review:frontend, urgent

#956 chore: update php vendors that are not covered by dependabot
  composer.lock
Labels: review:backend

#724 feat: Avoid call to elasticsearch to fix tests
  demosplan/DemosPlanStatementBundle/Logic/StatementFragmentService.php
Labels: review:backend

#974 feat: create OpenAPI Data only on development builds
  demosplan/DemosPlanCoreBundle/Command/FrontendIntegratorCommand.php
Labels: devops, review:backend, quick-win

#975 chore (refs T27388): fix simple and safe return type deprecations
  demosplan/DemosPlanAssessmentTableBundle/Logic/AssessmentTableViewMode.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
  demosplan/DemosPlanCoreBundle/Command/Data/DataProviderCommand.php
  demosplan/DemosPlanCoreBundle/Constraint/ClaimConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/ConsistentOriginalStatementConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/CorrectDateOrderConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/FormDefinitionConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/MatchingFieldValueInSegments.php
  demosplan/DemosPlanCoreBundle/Constraint/MatchingSubmitTypesConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/OriginalReferenceConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/PrePersistUniqueInternIdConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/ProcedureAllowedSegmentsConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/ProcedureInCoupleAlreadyUsedConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/ProcedureMasterTemplateConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/ProcedureTemplateConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/SimilarStatementSubmittersSameProcedureConstraint.php
  demosplan/DemosPlanCoreBundle/Constraint/UserWithMatchingDepartmentInOrgaConstraint.php
  demosplan/DemosPlanCoreBundle/DependencyInjection/Configuration/MenusTreeBuilder.php
  demosplan/DemosPlanCoreBundle/Doctrine/Generator/UuidV4Generator.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/NonAuthorizedAssignRemoveSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/Logger/ApiLogger.php
  demosplan/DemosPlanCoreBundle/Permissions/Permission.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
  demosplan/DemosPlanProcedureBundle/Constraint/ExclusiveProcedureOrProcedureTypeConstraint.php
  demosplan/DemosPlanProcedureBundle/Constraint/ProcedureTypeConstraint.php
  demosplan/DemosPlanStatementBundle/ValueObject/DraftStatementListFilters.php
Labels: review:backend

#970 feat: provide default values for database
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
Labels: devops, review:backend, quick-win

#848 fix required follows optional parameter deprecation draftstatementservice
  demosplan/DemosPlanStatementBundle/Logic/DraftStatementService.php
Labels: review:backend

#957 chore: define symfony packages explicitly
  composer.json
Labels: review:backend

#890 Minor Webpack Refactorings
  client/fe/README.md
  client/fe/config/config.js
  client/fe/config/projectConfig.js
  client/fe/index.js
  client/fe/webpack/bundleEntryPoints.js
  client/fe/webpack/moduleRules.js
  client/fe/webpack/optimization.js
  client/fe/webpack/plugins.js
  client/fe/webpack/resolveAliases.js
  client/fe/webpack/runWebpack.js
  client/fe/webpack/util.js
  client/setup/webpack/CssPrefixPlugin.js
  client/setup/webpack/log.js
  config.webpack.js
  fe
Labels: review:frontend, devops

#972 Bug(refs: T31791): fix loadtime not in form request
  client/js/components/statement/publicStatementModal/StatementModal.vue
Labels: review:frontend

#847 fix required follows optional parameter deprecation usermapper
  demosplan/DemosPlanUserBundle/Logic/UserMapperDataportGatewayHH.php
Labels: review:backend

#999 Feat(refs:T31666): Dont show globalnews title and section if no news exists
  templates/bundles/DemosPlanProcedureBundle/DemosPlanProcedure/public_index_globalnewslist.html.twig
Labels: review:frontend, type:story

#1002 feature (refs T30254): Make PercentageDistribution value object availabe in addons
  demosplan/DemosPlanCoreBundle/Logic/Factory/PercentageDistributionFactory.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanCoreBundle/ValueObject/PercentageDistribution.php
Labels: review:backend

#1014 F add parameters_test yaml
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_test.yml
Labels: review:backend

#988 fix (refs T31722): skip deleted files when copied from blueprint
  demosplan/DemosPlanCoreBundle/Entity/File.php
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureService.php
Labels: type:bug, review:backend

#1015 feat (refs T30254): update demosplan-addon
  composer.lock
Labels: review:backend

#1019 fix(refs:T31509): add space
  templates/bundles/DemosPlanCoreBundle/DemosPlanAdmin/statistics.html.twig
Labels: type:bug, review:frontend, quick-win

#1017 chore (refs T31795): fix component imports
  client/js/components/statement/DpBoilerPlate.vue
  client/js/components/statement/segments/DpInsertableRecommendation.vue
  client/js/components/statement/segments/DpRecommendationModal.vue
Labels: review:frontend, quick-win

#1024 F (ref:F_T31928): adjust use statement
  demosplan/DemosPlanCoreBundle/Event/CreateSimplifiedStatementEvent.php
Labels: type:bug, review:backend, quick-win

#1025 F (ref:F_T31927): handle values with int type
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
Labels: type:bug, review:backend, quick-win

#1026 feature (refs T31936): adjust path to ElasticSearchResult - TotalHits.
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiEsService.php
Labels: type:bug, review:backend, quick-win

#1029 fix: Adjust path to Jest config
  jest.config.js
Labels: type:bug, review:frontend

#1030 fix (refs T31622, T16953): fix user id in report entry
  demosplan/DemosPlanReportBundle/Logic/ProcedureReportEntryFactory.php
Labels: type:bug, review:backend, quick-win

#1034 chore(refs T29871): Remove unused CSS
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_chart.scss
Labels: review:frontend, quick-win, type:enhancement

#1046 feature (refs T31926): changed order of constructor calls
  demosplan/DemosPlanCoreBundle/Entity/User/AiApiUser.php
Labels: review:backend

#1020 Fix(refs:T31753): little spelling mistake correction
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, quick-win

#1048 Remove leftovers from moving utils to demosplan-ui
  jest.config.js
  yarn.lock
Labels: review:frontend

#1049 bug(refs: T31984): prevent unintentional deletion of editor text
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#1056 Bug(refs t31984) fix dpconfirm
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
Labels: review:frontend

#1032 fix: Update the addon's code on reinstall
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend, quick-win

#1062 feat (refs T31926): move ai api user to database
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/03/Version20230324132250.php
  demosplan/DemosPlanCoreBundle/Logic/JwtRouter.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/AiApiUserProvider.php
Labels: type:bug, review:backend

#1066 fix(refs T31929): Optimize addon loading
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
Labels: type:bug, review:frontend

#1068 Fix unclaiming of statement
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/DpClaim.vue
Labels: type:bug, review:frontend

#1070 Hide button row
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/edit_orga.html.twig
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/orga_data_entry.html.twig
Labels: type:bug, review:frontend

#1071 Show statement as text when not in edit mode
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
Labels: type:bug, review:frontend

#955 fix: avoid exception in uncalled listener
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
Labels: review:backend

#994 F t30835 adjusted keycloak data mapping
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
  demosplan/DemosPlanCoreBundle/ValueObject/KeycloakUserDataInterface.php
  demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakResponseValueObject.php
  demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakUserData.php
  tests/backend/base/FunctionalTestCase.php
Labels: review:backend, support:backend

#1079 fix(refs T31998): restore setActiveTabId
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
Labels: type:bug, review:frontend

#1081 feature (refs T31926): use new Response instance to prevent null value
  demosplan/DemosPlanCoreBundle/EventSubscriber/ParametersProviderSubscriber.php
Labels: review:backend

#1082 feature (refs T31926): change method of EventSubscriber from private to public.
  demosplan/DemosPlanCoreBundle/EventSubscriber/ParametersProviderSubscriber.php
Labels: review:backend, quick-win

#667 Feat ref 30254 related addon adjustements
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  client/js/components/procedure/basicSettings/DpAllowedSenderEmailList.vue
  client/js/components/procedure/basicSettings/DpEmailList.vue
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanSimplifiedStatementController.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/01/Version20230113141824.php
  demosplan/DemosPlanCoreBundle/Entity/EmailAddress.php
  demosplan/DemosPlanCoreBundle/Event/IsOriginalStatementAvailableEvent.php
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureDeletedEvent.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/HandleEmailAddressSubscriber.php
  demosplan/DemosPlanCoreBundle/Http/JsonApiClient.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/DplanResourceType.php
  demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OriginalStatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/UserResourceType.php
  demosplan/DemosPlanCoreBundle/Resources/config/services.yml
  demosplan/DemosPlanProcedureBundle/Logic/ProcedureService.php
  demosplan/DemosPlanUserBundle/Logic/UserService.php
Labels: review:backend, type:story

#1086 fix (refs T32007): avoid type error
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanDepartmentController.php
Labels: review:backend, quick-win

#1031 feature (refs T29882): alter path to json schemas
  demosplan/DemosPlanCoreBundle/Resources/config/parameters_default.yml
Labels: review:backend, quick-win

#1065 fix (refs T32003): disable permissions for institution tagging
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: type:bug, review:backend, quick-win

#1064 feature (refs T32008): add orgaName to ReportEntries
  client/js/components/report/DpReportGroup.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/ReportEntryResourceType.php
  demosplan/DemosPlanReportBundle/Logic/ReportMessageConverter.php
Labels: type:bug, review:backend

#1088 Remove pattern validation for city
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/admin/AuthorizedUsersList.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
Labels: type:bug, review:frontend

#1061 F T32013 submitters of the same statement are not saved
  demosplan/DemosPlanCoreBundle/ResourceTypes/SimilarStatementSubmitterResourceType.php
  demosplan/DemosPlanStatementBundle/Logic/StatementService.php
Labels: type:bug, review:backend

#1090 Update demosplan-ui to v0.0.18
  yarn.lock
Labels: type:bug, review:frontend

#1089 feature (refs T30254): update composer.lock
  composer.lock
Labels: review:backend, quick-win

#1093 fix administration import not loading addons
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
Labels: review:frontend

#1094 F_T31511 make statement splitting possible
  demosplan/DemosPlanCoreBundle/DependencyInjection/ServiceTagAutoconfigurator.php
  demosplan/DemosPlanCoreBundle/Logic/Rpc/RpcMethodSolverInterface.php
Labels: type:bug, review:backend

#1101 feature (refs T30254): update composer.lock
  composer.lock
Labels: review:backend, quick-win

#1083 Feat(refs:T31920): Change style header and footer
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_footer.html.twig
Labels: review:frontend, type:story

#1104 F adjust return type
  demosplan/DemosPlanCoreBundle/ValueObject/ValueObject.php
Labels: review:backend

#1103 feature (refs T30254): Adjust api call in DpImageAnnotator.vue
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
Labels: review:frontend

#1111 fix(refs T32058): Make check for maxExtent do what's suppose to do
  client/js/components/map/map/DpOlMap.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/procedure/listSubscriptions/ListSubscriptions.vue
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
  package.json
Labels: review:frontend, lifecycle:do-not-merge

#954 chore: do not report mails as sent in case of an error
  demosplan/DemosPlanCoreBundle/Logic/MailService.php
Labels: review:backend

#1113 feat: provide link to external identity provider
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
  templates/bundles/DemosPlanUserBundle/DemosPlanUser/alternative_login.html.twig
Labels: review:frontend, review:backend

#1091 Feat(refs:T31913): Hide press announcement if no press news existing
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/globalnewslist_list_index.html.twig
Labels: review:frontend, type:story

#1114 feature (refs T30254): change SegmentRepository usage of SegmentsManager
  demosplan/DemosPlanCoreBundle/Repository/SegmentRepository.php
Labels: review:backend, quick-win
