Repository demos-europe/demosplan-core, pull requests merged in 2023-10, with the labels that each got.

#1988 feat: in case of a phpunit test fail the ci should fail
  Jenkinsfile
  demosplan/DemosPlanCoreBundle/ValueObject/APIPagination.php
  tests/backend/core/Core/Unit/Utilities/Twig/Base64ExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/DatasheetNumberFormatExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/DateExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/FileExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/HeightLimitExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/MapExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/TwigToolsExtensionTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/WysiwygExtensionTest.php
  tests/backend/core/Core/Unit/ValueObject/APIPaginationTest.php
  tests/backend/core/Document/Unit/DocumentBundleImporterTest.php
  tests/backend/core/Procedure/Functional/ProcedureTypeServiceTest.php
Labels: devops, review:backend

#2098 feature (refs T34758): Rename KeyCloak role-map
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentController.php
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
Labels: type:bug, review:backend

#2080 Fix(T34793): segment id performance
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiEsService.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcBulkEditor/RpcSegmentIdLoader.php
  demosplan/DemosPlanCoreBundle/Traits/DI/ElasticsearchQueryTrait.php
Labels: review:frontend, review:backend

#2112 fix(refs T19759): make tailwind css compile with the changed vue3 setup
  babel.config.js
  client/css/tailwind.css
  client/fe/webpack/moduleRules.js
  config.webpack.js
  package.json
  yarn.lock
Labels: type:bug, review:frontend, type:enhancement

#2118 feature (refs T34504): Setup SupportContact entity and added Migration
  config/services_repositories.yml
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/10/Version20231006133151.php
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
  demosplan/DemosPlanCoreBundle/Repository/SupportContactRepository.php
Labels: review:backend

#2106 F validate draft json
  demosplan/DemosPlanCoreBundle/Constraint/SegmentDraftJsonConstraint.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementResourceTypeService.php
  demosplan/DemosPlanCoreBundle/Validator/SegmentDraftJsonConstraintValidator.php
  tests/backend/core/Statement/Functional/StatementResourceTypeServiceTest.php
  translations/validators.de.yml
Labels: review:backend

#2129 Feat(T34093): add content to the accessibility page - diplanbau
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#2109 feature (refs T32796): Removes a migration where the content was already run in Version20230711125038
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/07/Version20230706091408.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/07/Version20230711125038.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/09/Version20230925135949.php
Labels: type:bug, review:backend

#2141 fix(refs: T34975): show list items in Boilerplate modal
  client/js/components/statement/DpBoilerPlate.vue
Labels: type:bug, review:frontend

#2122 chore: try to fix environment in tests
  config/config_core.yml
  config/config_dev_container.yml
  config/config_dev_container_services.yml
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
  demosplan/DemosPlanCoreBundle/Command/UpdateCommand.php
  tests/backend/core/Core/Functional/EventFinderTest.php
  tests/backend/core/Core/Unit/Logic/Elements/PlanningDocumentCategoryTreeReordererTest.php
  tests/backend/core/Map/Unit/FeaturesToMapLayersConverterTest.php
  tests/backend/core/Procedure/Functional/SubdomainHandlerTest.php
  tests/backend/core/Statement/Functional/SimiliarStatementSubmitterTest.php
  tests/backend/core/Statement/Functional/StatementDeleterTest.php
  tests/backend/core/Statement/Functional/StatementMoverTest.php
Labels: review:backend

#2030 feat: logout from keycloak during local logout
  config/packages/security.yaml
  config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/LogoutSubscriber.php
Labels: review:backend

#2110 refactor: use fully qualified name for relationships
  demosplan/DemosPlanCoreBundle/Entity/MailSend.php
  demosplan/DemosPlanCoreBundle/Entity/Map/GisLayer.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Boilerplate.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/BoilerplateGroup.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureBehaviorDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureCoupleToken.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureType.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureUiDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/StatementFieldDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/StatementFormDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Tag.php
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTag.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/Entity/User/OrgaType.php
  demosplan/DemosPlanCoreBundle/Entity/User/Role.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
Labels: type:bug, review:backend

#2142 fix(refs: T34961): Pass ID as Tooltip container param
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#2153 fix(refs: T34971): Remove unwanted closing bracket
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/customer_settings_update_mail.html.twig
Labels: type:bug, review:frontend

#2154 feature (refs T34983): Fix manual Faq sort
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqService.php
Labels: type:bug, review:backend, quick-win

#2139 feature (refs T34504): allow setup and display of support contact information
  .reviewdog.yml
  client/js/bundles/faq/faqlist.js
  client/js/bundles/user/customerSettings.js
  client/js/components/support/DpSupport.vue
  client/js/components/support/DpSupportCard.vue
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  client/js/store/core/VuexApiRoutes.js
  config/permissions.yml
  config/services_repositories.yml
  demosplan/DemosPlanCoreBundle/Constraint/SupportContactConstraint.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/10/Version20231006133151.php
  demosplan/DemosPlanCoreBundle/Entity/Branding.php
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
  demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php
  demosplan/DemosPlanCoreBundle/Repository/SupportContactRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/BrandingResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerContactResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/FileResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OriginalStatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/SignLanguageOverviewVideoResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/UserResourceType.php
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_color.scss
  demosplan/DemosPlanCoreBundle/Resources/public/img/phone.svg
  demosplan/DemosPlanCoreBundle/Validator/SupportContactConstraintValidator.php
  translations/messages+intl-icu.de.yml
  translations/validators.de.yml
Labels: review:frontend, review:backend

#2123 chore: add option to enable addon during installation
  demosplan/DemosPlanCoreBundle/Addon/AddonRegistry.php
  demosplan/DemosPlanCoreBundle/Addon/Composer/PackageInformation.php
  demosplan/DemosPlanCoreBundle/Addon/Registrator.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: type:bug, review:backend, type:enhancement

#2124 feat: introduce addon list command
  demosplan/DemosPlanCoreBundle/Addon/AddonManifestCollectionWrapper.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonListCommand.php
  tests/backend/core/Core/Functional/AddonListCommandTest.php
Labels: review:backend

#2068 chore: add helper methods for installed and enabled addons
  demosplan/DemosPlanCoreBundle/Addon/AddonRegistry.php
  tests/backend/core/Core/Functional/AddonRegistryTest.php
Labels: review:backend

#2144 feature (refs T15052): remove faulty ORM-Annotations
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureUiDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Entity/User/CustomerCounty.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
Labels: review:backend

#2145 F t15052 tidy up docreine migrations diff
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureUiDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/StatementFieldDefinition.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/StatementFormDefinition.php
Labels: review:backend

#2162 F t35031 adjust redirect after pdf import
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
Labels: type:bug, review:frontend, quick-win

#2161 feature (refs T33642): fix faulty new line and out of place empty space
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/send_notification_email_for_unsubmitted_draft_statements.html.twig
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, quick-win

#2164 chore: Bump demosplan-ui from 0.2.0 to v0.2.1
  package.json
  yarn.lock
Labels: review:frontend, type:enhancement

#2132 chore (refs T34979): add missing props, when editor used dpUploadModal.
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_new.html.twig
Labels: review:frontend, quick-win, type:enhancement

#2169 chore: move some components from demosplan-ui to Core and rename it.
  client/js/bundles/statement/viewStatement.js
  client/js/components/shared/TextContentRenderer.vue
  client/js/components/statement/HeightLimit.vue
  client/js/components/statement/assessmentTable/DpBulkEditFragment.vue
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
  client/js/components/statement/assessmentTable/DpFragmentsSwitcher.vue
  client/js/components/statement/assessmentTable/EditableText.vue
  client/js/components/statement/fragmentList/Fragment.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
  demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/view_statement.html.twig
Labels: review:frontend, type:enhancement

#2172 chore: Group Sentry dependencies for Dependabot
  .github/dependabot.yml
Labels: review:frontend, type:enhancement

#2156 Fix(refs:35060): remove required symbol for emailAddress
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#2163 fix(refs T35059): Catch ununique Titles before sending them to the BE
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#2175 chore(refs T35059): Optimize Translations (keys and String)
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#2176 fix(refs T35113): Add missing Transkey
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, quick-win

#2171 feature (refs T35088): regard DateTime Objects when calculating changes to procedures
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureUpdatedEvent.php
Labels: type:bug, review:backend

#2187 feat(refs T34359): Display Version in diplanRog Console.
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_version.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:enhancement, type:story

#2146 chore (refs T34808): redirect to distinct error page after idp login error
  demosplan/DemosPlanCoreBundle/Controller/Platform/EntrypointController.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/login_idp_error.html.twig
Labels: review:frontend, review:backend

#2191 bug(refs T34955): Add required prop
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
Labels: type:bug, review:frontend, quick-win

#2166 chore: add data user role to fixtures
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadCategoryData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadMailTemplateData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadMigrationVersionData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureTypeData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadRolesData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadUserData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/ProdFixture.php
Labels: review:backend

#2200 chore refs T35168: css var value might be null as stated in entity
  demosplan/DemosPlanCoreBundle/Validator/ValidCssVarsConstraintValidator.php
Labels: type:bug, review:backend

#2210 Feat(refs:35155): add the new greeting formel
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/send_notification_email_for_released_statement.html.twig
Labels: review:frontend, type:story

#2218 f_T34920 show more causes an error message
  demosplan/DemosPlanStatementBundle/Resources/client/js/components/originalStatementsTable/OriginalStatementsTableItem.vue
Labels: type:bug, review:frontend, quick-win

#2217 feat (T35051): implement the FileInfoInterface and adjust composer lock
  composer.lock
  demosplan/DemosPlanCoreBundle/ValueObject/FileInfo.php
Labels: review:backend, quick-win

#2211 feat: Disable reviewdog on draft prs
  .github/workflows/reviewdog.yml
Labels: devops

#2222 fix(refs T35173): Skip own Title when checking for Uniqueness
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
Labels: type:bug, review:frontend

#2219 Fix(refs:34497): add introduction trans key to core
  translations/messages+intl-icu.de.yml
Labels: review:frontend
