Repository demos-europe/demosplan-core, pull requests merged in 2024-01, with the labels that each got.

#2486 feature (ref 35885): use statement parent id except statement id
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
Labels: type:bug, review:backend

#2468 chore: automatically enable addon during installation
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend, quick-win

#2504 feature (ref 26430): chnage method of route from get to post
  client/js/components/procedure/admin/AdministrationProceduresList.vue
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureListController.php
Labels: type:bug, review:backend

#2362 F T35519 fix deleting orphaned emails
  composer.lock
  demosplan/DemosPlanCoreBundle/Event/GetEmailIdsEvent.php
  demosplan/DemosPlanCoreBundle/Logic/EmailAddressService.php
  demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php
Labels: type:bug, review:backend

#2508 Fix(refs: T35879): incorrect parameter in getRequest
  client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
Labels: type:bug, review:frontend

#2510 feature (ref 35950): remove token from twig, because csrf token in em…
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanMailController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_email.html.twig
Labels: type:bug, review:backend

#2511 F t35495 stn shall not be overwritten when segmentdraftlist exist
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/listStatements/ListStatements.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, quick-win, type:enhancement

#2515 feature (ref 35952): use different method for statement with or witho…
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
Labels: type:bug, review:backend

#2465 chore (refs T19759 T19787): migration Render Function to vue3.
  client/js/components/procedure/AdministrationImport/AdministrationImportNone.vue
  client/js/components/shared/TextContentRenderer.vue
Labels: review:frontend, support:frontend, type:enhancement

#2513 B(T35949): adjustments in core for DpApi method
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
  client/js/lib/statement/AssessmentTable.js
  client/js/lib/statement/AssessmentTableOriginal.js
Labels: review:frontend

#2488 Fix(T35897): no layer available after fetch capabilities
  client/js/components/map/admin/LayerSettings.vue
Labels: review:frontend

#2485 Fix validation of unique statement.internId per procedure
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
  demosplan/DemosPlanCoreBundle/Validator/PrePersistUniqueInternIdConstraintValidator.php
Labels: review:backend, type:story

#2532 fix(T35874): add white space wrapping for the procedure name
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
Labels: quick-win

#2537 Fix(refs: T35991): the access to the segments count was incorrect or …
  client/js/components/procedure/DpDashboardTaskCard.vue
Labels: type:bug, review:frontend, quick-win

#2524 Fix(refs: T35961): incorrect redirect by click to procedure in nav menu
  demosplan/DemosPlanCoreBundle/Services/Breadcrumb/Breadcrumb.php
  demosplan/DemosPlanCoreBundle/Services/Breadcrumb/BreadcrumbTwigExtension.php
Labels: type:bug, review:backend

#2540 feature (refs T35961): cleanup leftovers that are not needed for chosen solution
  demosplan/DemosPlanCoreBundle/Services/Breadcrumb/Breadcrumb.php
Labels: review:backend, quick-win

#2535 bug(refs T35838): Check for overlapping segments
  client/js/store/procedure/SplitStatementStore.js
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#2541 Fix(T35990): badge position
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: quick-win

#2542 fix (T35993): lock value object before usage
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiEsService.php
Labels: review:backend, quick-win

#2548 fix(refs:T36011): the resourceType was incorrect
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
Labels: type:bug, review:frontend, quick-win

#2543 chore: update headers to match http2 standard
  demosplan/DemosPlanCoreBundle/Application/Header.php
Labels: review:backend

#2551 feature (ref 36020): set static statement data before create planning…
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilder.php
Labels: type:bug, review:backend

#2539 feature (ref 35989): use condition in handler, not in copier
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
Labels: type:bug, review:backend

#2531 feature (ref 35888): set targetBlank as an allow list
  demosplan/DemosPlanCoreBundle/Services/HTMLSanitizer.php
Labels: type:bug, review:backend

#2455 feat (refs T33578): delete related original statement on delete statement.
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadStatementData.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/SegmentFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/StatementFactory.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementDeleter.php
  tests/backend/core/Statement/Functional/StatementDeleterTest.php
Labels: help wanted, review:backend

#2553 chore: update `composer.lock` to current EDT dependency
  composer.lock
  demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php
Labels: review:backend

#2470 chore: show addons to build frontend for. Allow env to be passed
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
Labels: review:backend

#2554 fix (refs T36008): update `composer.lock` to current EDT dependency
  composer.lock
Labels: review:backend

#2566 feature (ref 36035): remove second calling method
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Labels: type:bug, review:backend

#2567 bug(refs T35883): Remove unnecessary title prop
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_split_statement.html.twig
Labels: type:bug, review:frontend, quick-win

#2570 F t36053 files on statement copy
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: type:bug, review:backend

#2549 fix: some fields are incorrect or there were missing check
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/SegmentsRecommendations.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/listStatements/ListStatements.vue
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_statement_segments_list.html.twig
Labels: review:frontend, review:backend, quick-win, type:enhancement

#2569 fix(T36027): issue with elements in the OriginalStatementsTableItem component
  client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
Labels: review:frontend

#2578 bug(refs T36069): Fix attribute name for attachment type
  client/js/components/statement/listStatements/ListStatements.vue
Labels: type:bug, review:frontend, quick-win

#2568 chore (refs T34499): add missing Hooks/Selectors.
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
Labels: review:frontend, quick-win, type:enhancement

#2581 chore (refs T34335): add missing Hooks/Selectors.
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
Labels: review:frontend, quick-win, type:enhancement

#2584 fix(refs T36079): fix segment can not be updated
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#2585 fix (refs T36081): remove unnecessary quoting
  demosplan/DemosPlanCoreBundle/Repository/SegmentRepository.php
Labels: type:bug, review:backend, quick-win

#2593 Change build to support Tailwind in addons
  client/fe/config/config.js
  client/fe/index.js
  client/fe/webpack/moduleRules.js
  client/fe/webpack/plugins.js
  client/fe/webpack/runWebpack.js
  config.webpack.js
  demosplan/DemosPlanCoreBundle/Twig/Extension/WebpackBundleExtension.php
  package.json
  tailwind.config.js
  yarn.lock
Labels: review:frontend, review:backend

#2506 refactor: Extract virusChecker for rabbitmq virus check
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
  demosplan/DemosPlanCoreBundle/Tools/VirusCheckInterface.php
  demosplan/DemosPlanCoreBundle/Tools/VirusCheckRabbitmq.php
Labels: review:backend

#2507 feat: use avscan http service
  config/config_dev_container.yml
  config/config_dev_container_services.yml
  config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Tools/VirusCheckHttp.php
Labels: review:backend

#2555 Rector update php
  composer.json
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Addon/AddonDoctrineMigrationsPass.php
  demosplan/DemosPlanCoreBundle/Attribute/DplanPermissions.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonUninstallCommand.php
  demosplan/DemosPlanCoreBundle/Command/ClassGenerator/EntityCompanionGeneratorCommand.php
  demosplan/DemosPlanCoreBundle/Command/Data/DeleteProcedureCommand.php
  demosplan/DemosPlanCoreBundle/Constraint/SupportContactConstraint.php
  demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureListController.php
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Procedure/ProcedureFactory.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/ConsultationToken.php
  demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureDeletedEvent.php
  demosplan/DemosPlanCoreBundle/Form/AbstractBaseResourceFormType.php
  demosplan/DemosPlanCoreBundle/Form/BoilerplateType.php
  demosplan/DemosPlanCoreBundle/Form/PreparationMailType.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceLinkageFactory.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/ResourceTypeStore.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AbstractRpcStatementBulkAction.php
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Logic/EditorService.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/FileResponseGeneratorAbstract.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilder.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilderWithZipSupport.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporterWithZipSupport.php
  demosplan/DemosPlanCoreBundle/Logic/Maps/MapProjectionConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcSegmentFacetsProvider.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Logic/TransformMessageBagService.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserService.php
  demosplan/DemosPlanCoreBundle/Logic/ZipImportService.php
  demosplan/DemosPlanCoreBundle/Permissions/CachingYamlPermissionCollection.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Repository/UserRepository.php
  demosplan/DemosPlanCoreBundle/Security/User/SamlUserFactory.php
  demosplan/DemosPlanCoreBundle/Services/HTMLFragmentSlicer.php
  demosplan/DemosPlanCoreBundle/Services/SubdomainHandler.php
  demosplan/DemosPlanCoreBundle/Tools/DocxImporterRabbitmq.php
  demosplan/DemosPlanCoreBundle/Tools/PdfCreatorRabbitmq.php
  demosplan/DemosPlanCoreBundle/Types/UserFlagKey.php
  demosplan/DemosPlanCoreBundle/ValueObject/UnnamedEventMatch.php
  tests/backend/core/User/Functional/UserHandlerTest.php
  tests/backend/core/User/Functional/UserServiceTest.php
Labels: review:backend

#2610 feature (refs T35857): adjust userSettings E-mail notification checkbox state for first visitors
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
Labels: review:backend

#2618 fix(refs T36141): serialize request params
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#2620 Fix(refs:36153): use the correct access for the dates
  client/js/components/procedure/admin/AdministrationProceduresList.vue
Labels: type:bug, review:frontend

#2619 Fix(refs:36132): problem by creating new procedure
  client/js/lib/procedure/CreateProcedure.js
Labels: type:bug, review:frontend

#2624 Minor layout fixes
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_footer.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header_nav_item_sign_language.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header_nav_item_simple_language.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig
Labels: type:bug, review:frontend

#2575 feature (ref 36036): set method internIdInUsed to call in Importer an…
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/AbstractStatementFromRowBuilder.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilder.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilderWithZipSupport.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php
  demosplan/DemosPlanCoreBundle/Validator/PrePersistUniqueInternIdConstraintValidator.php
  tests/backend/base/FunctionalTestCase.php
  tests/backend/core/Import/ZipImportServiceTest.php
  tests/backend/core/Statement/Functional/StatementImportTest.php
  tests/backend/core/Statement/Functional/res/dde7f809d7eea51123456799cae3a3bb_intern_id.xlsx
Labels: type:bug, review:backend

#2607 chore: ensure that field is nullable as this is not the case in all projects
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2023/03/Version20230324132250.php
Labels: review:backend, quick-win

#2612 chore: improve error logging in RpcAddonAssetsLoader
  demosplan/DemosPlanCoreBundle/Addon/RpcAddonAssetsLoader.php
Labels: review:backend, quick-win

#2616 chore: sort addon tags during install via GitHub
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend, quick-win

#2631 chore: remove useless and misleading Interface
  demosplan/DemosPlanCoreBundle/ValueObject/Statement/DraftStatementListFilters.php
Labels: review:backend

#2625 Select checkbox by default if only 1 boilerplate category is present
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate.html.twig
Labels: review:frontend, type:enhancement

#2514 feature (refs T34551): refactor procedure customer relation
  composer.lock
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/01/Version20240105113406.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/01/Version20240108110342.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureToLegacyConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
  tests/backend/core/Procedure/Functional/ProcedureServiceTest.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#2617 bug(refs T29693): Add margin for buttons
  client/js/components/user/DpUserList/DpUserFormFields.vue
  client/js/components/user/DpUserList/DpUserList.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_departments.html.twig
Labels: type:bug, review:frontend

#2642 bug(refs T18750): Add min height for editor p tags
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_styled-html.scss
Labels: type:bug, review:frontend

#2643 bug(refs T36229): Send JSON instead of string
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
Labels: type:bug, review:frontend, quick-win

#2645 Fix new phases of procedure
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/01/Version20240130051137.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
Labels: type:bug, review:frontend, support:backend, support:frontend, type:story

#2650 allow strike-through in pdf
  demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
  tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php
Labels: review:backend

#2654 feature (ref 36217): Add missed Translation Key
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend

#2655 bug(refs T36246): Allow char start and char end to be the same
  client/js/store/procedure/SplitStatementStore.js
Labels: type:bug, review:frontend

#2660 feature (ref 36190): remove extra link in header
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig
Labels: type:bug, review:frontend

#2656 fix(refs T36221): throw error if statements present
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanMasterToebController.php
  demosplan/DemosPlanCoreBundle/Exception/SubmittedStatementsOnMergeOrganisationsException.php
  demosplan/DemosPlanCoreBundle/Repository/MasterToebRepository.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend

#2587 chore (refs T34287): Add missing Hooks/Selectors.
  client/js/components/procedure/DpSubmitterList.vue
  client/js/components/procedure/SegmentsList/CustomSearch.vue
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/SegmentsList/FilterFlyoutCheckbox.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_segments_list.html.twig
Labels: review:frontend, quick-win, type:enhancement

#2630 Feat(T33381): add contact and location info to the institution list
  client/js/components/procedure/admin/DpAddOrganisationList.vue
  client/js/store/core/VuexApiRoutes.js
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionLocationContactResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InvitablePublicAgencyResourceType.php
Labels: review:frontend, review:backend

#2626 chore: modernize frontcontrollers to match symfony 5.x
  demosplan/DemosPlanCoreBundle/Application/FrontController.php
  tests/backend/core-application/app/config/config_test.yml
  tests/backend/core-application/src/Application/FrontController.php
Labels: review:backend

#2646 feature (ref 23064): use an if condition to can send email as a empty…
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: type:bug, review:backend

#2663 allow highlighted text in pdf export
  demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
  tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php
Labels: review:backend
