Repository demos-europe/demosplan-core, pull requests merged in 2024-10, with the labels that each got.

#3726 F dplan 12495 adjust create statement
  client/js/components/statement/listStatements/ListStatements.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
Labels: type:bug

#3745 fix(DPLAN-12564): empty detail page of STN
  client/js/components/statement/assessmentTable/DetailView/DetailView.vue
Labels: review:frontend, quick-win

#3734 bug(refs DPLAN-12494): Check button recommendation modal
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#3741 bug(refs DPLAN-2128): persist checkbox selection of search modal in local storage
  client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue
Labels: type:bug, review:frontend

#3747 feat (refs DPLAN-12536): remove duplicated success message
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: type:bug, review:backend

#3742 fix(refs DPLAN-12496): reduce margin
  client/js/components/procedure/SegmentsList/SegmentsList.vue
Labels: type:bug, review:frontend

#3687 chore: custom fix to set permissions is not needed any more
  tests/backend/bootstrap.php
Labels: review:backend

#3755 chore: update demosplan-ui 0.3.33
  package.json
  yarn.lock
Labels: review:frontend

#3746 Add permission to manage Cover page export file
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ExportService.php
Labels: type:bug, review:backend

#3762 chore: sync version of ol used in the masterportal
  .github/dependabot.yml
Labels: dependencies:yarn

#3763 Fix DPLAN-12593 adjust column length
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/10/Version20241004090021.php
  demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
Labels: type:bug, review:backend

#3776 Fix yarn build by downgrading masterportalapi and ol version
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: review:frontend

#3775 fix(refs DPLAN-2834): adjust docx export hint
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#3787 chore (refs DPLAN-564): allow upload of huge files
  demosplan/DemosPlanCoreBundle/Twig/Extension/FileExtension.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig
Labels: review:frontend, review:backend

#3754 fix(DPLAN-12584): add a permission check for the boilerplate button
  client/js/components/statement/assessmentTable/DpBulkEditStatement.vue
Labels: review:frontend, quick-win

#3753 fix(DPLAN-12578): adjust background color for the fullscreen mode
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_at.scss
Labels: review:frontend, quick-win

#3751 fix(refs DPLAN-2153): remove file filter from assessment table filters in planfestsh
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFilterHandler.php
Labels: review:frontend, review:backend, quick-win

#3788 bug(refs DPLAN-12555): Add styling for administration email
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_email_confirm.html.twig
Labels: type:bug, review:frontend

#3752 fix(DPLAN-1941): versions: add list styling
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/versions_of_statement.html.twig
Labels: review:frontend, quick-win

#3791 bug(refs DPLAN-12600): Remove link to old details page
  client/js/components/statement/listStatements/ListStatements.vue
Labels: type:bug, review:frontend

#3793 bug(refs DPLAN-1967): Add min height
  client/js/components/procedure/SegmentsList/SegmentsList.vue
Labels: type:bug, review:frontend

#3732 fix (refs DPLAN-12508): fix wrong customer in url
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
  demosplan/DemosPlanCoreBundle/Services/SubdomainHandler.php
Labels: type:bug, review:backend, quick-win

#3796 feat (DPLAN-12497): remove assessmenttable in specific projects
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: type:bug, review:backend

#3798 bug(refs DPLAN-12608): Remove permission
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/view_statement.html.twig
Labels: type:bug

#3701 chore(refs dplan-12315): Replace draggable with sortable for places
  client/js/components/procedure/admin/AdministrationPlaces.vue
  yarn.lock
Labels: review:frontend, type:enhancement

#3802 bug(refs DPLAN-12611): Set max width
  client/js/components/statement/StatementExportModal.vue
Labels: type:bug, review:frontend

#3799 feat (DPLAN-12497): add permission for subheading
  config/menus.yml
  config/permissions.yml
Labels: type:bug, review:backend

#3806 feat (DPLAN-12610): Allow update on non manual statements
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Labels: type:bug, review:backend

#3797 fix(refs DPLAN-12516): fix statement modal layout
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaSnailMailOrEmail.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#3786 build(refs DPLAN-12315): Remove $on since its removed in vue3
  client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue
  client/js/components/procedure/basicSettings/DpEmailList.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/components/statement/voter/StatementVoter.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
Labels: review:frontend, type:enhancement

#3805 Adjustment Table width
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_original_entry.tex.twig
Labels: type:bug, review:backend

#3807 fix(refs DPLAN-12516): bump demosplan-ui to v0.3.34
  package.json
  yarn.lock
Labels: type:bug, review:frontend

#3808 fix(refs DPLAN-12602): Bump demosplan-ui@0.3.18-2
  package.json
  yarn.lock
Labels: type:bug, review:frontend

#3819 chore: pass csrf token to addon wrapper
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig
Labels: review:frontend

#3827 f DPLAN-12620 adjust InvitablePublicAgencyResourceType :
  demosplan/DemosPlanCoreBundle/ResourceTypes/InvitablePublicAgencyResourceType.php
Labels: review:backend

#3772 Adjust File name in pdf export
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/pdfexport.tex.twig
Labels: type:bug, review:backend

#3834 bug(refs DPLAN-12616): Add condition for document link
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/view_statement.html.twig
Labels: type:bug, review:frontend

#3111 refactor(refs DPLAN-24): allow dragging an faq item into another category [vue 3]
  client/js/components/faq/DpFaqList.vue
  client/js/components/map/admin/AdminLayerListItem.vue
Labels: review:frontend

#3850 chore (refs DPLAN-12006): copy the FAQ from one customer to another
  demosplan/DemosPlanCoreBundle/Command/Data/CopyFaqCommand.php
Labels: review:backend

#3853 Revert "Adjust File name in pdf export"
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/pdfexport.tex.twig
Labels: review:backend

#3852 chore: Bump Babel-Jest@29 and dependents
  package.json
  tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap
  tests/frontend/unit/__snapshots__/DpProcedureCoordinateInput.spec.js.snap
  tests/frontend/unit/__snapshots__/DpPublicLayerListCategory.spec.js.snap
  tests/frontend/unit/__snapshots__/SearchModal.spec.js.snap
  yarn.lock
Labels: review:frontend, dependencies:yarn

#3810 refactor: rewrite orga_data_entry into Vue components
  client/js/bundles/user/editOrga.js
  client/js/components/user/orgaDataEntry/EmailNotificationSettings.vue
  client/js/components/user/orgaDataEntry/OrganisationBrandingSettings.vue
  client/js/components/user/orgaDataEntry/OrganisationDataForm.vue
  client/js/components/user/orgaDataEntry/PaperCopyPreferences.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrgaController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_data_entry.html.twig
Labels: review:frontend

#3848 fix (DPLAN-12622) Adjust permission to display button
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
Labels: review:backend

#3838 bug(refs DPLAN-12623): Fix adding and editing places
  client/js/components/procedure/admin/AdministrationPlaces.vue
Labels: type:bug, review:frontend

#3828 bug(refs DPLAN-12601): Fix layer legend
  client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue
  client/js/components/map/publicdetail/controls/legendList/DpLayerLegendItem.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
Labels: type:bug, review:frontend

#3863 Remove a permission that give institute coordinator to vote
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: type:bug, review:backend

#3870 bug(refs DPLAN-12601): Add title to layer legend
  client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#3839 fix(refs DPLAN-12651): Prevent undefined header fields
  client/js/components/procedure/admin/DpAddOrganisationList.vue
Labels: type:bug, review:frontend

#3826 feat (DPLAN-12571): Add new original statement list
  client/js/bundles/statement/listOriginalStatements.js
  client/js/bundles/statement/listStatements.js
  client/js/components/statement/DpStatementAnonymize.vue
  client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/StatementListController.php
  demosplan/DemosPlanCoreBundle/Exception/UndefinedPhaseException.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/ResourceTypeStore.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/PresentableOriginalStatementFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/OriginalStatementResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/FileResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OriginalStatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ParagraphVersionResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryDetailsResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementMetaResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_original_statements.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story

#3876 B dplan 12666 remove stats permission
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Labels: type:bug, review:backend

#3840 fix (DPLAN-12617) Adjust permission to use same PDF import to display original pdf
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/listStatements/ListStatements.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/FileResourceType.php
Labels: review:frontend, review:backend

#3877 feat (refs DPLAN-12689): add permission to check in file resourcetype
  demosplan/DemosPlanCoreBundle/ResourceTypes/FileResourceType.php
Labels: type:bug, review:backend, quick-win

#3872 fix(refs DPLAN-12667) Send mail PostProcedureCreated to inform support about statistics regarding procedures of orga in customer.
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/EventSubscriber/ProcedureMetricsEmailEventSubscriber.php
Labels: review:backend

#3871 F dplan 12665 enable available phases using api
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  demosplan/DemosPlanCoreBundle/ValueObject/Procedure/PhaseVO.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_statement_segments_list.html.twig
Labels: type:bug, review:frontend, review:backend

#3879 f DPLAN-12711 adjust statement intern id length
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/10/Version20241022180950.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
Labels: review:backend

#3869 bug(refs DPLAN-12623): Refactoring administration places
  client/js/components/procedure/admin/AdministrationPlaces.vue
Labels: type:bug, review:frontend

#3892 F 2024.10 2024.11 release bobhh cherry pick
  composer.json
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Document/SingleDocumentHandler.php
  demosplan/DemosPlanCoreBundle/Repository/ParagraphRepository.php
Labels: type:story

#3893 fix(refs DPLAN-12672): rename datacy hook
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_original_statements.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
Labels: review:frontend, quick-win

#3658 chore: improve locale performance due to best practice
  config/packages/framework.yaml
Labels: review:backend, quick-win

#3901 f adjust deprecated command option
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
Labels: quick-win

#3903 fix(refs DPLAN-12740): Get correct Getter "tags"
  client/js/components/statement/assessmentTable/DetailView/DetailView.vue
Labels: type:bug, review:frontend, quick-win

#3884 bug(refs DPLAN-DPLAN-12715): Add link to orignal statements list
  client/js/components/statement/listStatements/ListStatements.vue
Labels: type:bug, review:frontend

#3878 F dplan 12665 adjust phases usage
  client/js/components/assessmenttable/DpNewStatement.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/PresentableOriginalStatementFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementProcedurePhaseResolver.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/OriginalStatementResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OriginalStatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  demosplan/DemosPlanCoreBundle/ValueObject/Procedure/ProcedurePhaseVO.php
Labels: review:backend

#3905 F dplan 12618 check if one layer al least is available
  client/js/components/map/admin/AdminLayerList.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#3911 f DPLAN-12699 adjust methods parameters
  demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php
Labels: type:bug, review:backend, quick-win
