Repository demos-europe/demosplan-core, pull requests merged in 2024-08, with the labels that each got.

#3249 refactor: use tailwind class for hide visually
  client/js/bundles/document/elementsAdminImport.js
  client/js/components/button/BackToTopButton.vue
  client/js/components/document/ElementsList/IconPublished.vue
  client/js/components/document/ElementsList/IconStatementEnabled.vue
  client/js/components/map/admin/AdminLayerListItem.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListCategory.vue
  client/js/components/procedure/DpSearchProcedures.vue
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  client/js/components/procedure/admin/NewBlueprintForm.vue
  client/js/components/procedure/basicSettings/DpEmailList.vue
  client/js/components/procedure/publicindex/drawer/DetailView.vue
  client/js/components/procedure/survey/DpSurveyChart.vue
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/ConsolidateModal.vue
  client/js/components/statement/assessmentTable/DpExportModal.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/fragment/Edit.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupCitizenOrInstitution.vue
  client/js/components/statement/statement/DpVersionHistory.vue
  client/js/components/statement/statement/DpVersionHistoryItem.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSection.vue
  client/js/components/user/DpMasterToebList/DpFilterMasterToeb.vue
  client/js/lib/procedure/CreateProcedure.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/404.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/html_diff.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_aside.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_oeb_header.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/proceduremenu_statements.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_import.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_list_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/public_elements_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanFaq/faqlist.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanForum/development_release_story_threadentry_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanHelp/help_admin_contextual_help_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_global_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_import.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_masters.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/public_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/list_subscriptions.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail_form.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/form_filter.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
Labels: review:frontend, type:enhancement

#3519 fix(refs DPLAN-12008): Fix copy of attachments from ostns
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: type:bug, review:backend, quick-win

#3524 feat (DPLAN-11982) fix recognition of links
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/Utils/HtmlHelper.php
  tests/backend/core/SegmentExport/HtmlHelperTest.php
Labels: type:bug, review:backend

#3533 chore: add subdomain to oauth_keycloak_logout_route
  demosplan/DemosPlanCoreBundle/EventSubscriber/LogoutSubscriber.php
Labels: review:backend

#3535 chore refs (DPLAN-12231): allow planners to edit invitation email entirely
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig
Labels: review:frontend, review:backend

#3523 chore: initially fpa should be able to create procedures
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadUserData.php
Labels: review:backend

#3540 chore: use current docker scripts
  docker/build.sh
  docker/demosplan-base/Dockerfile
  docker/demosplan-base/README.md
  docker/demosplan-base/zzz-dplan-cli.ini
  docker/demosplan-production/.dockerignore
  docker/demosplan-production/Dockerfile
  docker/demosplan-production/README.md
  docker/demosplan-production/nginx.conf.template
  docker/demosplan-production/php-fpm_www.conf
  docker/demosplan-production/zzz-dplan.ini
  docker/nginx/site.conf
  docker/php8.1-cli-development/Dockerfile
  docker/php8.1-cli-development/files/ssh_host_dsa_key
  docker/php8.1-cli-development/files/ssh_host_dsa_key.pub
  docker/php8.1-cli-development/files/ssh_host_ed25519_key
  docker/php8.1-cli-development/files/ssh_host_ed25519_key.pub
  docker/php8.1-cli-development/sshd_config
  docker/php8.1-cli-development/start.sh
  docker/php8.1-cli-development/zshenv
  docker/php8.1-cli-development/zzz-dplan.ini
  docker/php8.1-cli-maintenance/Dockerfile
  docker/php8.1-cli-maintenance/start.sh
  docker/php8.1-cli-maintenance/zzz-dplan.ini
  docker/php8.1-fpm-xdebug/Dockerfile
  docker/php8.1-fpm-xdebug/xdebug.conf
  docker/php8.1-fpm/Dockerfile
  docker/rsyncExcludeProject.txt
  docker/rsyncInclude.txt
Labels: devops

#3528 feat(refs AB#14277): adjust cookie consent text
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/piwik.html.twig
Labels: review:frontend

#3536 feat (refs AB#14276): Update data protection
  client/js/bundles/misccontent/dataProtection.js
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#3494 Fix planning document category resource type test
  tests/backend/base/AbstractApiTest.php
  tests/backend/base/HttpTestCase.php
  tests/backend/core/JsonApi/Functional/PlanningDocumentCategoryResourceTypeTest.php
  tests/backend/integration/DemosPlanUserControllerTest.php
Labels: review:backend

#3482 Fix twig tool extensions test
  tests/backend/core/Core/Unit/Utilities/Twig/TwigToolsExtensionTest.php
Labels: review:backend

#3529 F dplan 12208 fix attachment copy on ostn copy
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: review:backend, quick-win

#3554 fix(refs AB#18954): fix SegmentBulkEditorServiceTest.php
  tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/SegmentBulkEditorServiceTest.php
Labels: review:backend

#3553 chore (refs DPLAN-12193): Add missing Hooks.
  client/js/components/procedure/SegmentsList/CustomSearch.vue
Labels: review:frontend, quick-win, type:enhancement

#3549 fix(refs AB#18954): send correct relationship to BE
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
Labels: review:frontend

#3557 B ado18953 success notification
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: type:bug, review:backend

#3560 F dplan 12268 check if password exists before reset
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend

#3562 chore (refs DPLAN-12286, DPLAN-12253): Adjust SideBar Styling.
  client/js/components/statement/splitStatement/AssignedTags.vue
  client/js/components/statement/splitStatement/SideBar.vue
Labels: type:bug, review:frontend

#3565 refactor(refs AB#18560): use demosplan-ui components in export modal
  client/js/components/statement/assessmentTable/DpExportModal.vue
Labels: review:frontend

#3564 chore (refs DPLAN-12198): Add missing Hooks/Selectors.
  client/js/components/procedure/admin/AdministrationPlaces.vue
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/components/user/DpCreateItem.vue
Labels: review:frontend, quick-win, type:enhancement

#3570 fix(refs dplan 12265): Pass Procedure ID properly to documents editor…
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_new.html.twig
Labels: review:frontend

#3572 fix(refs dplan 11843): Pass Procedure ID properly to documents editor…
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_new.html.twig
Labels: review:frontend

#3573 refactor (refs AB#18561): Don't extend xlsExporter
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableZipExporter.php
  tests/backend/core/Statement/Functional/StatementExportTest.php
Labels: review:backend

#3500 fix(refs DPLAN-12130): Don't make unneccessary drawing updates
  client/js/components/map/admin/MapAdmin.vue
  client/js/components/map/map/DpOlMapDrawFeature.vue
  client/js/components/map/map/DpOlMapEditFeature.vue
  client/js/components/map/map/MapView.vue
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#3566 feature (refs AB#18560): new page per original statement
  client/js/components/statement/assessmentTable/DpExportModal.vue
  config/statement/assessment_export_options.yml
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentExportController.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_original.tex.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story

#3575 Extract es result creation from Statement Service
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/Statement/ElasticsearchResultCreator.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: review:backend, type:enhancement

#3577 update territory
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/08/Version20240821091730.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
Labels: type:bug, review:backend

#3548 update uninstall addon
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonUninstallCommand.php
Labels: review:backend

#3580 feat (refs AB#18561): o statments pdf zip
  client/js/components/statement/assessmentTable/DpExportModal.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/ZipResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentExportOptions.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableZipExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/Enum/ListLineWidth.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story

#3584 chore: Bump demosplan-ui to 0.3.18-1
  package.json
  yarn.lock
Labels: type:bug, review:frontend

#3571 F add missing cypress hooks selectors
  client/js/components/document/DpMapSettingsPreview.vue
  client/js/components/procedure/DpDashboardTaskCard.vue
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/ToggleForm.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/includes/item/files.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header_userbox.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanHelp/help_admin_contextual_help_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_email_confirm.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/list_data_input_orga_procedures.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/view_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_orga_statements.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/customer_settings_update_mail.html.twig
Labels: review:frontend, lifecycle:do-not-merge, quick-win, type:enhancement

#3561 bug (refs AB#19037): use permission to access role list
  client/js/bundles/user/listUser.js
  client/js/components/user/DpUserListExtended.vue
  client/js/components/user/DpUserListExtendedItem.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/RoleResourceType.php
Labels: type:bug, review:frontend, review:backend

#3582 refactor: Use tailwind classes
  client/js/components/statement/assessmentTable/DpExportModal.vue
Labels: review:frontend, type:enhancement

#3589 f DPLAN 12334 adjust orga _orga_addresses_doctrine on delete operati…
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/08/Version20240826125829.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
Labels: review:backend

#3591 Update latex to adjustment data
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
Labels: type:bug, review:backend

#3599 fix (refs DPLAN-12347): Fix tags display for Segment.
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#3594 update latex to adjustment pdf
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
Labels: type:bug, review:backend

#3600 feat(refs AB#18561): Change trans key for export
  translations/messages+intl-icu.de.yml
Labels: review:frontend, quick-win, type:story

#3576 fix(DPLAN-1881 and DPLAN-1941): the bullet points are not being applied
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  client/js/components/support/DpSupportCard.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanFaq/faqlist.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/newsdetail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/public_newsdetail.html.twig
Labels: review:frontend, quick-win

#3585 Fix(Dplan-2862): ui improvement: export settings
  client/js/components/procedure/basicSettings/ExportSettings.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#3598 Fix(dplan-2307): map toolbar layout issue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_actionbox.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
Labels: review:frontend

#3601 fix(DPLAN-12326): image overlaps text
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/newsdetail.html.twig
Labels: review:frontend, quick-win

#3609 F dplan 12254 custom drupal filter condition factory
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/ConditionFactory/DemosPlanDrupalConditionFactory.php
Labels: review:backend
