Repository demos-europe/demosplan-core, pull requests merged in 2024-06, with the labels that each got.

#3201 f-DPLAN-11656 include customer in query result
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
Labels: type:bug, review:backend

#3208 chore (refs DPLAN-609): file uploads itself should not be checked for procedure permissions
  demosplan/DemosPlanCoreBundle/EventListener/AccessProcedureListener.php
Labels: type:bug, review:backend

#3210 chore: Upgrade jest
  yarn.lock
Labels: review:frontend

#3212 bug(refs DPLAN-1910): Use js delete instead of Vue.delete
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
  client/js/components/user/DpUserList/DpUserList.vue
Labels: type:bug, review:frontend

#3218 bug(refs DPLAN-2005): Remove uppercase
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
Labels: type:bug, review:frontend

#3215 F fix deprecations
  demosplan/DemosPlanCoreBundle/Entity/File.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: review:backend

#3221 fix(refs DPLAN-11741): avoid loading/fetching addons multiple times
  client/js/components/addon/AddonWrapper.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/js/dplan.settings.js.twig
Labels: type:bug, review:frontend, type:enhancement

#3211 bug(refs DPLAN-1909): Add whitespace normal for multiselect
  client/js/components/user/DpUserList/DpUserFormFields.vue
Labels: type:bug, review:frontend

#3213 bug(refs DPLAN-1912): Use correct property name
  client/js/components/procedure/admin/DpAddOrganisationList.vue
Labels: type:bug, review:frontend

#3220 bug(refs DPLAN-2168): Use size method to see if element exists
  client/js/lib/procedure/charts/Legend.js
Labels: type:bug, review:frontend, quick-win

#3223 chore: minor: docblockadjustments
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
Labels: quick-win

#3224 chore: Revert eslint-plugin-jest update
  package.json
  yarn.lock
Labels: review:frontend

#3166 fix (refs ADO-16169): Adjust dockBlock of method to not be misleading.
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
Labels: review:backend, quick-win

#3091 F dplan 11483 additional permissions paid orga
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/User/OrgaStatusInCustomerFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/User/OrgaTypeFactory.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/06/Version20240606084357.php
  demosplan/DemosPlanCoreBundle/Entity/Permission/AccessControl.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/User/OrgaHandler.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Repository/AccessControlRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
  tests/backend/core/AccessControlPermission/AccessControlPermissionServiceTest.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#3129 chore: update pagerfanta bundle
  composer.json
  composer.lock
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFragmentService.php
  demosplan/DemosPlanCoreBundle/Utilities/Pagination/DemosPlanArrayAdapter.php
Labels: review:backend

#3196 f-DPLAN-11703 take notifications order in account while procedure creating
  demosplan/DemosPlanCoreBundle/Repository/NewsRepository.php
Labels: type:bug, review:backend

#3206 chore (refs DPLAN-11545): Add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_header.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_oeb_header.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3237 bug(refs DPLAN-11746): Add timeout before redirecting
  client/js/components/statement/publicStatementModal/StatementModal.vue
Labels: type:bug, review:frontend

#3236 chore: improve SubdomainHandler docblock
  demosplan/DemosPlanCoreBundle/Services/SubdomainHandler.php
  demosplan/DemosPlanCoreBundle/Services/SubdomainHandlerInterface.php
Labels: review:backend, quick-win

#3240 chore (refs DPLAN-11668): Add missing Hooks/Selectors.
  client/js/components/procedure/publicindex/drawer/List.vue
  client/js/components/procedure/publicindex/drawer/ListItem.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail_form_confirmation_loggedin.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/new_public_participation_statement_confirm_content.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3235 bug(refs DPLAN-1879): Add aria-live for accessibility
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
  client/js/components/procedure/publicindex/drawer/Drawer.vue
Labels: type:bug, review:frontend

#3026 feat: Set permissions in Http Tests
  config/services.yml
  demosplan/DemosPlanCoreBundle/EventListener/SetHttpTestPermissionsListener.php
  tests/backend/base/HttpTestCase.php
  tests/backend/core/Core/Functional/SetTestPermissionsListenerTest.php
  tests/backend/integration/DemosPlanUserControllerTest.php
Labels: review:backend

#3241 feat (DPLAN-11765) Check customer subdomain instead of globalconfig (default) subdomain
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/User/OrgaStatusInCustomerFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/User/OrgaTypeFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  tests/backend/core/AccessControlPermission/AccessControlServiceTest.php
Labels: review:backend, type:story

#3242 B dplan 11776 catch assert exception
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
Labels: review:backend, type:story

#3245 bug(refs DPLAN-2759): Add h1 heading for public index
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_index.html.twig
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#3248 chore (refs DPLAN-11771): Add missing Hooks/Selectors.
  client/js/components/user/DpUserList/DpUserList.vue
Labels: review:frontend, quick-win, type:enhancement

#3250 bug(refs DPLAN-1879): Use the right attribute for label prop
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
Labels: type:bug, review:frontend, quick-win

#3251 chore (refs DPLAN-11770): Add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_departments.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3216 F dplan 11470 create command to add permissions
  demosplan/DemosPlanCoreBundle/Command/Permission/EnablePermissionForCustomerOrgaRoleCommand.php
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
  tests/backend/core/Core/Functional/Command/EnablePermissionForCustomerOrgaRoleCommandTest.php
Labels: review:backend, type:story

#3128 chore: remove deprecated sensio/framework-extra-bundle
  composer.json
  composer.lock
  config/bundles.php
  config/packages/sensio_framework_extra.yaml
  symfony.lock
Labels: review:backend, quick-win

#3219 chore: Update and add template for PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: quick-win, type:enhancement

#3257 f DPLAN-11794 use customer id instead array
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
Labels: type:bug, review:backend, quick-win

#2930 feature (ref dplan-11397): define demosplanKernel as a type of variable
  demosplan/DemosPlanCoreBundle/Application/ConsoleApplication.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonUninstallCommand.php
  demosplan/DemosPlanCoreBundle/Command/Db/MigrateCommand.php
  demosplan/DemosPlanCoreBundle/Command/DeployCommand.php
  demosplan/DemosPlanCoreBundle/Command/ElasticsearchPopulateCommand.php
  demosplan/DemosPlanCoreBundle/Command/UpdateCommand.php
Labels: type:bug, review:backend

#3246 feat (DPLAN-11785) Create NewOrgaCreated event and add listener to ca…
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/Event/User/NewOrgaCreatedEvent.php
  demosplan/DemosPlanCoreBundle/Event/User/OrgaAdminEditedEvent.php
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
  demosplan/DemosPlanCoreBundle/Logic/User/RoleHandler.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  tests/backend/core/AccessControlPermission/AccessControlServiceTest.php
Labels: review:backend

#3243 chore (refs DPLAN-11743): Add missing Hooks/Selectors.
  client/js/components/procedure/admin/DpAddOrganisationList.vue
  client/js/components/user/ToggleForm.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/unregistered_publicagency_list.html.twig
Labels: review:frontend, type:enhancement

#3255 chore (refs DPLAN-11769): Add missing Hooks/Selectors.
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
Labels: review:frontend, quick-win, type:enhancement

#3259 feat(DPLAN-24505): adjust PersonalData component
  client/js/components/user/portalUser/PersonalData.vue
Labels: review:frontend

#3214 chore: remove symlink to local addon during uninstall
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonUninstallCommand.php
Labels: review:backend

#3260 chore (refs DPLAN-11503): Add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list_entry.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3097 test: Remove tests for name and object
  tests/frontend/unit/DpAdminLayerList.spec.js
  tests/frontend/unit/DpAutofillSubmitterData.spec.js
  tests/frontend/unit/DpBulkEdit.spec.js
  tests/frontend/unit/DpBulkEditStatement.spec.js
  tests/frontend/unit/DpClaim.spec.js
  tests/frontend/unit/DpEditFieldMultiSelect.spec.js
  tests/frontend/unit/DpLayerLegend.spec.js
  tests/frontend/unit/DpProcedureCoordinateInput.spec.js
  tests/frontend/unit/DpPublicLayerList.spec.js
  tests/frontend/unit/DpPublicLayerListCategory.spec.js
  tests/frontend/unit/DpPublicStatement.spec.js
  tests/frontend/unit/FilterModalSelectItem.spec.js
  tests/frontend/unit/SearchModal.spec.js
  tests/frontend/unit/Status.spec.js
  tests/frontend/unit/__snapshots__/DpProcedureCoordinateInput.spec.js.snap
Labels: review:frontend

#3207 feat: further improve branding logo upload
  client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
Labels: review:frontend

#3273 fix(refs dplan-11814): Adjust pagerfanta-templates after upgrade
  templates/bundles/DemosPlanCoreBundle/macros.html.twig
Labels: type:bug, review:frontend

#3269 feat (DPLAN-11470) adjust command to take orga type into account
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
Labels: review:backend

#3080 Update deprecated Tightenco\Collect to Illuminate\Support\Collection
  composer.json
  demosplan/DemosPlanCoreBundle/Command/Documentation/PermissionListCommand.php
  demosplan/DemosPlanCoreBundle/Command/ElasticsearchPopulateCommand.php
  demosplan/DemosPlanCoreBundle/Command/User/UserListCommand.php
  demosplan/DemosPlanCoreBundle/Command/VendorlistUpdateCommand.php
  demosplan/DemosPlanCoreBundle/Controller/MiscContent/DemosPlanMiscContentController.php
  demosplan/DemosPlanCoreBundle/DataGenerator/CustomFactory/StatementFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/CustomFactory/StatementFragmentFactory.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementFragment.php
  demosplan/DemosPlanCoreBundle/Entity/User/Department.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/Event/Procedure/PublicDetailStatementListLoadedEvent.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/Facet/FacetFactory.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqHandler.php
  demosplan/DemosPlanCoreBundle/Logic/FloodControlService.php
  demosplan/DemosPlanCoreBundle/Logic/Map/FeaturesToMapLayersConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Map/GeoJsonToFeaturesConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Map/MapImageToPolygonCropper.php
  demosplan/DemosPlanCoreBundle/Logic/Map/PolygonIntoMapLayerMerger.php
  demosplan/DemosPlanCoreBundle/Logic/MessageBag.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/SubmitterExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentExportOptions.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementGeoService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Logic/TransformMessageBagService.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserMapperDataportGateway.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserService.php
  demosplan/DemosPlanCoreBundle/Repository/CoreRepository.php
  demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php
  demosplan/DemosPlanCoreBundle/Repository/UserRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
  demosplan/DemosPlanCoreBundle/Services/HTMLFragmentSlicer.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/TwigToolsExtension.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/WebpackBundleExtension.php
  demosplan/DemosPlanCoreBundle/Utilities/Map/MapScreenshotter.php
  demosplan/DemosPlanCoreBundle/ValueObject/Map/Feature.php
  demosplan/DemosPlanCoreBundle/ValueObject/Map/PrintLayer.php
  symfony.lock
  tests/backend/core/Core/Functional/DynamicTransformerTest.php
  tests/backend/core/Core/Functional/MessageBagTest.php
  tests/backend/core/Map/Unit/FeaturesToMapLayersConverterTest.php
  tests/backend/core/Map/Unit/GeoJsonToFeaturesConverterTest.php
  tests/backend/core/Map/Unit/PrintLayerToMapLayerConverterTest.php
  tests/backend/core/Statement/Functional/StatementHandlerTest.php
  tests/backend/core/StatementFragment/StatementFragmentServiceTest.php
  tests/backend/core/User/Functional/ModifyUserCommandTest.php
Labels: review:backend

#2097 Remove disabled method bimschgsh
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: review:backend

#3274 chore (refs DPLAN-11821): Add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanHelp/help_admin_contextual_help_list.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3282 feat (DPLAN-3268): Little refactoring of SegmentsExportController
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
Labels: review:backend, quick-win, type:enhancement

#3280 chore (refs DPLAN-11846): Edit Hooks/Selectors names.
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  config/menus.yml
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3286 chore (refs DPLAN-2743): Add aria-label for map.
  client/js/components/procedure/publicindex/map/Map.vue
Labels: review:frontend, quick-win, type:enhancement

#3261 refactor: unify loading addons
  client/js/components/addon/AddonWrapper.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/lib/addon/loadAddonComponents.js
Labels: review:frontend, type:enhancement

#3285 refacor: Create api2.0 Routes Dynamically
  client/js/store/core/VuexApiRoutes.js
  client/js/store/core/initStore.js
Labels: review:frontend, type:enhancement

#3287 fix(refs dplan 11843): Pass Procedure ID properly to documents editor
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_new.html.twig
Labels: type:bug, review:frontend

#3276 B d2133 remove search bar
  demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanAssessmentTableController.php
Labels: type:bug, review:backend

#3289 chore (refs DPLAN-11855): support file paths with procedure
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphExporter.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
  tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php
Labels: review:backend

#3293 chore (refs DPLAN-11855): fix missing image size during import
  demosplan/DemosPlanCoreBundle/Tools/ServiceImporter.php
  tests/backend/core/Document/Unit/DocumentBundleImporterTest.php
Labels: type:bug, review:backend

#3281 f DPLAN-11684 add listWidth To TemplateVars and pass it on to the latex filter
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphExporter.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_list_export.tex.twig
Labels: type:bug, review:backend

#3292 chore (refs DPLAN-1922): Add hint massage for participation import.
  client/js/components/procedure/AdministrationImport/ParticipationImport/ParticipationImport.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, quick-win

#3296 feat(refs DPLAN-11888): Pass Number instead of null
  client/js/components/user/DpUserList/DpUserList.vue
  client/js/store/core/VuexApiRoutes.js
Labels: type:bug, review:frontend

#3297 chore: Bump Yarn@4.2.2
  package.json
Labels: type:bug, review:frontend

#3233 chore: Bump node 18.18.0
  config/packages/nelmio_security.yaml
  package.json
  yarn.lock
Labels: lifecycle:do-not-merge

#3299 fix: Remove Preinstall hook in Package json
  package.json
  yarn.lock
Labels: type:bug, review:frontend

#3308 chore (refs DPLAN-11389): Add missing Hooks/Selectors.
  client/js/components/map/admin/DpAdminLayerList.vue
  client/js/components/map/admin/DpAdminLayerListItem.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3310 allow multiple ids in permission:enable command
  demosplan/DemosPlanCoreBundle/Command/Permission/DisablePermissionForCustomerOrgaRoleCommand.php
  demosplan/DemosPlanCoreBundle/Command/Permission/EnablePermissionForCustomerOrgaRoleCommand.php
  demosplan/DemosPlanCoreBundle/Command/Permission/PermissionForCustomerOrgaRoleCommand.php
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
  tests/backend/core/Core/Functional/Command/PermissionForCustomerOrgaRoleCommandTest.php
Labels: review:backend

#3294 feat(refs DPLAN-4020): Add Overview Page to Mapsettings
  config/menus.yml
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
  demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
Labels: review:backend, type:story

#3314 feat(refs DPLAN-4020): Add Custom Layer to Segments location
  client/js/bundles/map/mapAdminGislayerList.js
  client/js/components/document/DpMapSettingsPreview.vue
  client/js/components/map/admin/AdminLayerList.vue
  client/js/components/map/admin/AdminLayerListItem.vue
  client/js/components/map/map/DpOlMap.vue
  client/js/components/map/map/DpOlMapLayer.vue
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/store/map/ProcedureMapSettings.js
  demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
  tests/frontend/unit/DpAdminLayerList.spec.js
  tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap
Labels: review:frontend, type:story

#3325 chore (refs DPLAN-11745): Add missing Hooks/Selectors.
  client/js/components/map/admin/LayerSettings.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3326 chore (refs DPLAN-11770): Add missing Hook/Selector.
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_departments.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3295 feat(refs DPLAN-4020): Use Api 2.0 instead of 1.0
  client/js/store/map/Layers.js
  client/js/store/map/ProcedureMapSettings.js
  demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php
Labels: review:frontend, review:backend, type:story

#3315 Feat(DPLAN-32689): create modal window for exporting files
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/StatementExportModal.vue
  client/js/components/statement/listStatements/ListStatements.vue
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#3331 feature (ref 1995): create a message for manually created statement
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: type:bug, review:backend

#3335 f(DPLAN-3268): add unit tests for StatementExportModal component
  tests/frontend/unit/StatementExportModal.spec.js
  tests/frontend/unit/__mocks__/sessionStorage.mock.js
Labels: review:frontend

#3321 chore: check whether role to grant the permission is allowed in the given orga type
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
Labels: type:bug, review:backend

#3130 chore: define return types and type hints to be compatible with symfony 6
  demosplan/DemosPlanCoreBundle/Application/ConsoleApplication.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/Logic/NullablePropertyAccessor.php
  demosplan/DemosPlanCoreBundle/Repository/UserRepository.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php
  demosplan/DemosPlanCoreBundle/Utilities/Pagination/DemosPlanArrayAdapter.php
Labels: review:backend

#3337 feat(refs dplan-4020): Use permission
  client/js/components/map/admin/AdminLayerList.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig
  tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap
Labels: review:frontend

#3340 B dplan11955 renaming
  demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend

#3332 dplan 4020 refactor controller
  config/menus.yml
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
  demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_import.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:backend

#3342 F dplan 11955 adjust translation
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
Labels: type:story

#3343 fix (DPLAN-11957) Create permission to display options
  config/permissions.yml
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig
Labels: type:story
