Repository demos-europe/demosplan-core, pull requests merged in 2024-02, with the labels that each got.

#2664 chore (refs T34332): Add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/proceduremenu_statements.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/public_statement.html.twig
Labels: review:frontend, quick-win, type:enhancement

#2675 bug(refs T36258): fix slicing tagging
  client/js/store/procedure/SplitStatementStore.js
  client/js/store/procedure/storeHelpers/SplitStatementStore/HTMLIdxToProsemirrorIdx.js
Labels: type:bug, review:frontend

#2680 f adjust composer.lock
  composer.lock
Labels: review:backend

#2668 Adapt xhr call to changed lib
  client/js/bundles/procedure/publicIndexSimpleList.js
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
Labels: type:bug, review:frontend

#2676 ref(T36269): remove the insert and delete functions from the editor
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: review:frontend, quick-win

#2652 fix(T36196): procedure phase with write permission should have auto-switch activated by default
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
Labels: review:frontend

#2641 fix(T36199): display notification when a network error occurs
  client/js/components/map/admin/LayerSettings.vue
Labels: review:frontend, quick-win

#2665 fix(refs T36189): show "planungsanlass"
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  client/js/lib/procedure/CreateProcedure.js
Labels: type:bug, review:frontend

#2556 symfony recipe update framework
  .env
  .gitignore
  config/packages/cache.yaml
  config/packages/framework.yaml
  config/packages/test/framework.yaml
  config/preload.php
  config/routes/framework.yaml
  demosplan/DemosPlanCoreBundle/Application/FrontController.php
  symfony.lock
  tests/backend/core-application/app/config/config_test.yml
Labels: review:backend

#2648 bug(refs T36230): check response api call
  client/js/components/news/DpNewsAdminList.vue
Labels: type:bug, review:frontend

#2557 symfony recipe update monolog
  config/packages/monolog.yaml
  config/packages/prod/deprecations.yaml
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilderWithZipSupport.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementSpreadsheetImporter.php
  symfony.lock
Labels: review:backend

#2558 symfony recipe update rest
  config/packages/sentry.yaml
  phpunit.xml
  symfony.lock
Labels: review:backend

#2559 chore: update deprecated user method
  demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentDashboardAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SecurityUserProvider.php
  tests/backend/core/User/Functional/UserHandlerTest.php
  tests/backend/core/User/Functional/UserServiceTest.php
Labels: review:backend, quick-win

#2667 CoreRepository extended needed
  demosplan/DemosPlanCoreBundle/Repository/NewsRepository.php
Labels: review:backend

#2673 feat(refs T36187): errors admin user
  client/js/components/user/DpUserListExtended.vue
  client/js/components/user/DpUserListExtendedItem.vue
  config/permissions.yml
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_user.html.twig
Labels: type:bug, review:frontend, review:backend

#2681 feature (ref 36289): Add Errors to Orga delete
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
Labels: type:bug, review:backend

#2662 fix (refs T30474): reduce inconsistent code duplication
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/Logic/OwnsProcedureConditionFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/ProcedureAccessEvaluator.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/NonAuthorizedAssignRemover.php
Labels: type:bug, review:backend

#2684 F t29878 disconnect addon data storage
  demosplan/DemosPlanCoreBundle/Addon/AddonResolveTargetEntity.php
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
Labels: review:backend

#2692 feat (refs T29878): Update demosplan-addon version
  composer.lock
Labels: review:backend

#2699 feat (refs T29878): Add doctrine event so that when entityFlush happe…
  demosplan/DemosPlanCoreBundle/Addon/AddonResolveTargetEntity.php
Labels: review:backend

#2621 Fix(refs:T36142): no column title shown
  client/js/components/user/DpMasterToebList.vue
Labels: type:bug, review:frontend

#2670 feature (ref 26150): Fix issue with cascade persist in FileContainer …
  demosplan/DemosPlanCoreBundle/Entity/FileContainer.php
Labels: type:bug, review:backend

#2694 bug(refs T36341): Show title for icon only if there is an icon
  client/js/components/statement/assessmentTable/ItemRow.vue
Labels: type:bug, review:frontend, quick-win

#2700 fix error while adding new steps : configure cascade persist this ass…
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
Labels: type:bug, review:backend, quick-win

#2702 chore: Update demosplan-ui to v0.3.6
  package.json
  yarn.lock
Labels: review:frontend

#2693 feat (refs T36297): Keep formatting on export original-STN as already…
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Grouping/EntityGrouper.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ExportService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: type:bug, review:backend

#2705 feature (ref 36294): find api user from list and unset that
  demosplan/DemosPlanCoreBundle/ResourceTypes/AdministratableUserResourceType.php
Labels: type:bug, review:backend

#2723 f T36454 convert paramater to string
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Labels: review:backend, quick-win

#2724 fix (refs T36452): adjust ResourceType::getProperties return type to also allow ResourceConfigBuilder
  demosplan/DemosPlanCoreBundle/ResourceTypes/SignLanguageOverviewVideoResourceType.php
Labels: type:bug, review:backend, quick-win

#2719 feature (ref 34504): adjustment name of resource type
  client/js/components/user/CustomerSettings/CustomerSettings.vue
Labels: review:frontend, support:backend, type:story

#2730 fix (refs T36342): disable element.assign when negative report is selected
  client/js/components/statement/publicStatementModal/StatementModal.vue
Labels: type:bug, quick-win

#2732 feature (ref 36461): fix wrong naming for function in resourcetype
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerLoginSupportContactResourceType.php
Labels: type:bug, review:backend

#2729 refs T36463: Fix login
  demosplan/DemosPlanCoreBundle/Entity/User/SecurityUser.php
  demosplan/DemosPlanCoreBundle/Logic/User/OrgaService.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserService.php
  tests/backend/core/DemosPlanCoreBundle/Entity/User/SecurityUserTest.php
Labels: type:bug, review:backend

#2734 f T36467 Error when deleting other submitters of the same statement
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Labels: type:bug, review:backend, quick-win

#2721 feature (ref 34724): create new permission to can manage note, that b…
  config/permissions.yml
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/new_public_participation_statement_confirm_content.html.twig
Labels: type:bug, review:frontend, review:backend

#2718 feature (ref 32892): set permission to required contact person
  config/permissions.yml
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:backend, support:frontend, type:story

#2735 f T36440 Additional submitters should only be displayed if they have been specified
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Labels: type:bug, review:backend, quick-win

#2725 bug (ref T25450) Adjust label for a neutral gender expression
  translations/messages+intl-icu.de.yml
Labels: review:backend

#2733 bug(refs T36452): Fill customer with currentdata props
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new.html.twig
Labels: type:bug, review:frontend

#2740 fix(T36474): improve error validation on the administration page
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, quick-win

#2736 Fix(T35464): dp-support layout issue
  client/js/components/support/DpSupport.vue
Labels: review:frontend, quick-win

#2737 fix(T36473): add an indicator for the mandatory field
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, quick-win

#2748 bug(refs T36509): Remove empty comment which is breaking the site
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: type:bug, review:frontend, quick-win

#2750 fix(T34161): tiptap h3/h4 spacing issue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
Labels: review:frontend, quick-win

#2749 Fix(T35058): long emails break the layout
  client/js/components/support/DpSupportCard.vue
Labels: quick-win

#2752 chore (refs T33654): use variable to portal in trans key
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, review:backend, quick-win

#2757 chore (refs T36516): Fix duplicate Hooks.
  config/menus.yml
Labels: type:bug, review:frontend, quick-win, type:enhancement

#2751 chore: simplify logger
  config/packages/monolog.yaml
  config/packages/nelmio_security.yaml
  config/parameters_default.yml
  config/services.yml
Labels: review:backend

#2767 chore: fix bc break in fractal 0.20
  demosplan/DemosPlanCoreBundle/Transformers/AssessmentTable/StatementBulkEditTransformer.php
  demosplan/DemosPlanCoreBundle/Transformers/Document/DocumentDashboardTransformer.php
  demosplan/DemosPlanCoreBundle/Transformers/FaqCategoryTransformer.php
  demosplan/DemosPlanCoreBundle/Transformers/Filters/AggregationFilterGroupTransformer.php
  demosplan/DemosPlanCoreBundle/Transformers/Filters/AggregationFilterTypeTransformer.php
  demosplan/DemosPlanCoreBundle/Transformers/HistoryDayTransformer.php
Labels: type:bug, review:backend

#2759 B t17533 adjust print in blueprints using basemap
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/02/Version20240220142305.php
  tests/backend/core/Core/Functional/DynamicTransformerTest.php
Labels: review:backend

#2683 chore (refs T34245): Add missing Hooks/Selectors.
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue
Labels: review:frontend, quick-win, type:enhancement

#2677 chore (refs T34249): Add missing Hooks/Selectors.
  client/js/components/statement/listStatements/ListStatements.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
Labels: review:frontend, quick-win, type:enhancement

#2779 bug(refs T25438): Remove padding
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
Labels: type:bug, review:frontend, quick-win

#2783 feature (ref 36557): fix the address of include twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
Labels: type:bug, review:frontend

#2771 feature (ref 34305): use break class to handle big insert data
  client/js/components/support/DpSupportCard.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
Labels: type:bug, review:frontend

#2784 feature (ref 35058): adjustment long data issue in release
  client/js/components/support/DpSupportCard.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
Labels: type:bug, review:frontend

#2780 bug(refs T23768): Disable opacity for base map
  client/js/lib/map/GisLayerEdit.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig
Labels: type:bug, review:frontend

#2778 fix(refs T36457): prevent corrupt layers from breaking draw fn
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#2747 Fix(T34304): adjust layout on the 'Stellungnahme mitzeichnen' page
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/new_public_participation_statement_vote_content.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/new_public_participation_statement_confirm_entry.html.twig
Labels: review:frontend

#2782 fix(refs T36396): use the correct access for the dates
  client/js/components/procedure/admin/AdministrationProceduresList.vue
Labels: type:bug, review:frontend

#2781 fix(refs T36055): correctly fallback to defaultMapExtent
  client/js/components/map/map/DpOlMap.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
Labels: type:bug, review:frontend

#2787 fix (refs T15681): Only show legend of layer if the layer is enabled and contains a legend file
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
Labels: type:bug, review:frontend, quick-win

#2722 chore: trim Proxy params
  demosplan/DemosPlanCoreBundle/Logic/HttpCall.php
  tests/backend/core/Core/Functional/HttpCallTest.php
Labels: review:backend

#2788 fix (refs T30474): Use interfaces instead of entities as method parameters in core-entities implementing demosplan-addon interfaces
  composer.lock
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
Labels: type:bug, review:backend

#2791 Allow for opting out of default filter of procedures on public_index
  client/js/bundles/procedure/publicIndexNoMap.js
Labels: type:bug, review:frontend

#2790 feature (ref 36387): set master toeb list changes link
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig
Labels: type:bug, review:frontend

#2795 Fix(refs:36153): use the correct access for the dates (#2620)
  client/js/components/procedure/admin/AdministrationProceduresList.vue
Labels: type:bug, review:frontend

#2794 bug (ref T36592) Adjust "element" in include for API request so EDT can understand and match the entity
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php
Labels: review:frontend, review:backend

#2797 bug (ref T36592) Adjust ToOneRelationshipConfigBuilderInterface for element
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php
Labels: review:backend

#2799 bug (ref T36592) Set ToOneRelationshipConfigBuilderInterface to eleme…
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php
Labels: review:backend

#2796 feature (ref 36600): set some missed columns
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: type:bug, review:backend

#2789 Check all write phases in AutoSwitchProcedurePhaseForm
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: type:bug, review:frontend
