Repository demos-europe/demosplan-core, pull requests merged in 2024-11, with the labels that each got.

#3928 fix(refs dplan-12776): Remove Email Boilerplates in Customer Settings Update mail
  client/js/bundles/user/customersettingsmail.js
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanCustomerController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/customer_settings_update_mail.html.twig
Labels: type:bug, review:frontend, type:enhancement

#3932 fix(refs f_BEAA2-10) update to demosplan-addon v0.43
  composer.json
  composer.lock
  config/services.yml
Labels: review:backend

#3902 F dplan 12722 add resource type stn vote
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/ResourceTypeStore.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementVoteResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementVoteResourceType.php
Labels: review:backend

#3935 fix(refs dplan-12775): Move customerBranding logic to Store
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/BrandingResourceType.php
Labels: review:frontend, review:backend

#3933 fix(refs dplan-12770): Don't transform store-state (publicStatement)
  client/js/components/statement/publicStatementModal/StatementModal.vue
Labels: type:bug, review:frontend, quick-win, type:enhancement

#3923 fix(refs dplan-12776): Make TS-Components mount
  client/js/InitVue.js
Labels: type:bug, quick-win, type:enhancement

#3916 fix(refs dplan-12767): Make create statement work again
  client/js/components/assessmenttable/DpNewStatement.vue
  client/js/components/button/BackToTopButton.vue
  client/js/store/statement/Statement.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: type:bug, review:frontend, type:enhancement

#3936 chore (refs AB#17164): remove unused unmaintained symfony/inflector
  composer.json
  composer.lock
  symfony.lock
Labels: review:backend, quick-win

#3927 chore: use strict and secure session cookie
  config/packages/framework.yaml
Labels: review:backend, quick-win

#3925 chore: remove deprecated xss_protection
  config/packages/nelmio_security.yaml
Labels: review:backend, quick-win

#3907 F dplan 3217 add documents paragraph stn
  demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/PlaningDocumentCategoryResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ParagraphVersionResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryDetailsResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementAttachmentResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Labels: review:backend, type:story

#3949 Add backslash to create new line
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
Labels: type:bug, review:backend

#3833 chore refs(DPLAN-12660): massively improve performance in docx export
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/ValueObject/Statement/StatementViewed.php
Labels: review:backend

#3950 fix(refs DPLAN-12775): Fix saving style without logo
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/BrandingResourceType.php
Labels: type:bug, review:frontend

#3959 chore: switch to new ProcedureDeleter
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
Labels: review:backend, quick-win

#3961 fix(refs DPLAN-12814): Get Projection per Layer in Public Detail
  client/js/store/map/Layers.js
Labels: type:bug, review:frontend

#3964 chore: fix pagerfanta pagination after major update
  demosplan/DemosPlanCoreBundle/Utilities/Pagination/DemosPlanArrayAdapter.php
Labels: review:backend

#3962 fix(refs DPLAN-12699): Don't request Municipalities if not enabled
  client/js/store/statement/Statement.js
Labels: type:bug, review:frontend

#3904 fix(refs f_BEAA2-10_handle proxy relation problem regarding currentSlugs
  config/services.yml
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostProcedureUpdatedEvent.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
Labels: review:backend

#3980 bug(refs DPLAN-1967): Add min height (3793)
  client/js/components/procedure/SegmentsList/SegmentsList.vue
Labels: review:frontend

#3971 feat (DPLAN-12730): show original attachment link
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
Labels: review:frontend, review:backend, quick-win

#3982 bug(refs DPLAN-12817): fix icons for map layers
  client/js/components/map/admin/AdminLayerListItem.vue
Labels: review:frontend

#3983 B dplan 12817 fix icons in plan drawing view
  client/js/components/map/admin/AdminLayerListItem.vue
Labels: review:frontend

#3968 feat (DPLAN-12809): wrap feature in permission
  config/permissions.yml
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: type:bug, review:backend

#3963 feat (refs DPLAN-12824): Don't delete customer master template
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureListController.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend

#3938 Revert "F dplan 12618 check if one layer al least is available (3905)"
  client/js/components/map/admin/AdminLayerList.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#3993 B dplan 12733 fix entity manager closed
  demosplan/DemosPlanCoreBundle/Entity/Document/Paragraph.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementFileHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementAnonymizeService.php
  demosplan/DemosPlanCoreBundle/Repository/DraftStatementFileRepository.php
Labels: type:bug, review:backend

#3998 fix(refs f_BEAA2-10) use an existing trans key.
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiResourceTypeService.php
Labels: review:backend, quick-win

#3986 fix(refs f_BEAA2-10) save copyright and alt texts for
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureToLegacyConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:backend

#4003 getEmailAuthCode can to return null
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  tests/backend/core/DemosPlanCoreBundle/Entity/User/SecurityUserTest.php
Labels: type:bug, review:backend

#3992 feat(refs DPLAN-12526): add statement quicksave button after ocr text recognition
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4009 fix(refs DPLAN-12690): fix alignment of help icons
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, quick-win

#3984 fix(refs dplan-12823): Reset orga form only for editable fields
  client/js/bundles/user/editOrga.js
  client/js/components/user/orgaDataEntry/OrganisationDataForm.vue
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrgaController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/edit_orga.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_data_entry.html.twig
Labels: type:bug, review:frontend

#3931 chore (refs AB#20738): use phpspreadsheet directly
  composer.json
  composer.lock
  config/bundles.php
  config/services.yml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanMasterToebController.php
  demosplan/DemosPlanCoreBundle/Logic/SimpleSpreadsheetService.php
  symfony.lock
Labels: review:backend

#4025 build: bump demosplan-ui to v.0.3.38
  package.json
  yarn.lock
Labels: review:frontend

#4023 fix(refs DPLAN-12746): use new tooltipOptions prop
  client/js/components/statement/DpBoilerPlate.vue
Labels: type:bug, review:frontend

#4027 fix(refs DPLAN-3217): re-add div for consistent spacing
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaLocationAndDocumentReference.vue
Labels: review:frontend

#4028 F dplan 12526 add statement quicksave button after ocr text recognition
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4033 build: bump @uppy/core to 4.2.3, @uppy/drag-drop to 4.0.4
  package.json
  yarn.lock
Labels: review:frontend, dependencies:yarn

#4041 feat(refs DPLAN-12526): pick changes for release
  client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4002 chore: add symfony packages to dependabot group
  .github/dependabot.yml
Labels: devops, review:backend, quick-win

#4046 feat (refs DPLAN-12917): show statement in assessmenttable again
  client/js/store/statement/Statement.js
Labels: type:bug, review:frontend, support:frontend

#3920 chore: remove unused deployment leftovers
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
  demosplan/DemosPlanCoreBundle/Command/DeployCommand.php
  demosplan/DemosPlanCoreBundle/Command/UpdateCommand.php
  demosplan/DemosPlanCoreBundle/DependencyInjection/Compiler/DeploymentStrategyLoaderPass.php
  demosplan/DemosPlanCoreBundle/DependencyInjection/ServiceTagAutoconfigurator.php
  demosplan/DemosPlanCoreBundle/Logic/Deployment/Strategy.php
  demosplan/DemosPlanCoreBundle/Logic/Deployment/StrategyInterface.php
  demosplan/DemosPlanCoreBundle/Logic/Deployment/StrategyLoader.php
Labels: review:backend

#3921 chore: any functional user needs a default orga
  demosplan/DemosPlanCoreBundle/Entity/User/AiApiUser.php
  demosplan/DemosPlanCoreBundle/Entity/User/AnonymousUser.php
  demosplan/DemosPlanCoreBundle/Entity/User/FunctionalUser.php
Labels: review:backend, quick-win

#3930 chore (refs AB#20738): remove patchwork/utf8
  composer.json
  composer.lock
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
  demosplan/DemosPlanCoreBundle/Logic/CoreHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ExportService.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserMapperDataportGateway.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserMapperDataportGatewayHH.php
  demosplan/DemosPlanCoreBundle/Logic/ZipExportService.php
  demosplan/DemosPlanCoreBundle/Response/BinaryFileDownload.php
  symfony.lock
Labels: review:backend

#4045 feat(refs DPLAN-12916): add function to redirect back to import center
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
Labels: review:frontend

#4063 f-DPLAN-12816-retain-layers-preselection-after-saving-or-updating-layers
  demosplan/DemosPlanCoreBundle/Logic/Map/MapHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Map/MapService.php
  demosplan/DemosPlanCoreBundle/Repository/MapRepository.php
Labels: type:bug, review:backend

#4072 feat(refs DPLAN-12460): add style to always display flyout properly
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_flyout.scss
Labels: review:frontend

#4074 chore: bump demosplan-ui to 0.3.40
  package.json
  yarn.lock
Labels: review:frontend

#4049 chore: build addon frontend only when it exists
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend, quick-win

#4054 chore: only load aws s3 sdk api
  composer.json
Labels: review:backend

#4061 chore: Ratelimit api requests
  config/packages/rate_limiter.yaml
  demosplan/DemosPlanCoreBundle/EventSubscriber/RatelimitRequestSubscriber.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/AbstractStatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  tests/backend/core/Core/Functional/RatelimitRequestSubscriberTest.php
Labels: review:backend
