Repository demos-europe/demosplan-core, pull requests merged in 2024-07, with the labels that each got.

#3345 feature (ref 11959): use Permissin for map options
  client/js/components/map/admin/AdminLayerList.vue
Labels: type:bug

#3351 feat(refs DPLAN-11953, DPLAN-4020): Fix Header Col Position for AdminLayerList
  client/js/components/map/admin/AdminLayerList.vue
Labels: type:bug, review:frontend, quick-win

#3352 bug(refs DPLAN-11849): Set boundingbox only if it exists
  client/js/components/map/map/DpOlMap.vue
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
Labels: type:bug, review:frontend

#3339 feat (DPLAN-3268): code inspection fixes
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Labels: review:backend

#3347 feature (ref 11961): allow to delete Gislayer
  client/js/store/map/Layers.js
  demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerCategoryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php
Labels: type:bug, review:frontend, review:backend

#3355 chore: fix yarn 4 deprecations in jenkins pipeline
  Jenkinsfile
Labels: devops

#3357 chore: bump demosplan-addon version
  composer.json
  composer.lock
Labels: review:backend, quick-win

#3356 feat(refs DPLAN-4020): Controll which Layer Options are visible and …
  client/js/components/map/admin/AdminLayerList.vue
  client/js/components/map/admin/AdminLayerListItem.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig
Labels: review:frontend, review:backend

#3324 chore (refs DPLAN-11531): Standardizing the names of the Hooks for St…
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
Labels: review:frontend, quick-win, type:enhancement

#3373 chore (refs DPLAN-11745): Add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_new.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3374 chore (refs DPLAN-12012): Standardizing the names of the Hooks for ne…
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
Labels: review:frontend, quick-win, type:enhancement

#3378 chore (refs DPLAN-12005): add missing Hook.
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend, quick-win, type:enhancement

#3375 chore (refs DPLAN-11503): Edit Hook naming.
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list_entry.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3379 fix: Interpret String as String
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/alternative_login.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/citizen_register_form.html.twig
Labels: type:bug

#3371 chore (refs DPLAN-12006): copy the FAQ from one customer to another
  demosplan/DemosPlanCoreBundle/Command/Data/CopyFaqCommand.php
Labels: review:backend

#3370 chore (refs DPLAN-12006): register default users for new customer
  demosplan/DemosPlanCoreBundle/Command/Data/GenerateCustomerCommand.php
Labels: review:backend

#3358 chore: fix tests that fail the build
  demosplan/DemosPlanCoreBundle/Services/Queries/SqlQueriesService.php
  tests/backend/core/Core/Functional/DynamicTransformerTest.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: review:backend

#3393 fix (refs DPLAN-12022): use new permission to read technical support entry
  client/js/components/support/DpSupport.vue
  config/permissions.yml
Labels: review:frontend, review:backend

#3398 fix (refs DPLAN-11968): grant planning_agency invitation permission to fpa-only
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: review:backend

#3404 chore (refs DPLAN-12027): standardizing hooks names between projects.
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3406 chore (refs DPLAN-12028): Add missing Hooks/Selectors.
  client/js/components/procedure/admin/AdministrationPlaces.vue
Labels: quick-win, type:enhancement

#3421 fix (refs DPLAN-12068): add interface to event dispatcher
  demosplan/DemosPlanCoreBundle/Controller/Segment/DraftsInfoApiController.php
Labels: review:backend

#3423 fix (refs DPLAN-12068): add interface to event dispatcher.
  demosplan/DemosPlanCoreBundle/Controller/Segment/DraftsInfoApiController.php
Labels: review:backend

#3422 fix (refs DPLAN-12068): add interface to event dispatcher.
  demosplan/DemosPlanCoreBundle/Controller/Segment/DraftsInfoApiController.php
Labels: review:backend

#3418 feat (DPLAN-3796) Fix test as this event was removed from folder, see…
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/StatementFragmentFactory.php
  tests/backend/base/JsonApiTest.php
  tests/backend/core/Core/Functional/DynamicTransformerTest.php
  tests/backend/core/Core/Functional/EntityFetcherTest.php
  tests/backend/core/Core/Functional/EventFinderTest.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
  tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/RpcBulkEditorTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/TwigToolsExtensionTest.php
  tests/backend/core/Forum/Functional/ForumDevelopmentTest.php
  tests/backend/core/JsonApi/Functional/PlanningDocumentCategoryResourceTypeTest.php
  tests/backend/core/JsonApi/Functional/ProcedureNewsResourceTypeTest.php
  tests/backend/core/Procedure/Functional/ProcedureServiceTest.php
  tests/backend/core/Report/Functional/ReportMessageConverterTest.php
  tests/backend/core/Statement/Functional/StatementDeleterTest.php
  tests/backend/core/Statement/Functional/StatementHandlerTest.php
  tests/backend/core/Statement/Functional/TagServiceTest.php
  tests/backend/core/User/Functional/MasterToebServiceTest.php
  tests/frontend/unit/changeUrlForPager.test.js
Labels: review:backend

#3415 chore (refs DPLAN-12028, DPLAN-12029): Add missing Hooks.
  client/js/components/procedure/admin/AdministrationPlaces.vue
Labels: review:frontend, quick-win, type:enhancement

#3416 chore (refs DPLAN-12078): add missing Hook.
  client/js/components/faq/DpFaqCategoryItem.vue
  client/js/components/faq/DpFaqItem.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanFaq/faq_admin_category_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanFaq/faq_admin_edit.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3417 feature (ref DPLAN163):
  client/js/components/procedure/charts/DpStatementSegmentsStatusCharts.vue
  client/js/components/procedure/charts/ProcedureCharts.js
  client/js/lib/procedure/charts/DonutChart.js
  demosplan/DemosPlanCoreBundle/Controller/Procedure/ProcedureStatisticsRpcController.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/ViewStatementStatus.php
  demosplan/DemosPlanCoreBundle/Logic/ProcedureStatisticsService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  tests/backend/core/Core/Functional/ProcedureStatisticsServiceTest.php
  tests/backend/core/Statement/Functional/StatementServiceTest.php
Labels: review:frontend, review:backend, type:story

#3420 fix(refs DPLAN-11964): Set empty array as empty Object for Territory
  client/js/components/map/admin/MapAdmin.vue
Labels: type:bug, review:frontend

#3444 Fix tag service tests
  tests/backend/core/Statement/Functional/TagServiceTest.php
Labels: review:backend

#3400 fix(refs dplan-12021): Pass Opacity to Segments Map
  client/js/components/map/map/DpOlMap.vue
  client/js/components/map/map/DpOlMapLayer.vue
  client/js/store/map/ProcedureMapSettings.js
Labels: type:bug, review:frontend

#3399 fix(refs dplan-12020): Prevent Layer Url from doubling the Service param
  client/js/components/map/map/DpOlMapLayer.vue
Labels: type:bug, review:frontend

#3430 feat (DPLAN-3796) Make EntityFetcherTest run
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/StatementMetaFactory.php
  tests/backend/core/Core/Functional/EntityFetcherTest.php
Labels: review:backend

#3395 feat (DPLAN-3796) Adjust filename
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/StatementMetaFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentExporterFileNameGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  tests/backend/core/Statement/Functional/SegmentExporterFileNameGeneratorTest.php
  tests/backend/core/Statement/Functional/SegmentsByStatementsExporterTest.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#3319 chore (refs DPLAN-3485): Add missing Hooks/Selectors.
  client/js/components/procedure/SegmentsList/CustomSearch.vue
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
Labels: review:frontend, quick-win, type:enhancement

#3445 Fix test core permissions
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: review:backend

#3338 chore (refs DPLAN-11820): Add missing Hooks/Selectors.
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
  client/js/components/user/CustomerSettings/CustomerSettingsMap.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSection.vue
Labels: review:frontend, quick-win, type:enhancement

#3448 feat(refs DPLAN-3796): Add input for file name in exports
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/StatementExportModal.vue
  client/js/components/statement/listStatements/ListStatements.vue
  tests/frontend/unit/StatementExportModal.spec.js
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#3394 feat(refs DPLAN-11981): Enable images for segments
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/shared/ImageModal.vue
  client/js/components/statement/StatementExportModal.vue
  client/js/components/statement/assessmentTable/EditableText.vue
  demosplan/DemosPlanCoreBundle/Logic/ImageLinkConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
  tests/backend/core/Statement/Functional/ImageLinkConverterTest.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story

#3368 fix(refs plan-11960): Make sort layers work again
  client/js/components/map/admin/AdminLayerList.vue
  client/js/components/map/admin/AdminLayerListItem.vue
  client/js/store/map/Layers.js
  demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
  demosplan/DemosPlanCoreBundle/Logic/KeycloakUserDataMapper.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerCategoryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/GisLayerResourceType.php
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_sortablelist.scss
  demosplan/DemosPlanCoreBundle/ValueObject/KeycloakUserData.php
  tests/frontend/unit/DpLayerLegend.spec.js
  tests/frontend/unit/SearchModal.spec.js
  tests/frontend/unit/StatementExportModal.spec.js
  tests/frontend/unit/__mocks__/MapLayer.mock.js
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#3433 Feat(DPLAN-11858): splitStatement: adjust design for sidebar
  client/js/components/statement/splitStatement/AssignedTags.vue
  client/js/components/statement/splitStatement/FloatingContextButton.vue
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/store/statement/SplitStatementStore.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitstatement.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_footer.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#3402 F dplan163 statement status
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/Shared/StatusBadge.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/procedure/admin/AdministrationPlaces.vue
  client/js/components/procedure/charts/DpStatementSegmentsStatusCharts.vue
  client/js/components/procedure/charts/ProcedureCharts.js
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/lib/procedure/charts/DonutChart.js
  composer.json
  composer.lock
  demosplan/DemosPlanCoreBundle/Controller/Procedure/ProcedureStatisticsRpcController.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/07/Version20240716115746.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Segment.php
  demosplan/DemosPlanCoreBundle/Entity/Workflow/Place.php
  demosplan/DemosPlanCoreBundle/Logic/ProcedureStatisticsService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlaceResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  tests/backend/core/Core/Functional/ProcedureStatisticsServiceTest.php
  tests/backend/core/Core/Unit/Faker/Provider/ApproximateLengthTextTest.php
  tests/backend/core/News/Functional/ProcedureNewsServiceTest.php
  tests/backend/core/Procedure/Functional/ProcedureServiceTest.php
  tests/backend/core/Statement/Functional/StatementServiceTest.php
  tests/frontend/unit/StatusBadge.spec.js
Labels: review:frontend, review:backend, type:story

#3426 feature (ref DPLAN2023): manage procedure export
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ExportService.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: type:bug, review:backend

#3466 chore: Update demosplan-ui to v0.3.21
  package.json
  yarn.lock
Labels: review:frontend

#3429 chore (refs DPLAN-12089): add missing Hook.
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImport.vue
  client/js/components/procedure/AdministrationImport/ParticipationImport/ParticipationImport.vue
Labels: review:frontend, quick-win, type:enhancement

#3461 Fix Statement Deleter tests
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/CountyFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/MunicipalityFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/PriorityAreaFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/StatementAttributeFactory.php
  tests/backend/core/Statement/Functional/StatementDeleterTest.php
Labels: review:backend

#3432 fix(refs DPLAN-11488): Make departments updateable again
  client/js/components/user/DpUserList/DpUserFormFields.vue
Labels: type:bug, review:frontend

#3405 fix(refs DPLAN-11803): properly calculate inParticipation phase
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
Labels: type:bug, review:frontend

#3476 chor (refs DPLAN-12118): Add missing Hooks/Selectors.
  client/js/components/statement/StatementExportModal.vue
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/DpExportModal.vue
Labels: review:frontend, quick-win, type:enhancement

#3470 fix(refs DPLAN-11449): Print warning for short segments
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/lib/prosemirror/commands.js
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#3431 fix(refs DPLAN-12009): Fix file copies on STN copy to different procedure
  demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementMover.php
  demosplan/DemosPlanCoreBundle/Logic/StatementAttachmentService.php
  demosplan/DemosPlanCoreBundle/Repository/FileRepository.php
  demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php
Labels: type:bug, review:backend

#3474 chore: use MessageBagInterface in DI to show all messages
  demosplan/DemosPlanCoreBundle/Logic/Document/DocumentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Document/ElementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Forum/ForumHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Help/HelpHandler.php
  demosplan/DemosPlanCoreBundle/Logic/News/GlobalNewsHandler.php
  demosplan/DemosPlanCoreBundle/Logic/News/NewsHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureProposalHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementAnonymizeHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFilterHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/CustomerHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/OrgaHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/PublicAffairsAgentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/RoleHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
  tests/backend/core/Core/Functional/MessageBagTest.php
  tests/backend/core/Core/Unit/Handler/CoreHandlerTest.php
Labels: type:bug, review:backend

#3408 fix(refs DPLAN-11488): Prevent error on unset departments
  client/js/components/user/DpUserList/DpUserFormFields.vue
Labels: type:bug, review:frontend

#3478 bug (refs DPLAN-1916): show warning
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
Labels: type:bug, review:frontend

#3477 fix(refs DPLAN-941): Adjust Filter to find names with Blanks
  client/js/components/user/DpUserList/DpUserList.vue
Labels: type:bug, review:frontend

#3481 refactoring: some refactorings for StatementExportModal
  client/js/components/statement/StatementExportModal.vue
  tests/frontend/unit/StatementExportModal.spec.js
Labels: review:frontend, type:enhancement

#3475 load user list by orga admin role
  client/js/components/user/DpUserList/DpUserFormFields.vue
  client/js/components/user/DpUserList/DpUserList.vue
  client/js/store/user/UserFormFields.js
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaStatusInCustomerResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaTypeResourceType.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: type:bug, review:frontend, review:backend

#3471 feat (DPLAN-3796) Fix bulk segement editor test
  tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/RpcBulkEditorTest.php
  tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/SegmentBulkEditorServiceTest.php
Labels: review:backend

#3483 feat (DPLAN-11982): images in segments export
  demosplan/DemosPlanCoreBundle/Logic/ImageLinkConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/ImageManager.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/Utils/HtmlHelper.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  demosplan/DemosPlanCoreBundle/ValueObject/SegmentExport/ConvertedSegment.php
  demosplan/DemosPlanCoreBundle/ValueObject/SegmentExport/ImageReference.php
  tests/backend/core/SegmentExport/HtmlHelperTest.php
  tests/backend/core/Statement/Functional/ImageLinkConverterTest.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#3487 fix (DPLAN-12156): fix path cannot be empty
  demosplan/DemosPlanCoreBundle/Logic/ImageLinkConverter.php
  tests/backend/core/Statement/Functional/ImageLinkConverterTest.php
Labels: type:bug, review:backend

#3488 feat(refs DPLAN-12088): Delay before trying to set the marker bounds
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
Labels: type:bug, review:frontend

#3492 chor (refs DPLAN-11743): Add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_unregistered_publicagency_list.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3495 fix(refs dplan-12026): Prevent undefined
  client/js/lib/map/GisLayerEdit.js
Labels: type:bug, review:frontend, quick-win

#3502 fix (DPLAN-12156): Add no page break if no images are present.
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/ImageManager.php
Labels: type:bug, review:backend, quick-win

#3504 chore: Update demosplan-ui to v0.3.24
  package.json
  yarn.lock
Labels: review:frontend

#3496 bug(refs DPLAN-12154): Fix segmentation buttons
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/statement/splitStatement/CardPaneCard.vue
Labels: type:bug, review:frontend

#3493 feat(refs dplan-163): Add hints for solved places new
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/admin/AdministrationPlaces.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, type:enhancement, type:story

#3503 fix(refs DPLAN-12009): Apply fix for regio as well since STNs can be copied/moved here as well
  demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementMover.php
  demosplan/DemosPlanCoreBundle/Logic/StatementAttachmentService.php
  demosplan/DemosPlanCoreBundle/Repository/FileRepository.php
  demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php
Labels: type:bug, review:backend

#3516 bug(refs DPLAN-12159): Add class to prosemirror schema
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/statement/splitStatement/SegmentationEditor.vue
Labels: type:bug, review:frontend, urgent

#3517 fix (DPLAN-12164 & DPLAN-12165): fix image links in export
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/Utils/HtmlHelper.php
  tests/backend/core/SegmentExport/HtmlHelperTest.php
Labels: review:backend, quick-win

#3518 feat (DPLAN-11982) use correct file path
  demosplan/DemosPlanCoreBundle/Logic/ImageLinkConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/Utils/HtmlHelper.php
  demosplan/DemosPlanCoreBundle/ValueObject/SegmentExport/ImageReference.php
  tests/backend/core/Statement/Functional/ImageLinkConverterTest.php
Labels: type:bug, review:backend
