Repository demos-europe/demosplan-core, pull requests merged in 2024-09, with the labels that each got.

#3534 F 2024.10 2024.11
  composer.json
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Document/SingleDocumentHandler.php
  demosplan/DemosPlanCoreBundle/Repository/ParagraphRepository.php
Labels: review:backend, type:story

#3616 feat(refs DPLAN-12340 AB#18958): Add cypress selectors
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/edit_orga.html.twig
Labels: review:frontend, type:story

#3579 chore (refs f_DPLAN-12067_add_missing_hooks): Add missing Hooks/Selec…
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/lib/prosemirror/utilities.js
Labels: review:frontend, quick-win, type:enhancement

#3622 bug(refs DPLAN-1879): Change aria live to assertive
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
  client/js/components/procedure/publicindex/drawer/Drawer.vue
Labels: type:bug, review:frontend

#3623 bug(refs DPLAN-1953): Set full width to true
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/list_subscriptions.html.twig
Labels: type:bug, review:frontend

#3615 feat(refs DPLAN-3428): enable videos sign lang
  config/config_dev_container.yml
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#3629 chore: Update demosplan-ui to v0.3.30
  package.json
  yarn.lock
Labels: review:frontend, type:enhancement

#3628 fix (DPLAN-12363) Adjust fields
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/statement_anonymize.html.twig
Labels: type:bug, review:backend

#3604 feature (refs AB#15558): Include the customer in the cockpit url.
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
Labels: review:backend, type:story

#3636 fix(refs DPLAN-12372): Fix UserResourceType access conditions
  demosplan/DemosPlanCoreBundle/ResourceTypes/UserResourceType.php
Labels: review:backend, quick-win

#3632 chore (refs DPLAN-12349): Add missing Hooks.
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSignLanguageVideo.vue
Labels: review:frontend, quick-win, type:enhancement

#3634 bug(refs DPLAN-12379): Add z index to draw feature
  client/js/components/map/map/DpOlMapDrawFeature.vue
Labels: type:bug, review:frontend

#3620 fix(refs DPLAN-12267): add consideration as BoilerplateCategory permission based by default
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Repository/BoilerplateCategoryRepository.php
  demosplan/DemosPlanCoreBundle/Repository/BoilerplateRepository.php
Labels: review:backend

#3645 fix(refs DPLAN-12267): add consideration as BoilerplateCategory permi…
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Repository/BoilerplateCategoryRepository.php
  demosplan/DemosPlanCoreBundle/Repository/BoilerplateRepository.php
Labels: review:backend

#3642 bug(refs DPLAN-1998): Hide fields when empty
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
Labels: type:bug, review:frontend

#3644 chore: Update demosplan-ui to v0.3.31
  package.json
  yarn.lock
Labels: review:frontend, type:enhancement

#3646 feat(refs DPLAN-12322): add permission
  client/js/components/statement/DpStatementAnonymize.vue
Labels: review:frontend, type:story

#3633 Provide command to install automatically all defined project addons
  config/addons.yml
  demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonAutoinstallCommand.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
  demosplan/DemosPlanCoreBundle/Command/CacheClearCommand.php
  demosplan/DemosPlanCoreBundle/DependencyInjection/Compiler/OptionsLoaderPass.php
  demosplan/DemosPlanCoreBundle/DependencyInjection/Configuration/AddonTreeBuilder.php
  tests/backend/core/Core/Functional/Command/AddonAutoinstallCommandTest.php
Labels: review:backend

#3473 chore (refs DPLAN-12133): implement 2fa with totp and email
  composer.json
  composer.lock
  config/bundles.php
  config/packages/scheb_2fa.yaml
  config/packages/security.yaml
  config/permissions.yml
  config/routes/scheb_2fa.yaml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/07/Version20240719092223.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserSecurityHandler.php
  demosplan/DemosPlanCoreBundle/Mailer/TwoFactorMailer.php
  symfony.lock
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/email/2fa_email_auth.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/emptybase.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/2fa.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_profile.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_profile_2fa.html.twig
  tests/backend/core/User/Functional/UserSecurityHandlerTest.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, support:frontend

#3349 remove HslavichOneloginSamlBundle
  client/js/bundles/user/alternativeLogin.js
  client/js/components/user/IdpLoginForm/IdpLoginForm.vue
  client/js/components/user/citizenRegisterForm/CitizenRegisterForm.vue
  composer.json
  config/bundles.php
  config/packages/hslavich_onelogin_saml.yml
  config/packages/security.yaml
  config/parameters_default.yml
  config/routing_core.yml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/LogoutSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/SAML/SamlAttributesParser.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Provider/SamlUserProvider.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/SamlAuthenticationSuccessHandler.php
  demosplan/DemosPlanCoreBundle/Security/User/SamlUserFactory.php
  symfony.lock
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/alternative_login.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/citizen_register_form.html.twig
  tests/backend/core/Core/Functional/SamlAttributesParserTest.php
  tests/backend/core/Core/Functional/SamlUserFactoryTest.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#3649 bug(refs DPLAN-12404): Check for location contacts in institutions
  client/js/components/procedure/admin/DpAddOrganisationList.vue
Labels: type:bug, review:frontend

#3651 F dplan 12400 adjust pdf url
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/public_newsdetail.html.twig
Labels: type:bug, review:frontend

#3662 chore (refs DPLAN-12419): rollback user api 2.0 route
  client/js/store/core/VuexApiRoutes.js
Labels: review:frontend

#3656 B dplan 12406 adjust controller territory field
  client/js/components/map/publicdetail/Map.vue
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Logic/Map/CoordinateJsonConverter.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
  tests/backend/core/Core/Functional/SetTestPermissionsListenerTest.php
Labels: type:bug, review:frontend, review:backend

#3657 chore: reorganize cache & log folders
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
  docker/demosplan-production/Dockerfile
  docker/demosplan-production/nginx.conf.template
  docker/demosplan-production/zzz-dplan.ini
Labels: devops

#3467 chor (refs DPLAN-11884, DPLAN-114): Add Trans-Keys to data-dp-validat…
  client/js/components/user/CustomerSettings/CustomerSettingsLoginSupport.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/send_statement.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3654 fix(refs DPLAN-1877): add warning for empty delete selection of boilerplates
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Labels: review:backend, quick-win

#3655 fix(refs DPLAN-1878): prevent resending a post request on page-reload
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Labels: review:backend, quick-win

#3653 chore: distinct ci container for better jenkins performance
  Jenkinsfile
Labels: devops, review:backend

#3673 chore (refs DPLAN-12424): Add & Edit Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3672 f-DPLAN-12418: show only procedures where Stns have been moved
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
Labels: review:backend

#3675 chore: add var folder to git
  .gitignore
  var/.gitkeep
Labels: review:frontend, devops, review:backend, quick-win

#3663 fix(refs DPLAN-12401): add missing fields to request
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListWrapper.vue
  client/js/store/map/Layers.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
Labels: type:bug, review:frontend

#3670 fix: DPLAN-12009 copy statement with file container
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/RpcBulkCopyStatements.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ReportService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopier.php
Labels: review:backend

#3666 fix(DPLAN-12411): issue by displaying fragments in the STN list
  Jenkinsfile
  client/js/components/statement/assessmentTable/Fragment.vue
Labels: review:frontend, quick-win

#3578 feature (refs AB#18560): add default value newPagePerStn
  config/statement/assessment_export_options.yml
Labels: quick-win

#3668 fix(DPLAN-1875):improve error handling
  demosplan/DemosPlanCoreBundle/Form/ProcedureUiDefinitionFormType.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_procedure_type_edit.html.twig
Labels: review:frontend

#3671 bug(refs DPLAN-12405): Fix merging layers
  client/js/components/map/admin/AdminLayerListItem.vue
Labels: type:bug, review:frontend

#3679 fix(refs DPLAN-12428): cast MaxPerPage Param from string to int
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/ElasticsearchResultCreator.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFragmentService.php
  demosplan/DemosPlanCoreBundle/Traits/DI/ElasticsearchQueryTrait.php
Labels: review:backend

#3611 feature (refs DPLAN-12362): Fix filter assignee
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/store/procedure/SegmentFilter.js
Labels: type:bug, review:frontend, review:backend, support:backend

#3685 f DPLAN-12231 remove doubled note
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig
Labels: review:backend, quick-win

#3688 bug(refs DPLAN-11964): Get Code from Main to make mapFeature Interaction work again
  client/js/components/map/map/DpOlMapDrawFeature.vue
  client/js/components/map/map/DpOlMapEditFeature.vue
  client/js/components/map/map/DpOlMapLayerVector.vue
  package.json
Labels: type:bug, review:frontend

#3695 f DPLAN-12254 revert not necessary changes
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/ConditionFactory/DemosPlanDrupalConditionFactory.php
Labels: review:backend

#3696 fix(refs DPLAN-12410): add link to public detail
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/elements_admin_list.html.twig
Labels: review:frontend

#3692 Ado 18935 numbering of statements docx
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/ExportModal.vue
  config/statement/assessment_export_options.yml
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentExportController.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ExportService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableDocxExporter.php
  tests/backend/core/AssessmentTable/AssessmentHandlerTest.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story

#3674 F dplan 11379 add customer to news
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadGlobalContentData.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/09/Version20240912141620.php
  demosplan/DemosPlanCoreBundle/Entity/Category.php
  demosplan/DemosPlanCoreBundle/Entity/GlobalContent.php
  demosplan/DemosPlanCoreBundle/Logic/ContentService.php
  demosplan/DemosPlanCoreBundle/Repository/ContentRepository.php
Labels: review:backend, type:story

#3689 f delete access control while deleting orga
  demosplan/DemosPlanCoreBundle/Logic/Orga/OrgaDeleter.php
Labels: review:backend

#3684 feat(refs DPLAN-12323, #AB15313): add data protection link to statement modal
  client/js/components/statement/publicStatementModal/StatementModal.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_statement.scss
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#3678 chore: (refs DPLAN-12315): Replace vue draggable with vue sortable in adminlayerList
  .yarnrc.yml
  client/js/components/document/ElementsAdminList.vue
  client/js/components/document/ElementsList.vue
  client/js/components/faq/DpFaqList.vue
  client/js/components/map/admin/AdminLayerListItem.vue
  client/js/components/map/admin/DpAdminLayerList.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/news/DpNewsAdminList.vue
  client/js/components/procedure/admin/AdministrationPlaces.vue
  client/js/store/map/Layers.js
  demosplan/DemosPlanCoreBundle/ResourceTypes/FaqResourceType.php
  package.json
  yarn.lock
Labels: review:frontend, type:enhancement

#3705 fix(refs DPLAN-1917): bump demosplan-addon version to v0.40
  composer.json
  composer.lock
Labels: review:backend

#3708 fix(refs DPLAN-11379) the customer got added to the globalContent (news) and are expected to be present when fetching entities within the tests.
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Logic/ContentService.php
  tests/backend/core/News/Functional/GlobalNewsHandlerTest.php
Labels: review:backend

#3709 fix(refs DPLAN-11379) the customer got added to the globalContent (news) and is expected to be present when fetching entities within the tests.
  demosplan/DemosPlanCoreBundle/Logic/ContentService.php
  tests/backend/core/News/Functional/GlobalNewsHandlerTest.php
Labels: review:backend

#3680 fix(refs DPLAN-1917): Add map-params to newly created customers via GenerateCustomerCommand
  demosplan/DemosPlanCoreBundle/Command/Data/GenerateCustomerCommand.php
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerResourceType.php
  tests/backend/core/Core/Functional/GenerateCustomerCommandTest.php
Labels: review:backend

#3686 fix(DPLAN-1881): no bullet points are displayed
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/listentry_content.html.twig
Labels: review:frontend, quick-win

#3699 fix(refs DPLAN-12407): fix spacings and alignments
  client/js/components/map/admin/AdminLayerList.vue
  client/js/components/map/admin/AdminLayerListItem.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_sortablelist.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
  tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap
Labels: review:frontend

#3707 bug(refs DPLAN-12484): Fix target name for ol map draw point
  client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue
Labels: type:bug, review:frontend

#3683 bug(refs DPLAN-12445): Improve accessibility
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_button.scss
Labels: type:bug, review:frontend

#3706 upgrade demosplan-ui to version 0.3.32
  package.json
  yarn.lock
Labels: review:frontend

#3712 fix(DPLAN-2252): sorting is lost after form submit
  client/js/components/statement/assessmentTable/DpEditSelectedItemsMenu.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
  client/js/lib/statement/AssessmentTable.js
Labels: review:frontend

#3714 fix (refs DPLAN-12489): update Map to accept as an array instead of …
  client/js/components/map/map/DpOlMapLayerVector.vue
Labels: type:bug, review:frontend, quick-win

#3715 F dplan 12514 add berlin time to filenames
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableDocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Labels: review:backend, quick-win

#3717 bug(refs DPLAN-12380): Correct typo in Vuex mutation subscription
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
Labels: type:bug, review:frontend, quick-win

#3722 Fix(DPLAN-2252): issue where the 'remove' action was resetting the sorting option
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
  client/js/lib/statement/AssessmentTable.js
  client/js/store/statement/Statement.js
Labels: review:frontend

#3718 Fix(dplan 12522): position of the opacity control slider
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
Labels: review:frontend, quick-win

#3723 fix(refs dplan-12527): Fix missing territory fallback
  client/js/components/map/publicdetail/Map.vue
  composer.json
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Logic/Map/CoordinateJsonConverter.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
  tests/backend/core/Core/Functional/SetTestPermissionsListenerTest.php
Labels: review:frontend, review:backend

#3515 Update edt to 0.25
  composer.json
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Command/FrontendIntegratorCommand.php
  demosplan/DemosPlanCoreBundle/Controller/Base/APIDocumentationController.php
  demosplan/DemosPlanCoreBundle/Controller/Report/DemosPlanReportAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAPIController.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/JsonApiEsService.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AbstractRpcStatementBulkAction.php
  demosplan/DemosPlanCoreBundle/Logic/Document/ElementsService.php
  demosplan/DemosPlanCoreBundle/Logic/Elements/PlanningDocumentCategoryTreeReorderer.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqService.php
  demosplan/DemosPlanCoreBundle/Logic/News/ProcedureNewsService.php
  demosplan/DemosPlanCoreBundle/Logic/OwnsProcedureConditionFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/NonAuthorizedAssignRemover.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/AssignableUserResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InvitablePublicAgencyResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ReportEntryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/RoleResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/SegmentCommentResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/SignLanguageOverviewVideoResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/SimilarStatementSubmitterResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementSegmentResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/TagResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/TagTopicResourceType.php
  symfony.lock
Labels: review:backend

#3737 fix(DPLAN-12567): issue by saving department in fragment
  client/js/store/statement/Fragment.js
Labels: review:frontend

#3740 fix(DPLAN-12567): issue by saving department in fragment
  client/js/store/statement/Fragment.js
Labels: review:frontend

#3724 bug(refs DPLAN-12530): Set initial segments to empty array
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/store/statement/SplitStatementStore.js
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, review:backend

#3736 fix(refs DPLAN-12488): fix pinning statement information
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_statement_segments_list.html.twig
Labels: type:bug, review:frontend

#3738 bug(refs DPLAN-12552): Distinguish between master and procedure
  client/js/components/map/admin/MapAdmin.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/store/map/ProcedureMapSettings.js
  demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureTemplateResourceType.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin.html.twig
Labels: type:bug, review:frontend, review:backend
