Repository demos-europe/demosplan-core, pull requests merged in 2024-05, with the labels that each got.

#3027 Fix(DPLAN-11518): adjust fullscreen-mode layout when a bulk-edit is displayed
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend, quick-win

#3034 bug (ref DPLAN-1970) Remove duplicated breadcrumbs
  demosplan/DemosPlanCoreBundle/Services/Breadcrumb/Breadcrumb.php
Labels: review:backend

#3038 fix(DPLAN-1965): improve error validation of the Datepicker
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#3041 chore (refs DPLAN-11547): Tus path needs to be relative
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/js/dplan.settings.js.twig
Labels: type:bug, review:frontend, review:backend

#3039 F dplan 11443 add additional fields procedure map setting
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/ProcedureMapSettingResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
  demosplan/DemosPlanCoreBundle/ValueObject/Procedure/AvailableProjectionVO.php
Labels: review:backend

#3048 chore (refs DPLAN-11537): add missing Hooks/Selectors.
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_dashboard.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3047 feat(refs DPLAN-3570): Settings for initial map area (copy of 2964)
  client/js/bundles/map/mapAdmin.js
  client/js/bundles/procedure/administrationStatementSegmentsList.js
  client/js/components/map/admin/DpMapAdmin.vue
  client/js/components/map/admin/MapAdmin.vue
  client/js/components/map/admin/MapAdminScales.vue
  client/js/components/map/map/DpOlMap.vue
  client/js/components/map/map/DpOlMapSetExtent.vue
  client/js/components/map/map/MapView.vue
  client/js/components/map/map/utils/convertExtentToFlatArray.js
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/store/map/ProcedureMapSettings.js
  config/menus.yml
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/Map/DemosPlanMapController.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin.html.twig
  tests/frontend/unit/convertExtentToFlatArray.spec.js
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#3049 chore: Bump demosplan-ui @0.3.12
  package.json
  yarn.lock
Labels: review:frontend, quick-win

#3055 chore: Update GH-Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#3054 fix(refs DPLAN-11559): Set fullwidth for Tags
  client/js/components/statement/splitStatement/TagSelect.vue
Labels: type:bug, review:frontend, quick-win

#3050 fix(refs dplan-11557): Only send set extents on patch
  client/js/components/map/admin/MapAdmin.vue
  client/js/components/map/map/utils/convertExtentToObject.js
  client/js/store/map/ProcedureMapSettings.js
  tests/frontend/unit/convertExtentToObject.spec.js
Labels: type:bug, review:frontend

#3056 B dplan 11557 add map permissions
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
Labels: review:backend

#3052 bug(refs DPLAN-3570): Fix params for api request
  client/js/store/map/ProcedureMapSettings.js
Labels: type:bug, review:frontend, quick-win

#3053 chore: create addonZips dir if it does not exist
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend, quick-win

#3058 B dplan 11557 remove scales check permission
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
Labels: review:backend

#3059 feat(refs DPLAN-3570): add permissions for map settings
  client/js/components/map/admin/MapAdmin.vue
  client/js/components/map/map/MapView.vue
  client/js/store/map/ProcedureMapSettings.js
Labels: type:bug, review:frontend

#3032 chore: improve list performance
  demosplan/DemosPlanCoreBundle/Logic/ProcedureAccessEvaluator.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
Labels: review:backend

#3011 feat (refs DPLAN-603, DPLAN-1901): Introduce rate limits against brute force
  .env
  client/js/components/statement/publicStatementModal/StatementModal.vue
  composer.json
  composer.lock
  config/packages/rate_limiter.yaml
  config/packages/security.yaml
  demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrgaController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/LoginFormAuthenticator.php
  phpunit.xml
  symfony.lock
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#2988 chore: remove deprecated guard authentication
  config/packages/security.yaml
  config/services.yml
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/AiApiAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/ApiAuthenticator.php
Labels: review:backend

#2984 chore: set project migrations as migrated on container setup
  demosplan/DemosPlanCoreBundle/Command/ContainerInitCommand.php
  demosplan/DemosPlanCoreBundle/Command/InitDbCommand.php
Labels: review:backend

#2983 chore: only suggest allowed roles in command
  demosplan/DemosPlanCoreBundle/Command/Data/RegisterUserForCustomerCommand.php
  demosplan/DemosPlanCoreBundle/Command/Helpers/Helpers.php
  demosplan/DemosPlanCoreBundle/Command/User/UserCreateCommand.php
  tests/backend/core/Core/Functional/RegisterUserForCustomerCommandTest.php
Labels: review:backend

#2446 F fix related support contact issues
  demosplan/DemosPlanCoreBundle/Entity/User/SupportContact.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/login_idp_error.html.twig
Labels: type:bug, review:frontend, review:backend, quick-win

#3074 fix(refs dplan-11435): get hash for filter
  client/js/components/procedure/admin/AdministrationProceduresList.vue
  client/js/store/statement/Filter.js
  tests/frontend/unit/__mocks__/UserFilterSetResource.mock.js
  tests/frontend/unit/store/Filter.spec.js
Labels: type:bug, review:frontend

#3081 chore (refs DPLAN-2746): add missing Hook/Selector.
  client/js/components/statement/assessmentTable/DpFilterModal.vue
Labels: review:frontend, quick-win, type:enhancement

#3084 chore: fix namespaces
  tests/backend/core/Statement/Functional/StatementHandlerTest.php
Labels: review:backend, quick-win

#3085 chore: explicitly define used php extensions
  composer.json
Labels: review:backend, quick-win

#2993 F dplan 11487 update edt dependencies
  composer.json
  composer.lock
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentRpcController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAPIController.php
  demosplan/DemosPlanCoreBundle/Logic/JsonApiActionService.php
  demosplan/DemosPlanCoreBundle/Logic/RpcStatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcBulkEditor/RpcSegmentIdLoader.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcSegmentFacetsProvider.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  demosplan/DemosPlanCoreBundle/Permissions/PermissionDrupalConditionFactory.php
  demosplan/DemosPlanCoreBundle/Permissions/PermissionResolver.php
  symfony.lock
  tests/backend/core/Core/Functional/EntityFetcherTest.php
Labels: review:backend

#3086 bug(refs DPLAN-11472): Add event for phase selecting
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
  client/js/components/procedure/basicSettings/ParticipationPhases.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  tests/frontend/unit/ParticipationPhases.spec.js
Labels: type:bug, review:frontend, type:enhancement

#3057 Fix dplan 11494 update pi proposals with excel imported tags
  demosplan/DemosPlanCoreBundle/Event/Statement/StatementCreatedViaExcelEvent.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
Labels: review:backend

#3088 fix(refs DPLAN-3570): Add resetbutton to map settings
  client/js/components/map/admin/MapAdmin.vue
  client/js/store/map/ProcedureMapSettings.js
  config/permissions.yml
Labels: review:frontend, type:enhancement

#3087 chore: autowire repositories via compiler pass
  config/services_repositories.yml
  demosplan/DemosPlanCoreBundle/Application/DemosPlanKernel.php
  demosplan/DemosPlanCoreBundle/DependencyInjection/Compiler/RepositoryLoaderPass.php
  demosplan/DemosPlanCoreBundle/Repository/ElementsRepository.php
  tests/backend/core/Core/Functional/RepositoryLoaderPassTest.php
Labels: review:backend, type:enhancement

#3044 chore: symfony dependencies could be grouped
  .github/dependabot.yml
Labels: devops, review:backend

#3099 chore (refs DPLAN-11427): add missing Hook/Selector for Map.
  client/js/components/map/admin/MapAdmin.vue
  client/js/components/map/admin/MapAdminScales.vue
  client/js/components/map/map/DpOlMap.vue
  client/js/components/map/map/DpOlMapDragZoom.vue
  client/js/components/map/map/DpOlMapScaleSelect.vue
Labels: review:frontend, quick-win, type:enhancement

#3100 chore (refs DPLAN-1078): add missing gatewayURL
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Labels: type:bug, review:backend, quick-win

#3090 f DPLAN-11596 copy blueprint legend while procedure creation
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
Labels: type:bug, review:backend

#3083 chore: upgrade psalm 5
  composer.json
  composer.lock
  config/linters/psalm.template.xml
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentExportOptions.php
  symfony.lock
Labels: review:backend

#3106 F dplan 11494 upgrade demosplan addon to 0.34
  composer.lock
Labels: review:backend, quick-win

#3107 chore (refs DPLAN-11426): Add missing Hooks/Selector.
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/single_document_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/single_document_admin_new.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3109 chore (refs DPLAN-11497): Add missing Hooks/Selector.
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3115 chore (refs DPLAN-11538): Add missing Hooks/Selectors.
  client/js/components/map/map/DpOlMapDrawPoint.vue
  client/js/components/procedure/basicSettings/ProcedureCoordinateGeolocation.vue
Labels: review:frontend, quick-win, type:enhancement

#2653 feat: allow local addon development
  .gitignore
  demosplan/DemosPlanCoreBundle/Addon/Registrator.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonUninstallCommand.php
Labels: review:backend

#3117 chore (refs DPLAN-11624): delete Hamburg address & Fax from contact.
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatic/imprint_entry.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3118 chore (refs DPLAN-11604): Add missing Hooks/Selectors.
  client/js/components/statement/assessmentTable/DpEditSelectedItemsMenu.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
Labels: review:frontend, quick-win, type:enhancement

#3119 feat (DPLAN-11407): add addonDev to gitingore
  .gitignore
Labels: review:backend, quick-win

#3089 fix(DPLAN-2231): location validation issue on the basic settings page
  client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend

#3082 chore (refs DPLAN-603): throttle password reset requests
  config/packages/rate_limiter.yaml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#3127 chore (refs DPLAN-3254): Add missing Hooks/Selectors.
  client/js/components/statement/voter/StatementVoter.vue
Labels: review:frontend, quick-win, type:enhancement

#3126 chore: update php-parallel-lint/php-console-highlighter
  composer.json
  composer.lock
Labels: review:backend, quick-win

#3131 chore (refs DPLAN-11543): Add missing Hooks/Selectors.
  client/js/components/statement/publicStatementModal/StatementModal.vue
Labels: review:frontend, quick-win, type:enhancement

#3132 chore (refs DPLAN-3490): Add missing Hooks/Selectors.
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
Labels: quick-win, support:frontend, type:enhancement

#3133 chore (refs DPLAN-11472, DPLAN-3499): Edit Hooks/Selectors.
  client/js/components/procedure/basicSettings/ParticipationPhases.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3134 fix (refs DPLAN-11422): add composer_lock_for_minor_demosplan_addon_update
  composer.json
  composer.lock
Labels: review:backend

#3139 chore (refs DPLAN-11531): Edit Hooks/Selectors naming for export stat…
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend, quick-win, type:enhancement

#3140 bug: fix browser tracing sentry
  client/js/loadSentry.js
Labels: type:bug, review:frontend

#3141 chore (refs DPLAN-11605): Add missing Hooks/Selectors for assessment …
  client/js/components/statement/assessmentTable/DetailView/DetailViewFinalEmailBody.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_final.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_text.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/statement_detail_subheader.html.twig
  templates/bundles/DemosPlanCoreBundle/UI/form/datepicker.html.twig
Labels: review:frontend, type:enhancement

#3150 F dplan 11494 request segmentation after statements are committed
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxSegmentImport.php
Labels: review:backend

#3153 chore: Bump demosplan-ui to v0.3.15
  package.json
  yarn.lock
Labels: review:frontend

#3154 chore (refs DPLAN-11605): Add missing Hook.
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3152 chore (refs DPLAN-11504): Adjust data-cy Hooks/Selectors.
  client/js/components/procedure/basicSettings/DpEmailList.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, quick-win, type:enhancement

#3164 chore: Set concrete Version for demosplan-addon
  composer.json
Labels: review:backend, quick-win

#3163 chore (refs DPLAN-11651): Add missing Hooks/Selectors for statements …
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/DpTable.vue
Labels: review:frontend, quick-win, type:enhancement

#3161 fix (ref DPLAN-11370) Escape special chars to diplay file name using latex
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_public_citizen.tex.twig
Labels: type:bug, review:frontend

#3165 fix(refs DPLAN-11646): Expose Permission to control setting the map_max_extent
  config/permissions.yml
Labels: type:bug, review:frontend, quick-win

#3181 feature (ref ADO-16632): create factory for cockpit story
  demosplan/DemosPlanCoreBundle/Logic/Factory/BoilerplateCategoryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Factory/BoilerplateFactory.php
Labels: review:backend, type:story

#3194 fix (refs DPLAN-11422): bump demosplan-addon version
  composer.lock
Labels: review:backend, quick-win

#3179 fix (DPLAN-11584) use method with procedure id to open pdf view correctly
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/procedure_newslist.html.twig
Labels: type:bug, review:frontend

#3175 fix(refs DPLAN-11601): Only allow orgas with E-Mail addresses to be ivitable
  client/js/components/procedure/admin/DpAddOrganisationList.vue
  package.json
  translations/messages+intl-icu.de.yml
  yarn.lock
Labels: review:frontend, type:story

#3187 chore (refs DPLAN-11668): Add missing Hooks/Selectors in Public-View.
  client/js/components/map/publicdetail/controls/CustomLayer.vue
  client/js/components/map/publicdetail/controls/MapTools.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListWrapper.vue
  client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue
  client/js/components/procedure/publicindex/drawer/ContentToggle.vue
  client/js/components/procedure/publicindex/drawer/Search.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
Labels: review:frontend, type:enhancement

#3203 chore: Run yarn upgrade jest
  yarn.lock
Labels: type:bug, review:frontend

#3186 bug (refs DPLAN-11551): Show procedure phase depending on role
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
Labels: type:bug, review:frontend

#3204 chore (refs DPLAN-11500): Add missing Hook/Selector.
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/news_admin_edit.html.twig
Labels: review:frontend, quick-win, type:enhancement
