Repository demos-europe/demosplan-core, pull requests merged in 2024-03, with the labels that each got.

#2810 fix (refs T36617): prevent a permission check via onKernelEvent before permissions are initialized.
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: type:bug, review:backend

#2811 fix(refs T36317): tweak layout spacing
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_splitstatement.scss
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#2812 feature (ref 36588): create a permission for profile edit
  config/permissions.yml
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_profile.html.twig
Labels: type:bug, review:backend

#2806 Feat(refs:T36493): show the default copyright note in the correct maps
  client/js/components/document/DpMapSettingsPreview.vue
  client/js/components/map/map/DpMapView.vue
  client/js/components/map/map/DpOlMapLayer.vue
Labels: type:bug, review:frontend

#2825 fix(refs T36638): remove obsolete negative margin
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_switcher.scss
Labels: type:bug, review:frontend

#2828 F t36528 add similar stn submitters to statement list export
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
Labels: type:bug, review:backend, quick-win

#2833 Fix(refs:T36718): wrong message after click delete and reload
  demosplan/DemosPlanCoreBundle/Controller/Help/DemosPlanHelpController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanHelp/help_admin_contextual_help_list.html.twig
Labels: type:bug, review:frontend, review:backend

#2830 Fix(refs: T36722): missing fragment entries
  client/js/components/statement/fragmentList/DpFragmentList.vue
  client/js/components/statement/fragmentList/Fragment.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statement_fragments.html.twig
Labels: type:bug, review:frontend

#2746 build(refs T36496): Configure yarn cache dir for CI
  Jenkinsfile
Labels: devops

#2836 chore: minor exporter optimizations
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/ZipExportService.php
Labels: review:backend, quick-win

#2821 fix(refs T27465): display only documents that should be visible
  client/js/components/document/ElementsList.vue
  demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanningDocumentCategoryResourceType.php
Labels: type:bug, review:frontend, review:backend

#2848 fix(refs T36753): use full width to display the stn text
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
Labels: type:bug, review:frontend, quick-win

#2844 f T26867 remove chapter (kapitel) from statement filter
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFilterHandler.php
Labels: type:bug, review:backend

#2846 fix(refs T36689): document attribute name has to be without s
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/store/statement/Statement.js
Labels: type:bug, review:frontend, quick-win

#2843 feature (ref 15290): remove session between pages.
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentController.php
Labels: type:bug, review:backend

#2845 feature (ref 15938): use right key to show variable in pdf export
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFragmentService.php
Labels: type:bug, review:backend

#2820 Fix(refs:T31364): Edit fragment doesnt work
  client/js/components/statement/fragment/Edit.vue
  client/js/components/statement/fragment/Version.vue
  client/js/components/statement/fragmentList/DpFragmentList.vue
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanAssessmentStatementFragmentController.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Repository/StatementFragmentRepository.php
Labels: type:bug, review:frontend, review:backend

#2849 feat(refs T36528): add message to confirm export.
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
Labels: type:bug, review:frontend, quick-win

#2852 abort "yarn install" if demosplan-ui is mounted in container
  package.json
Labels: review:frontend

#2847 fix(refs T35941): rollback partial fix, serialize params
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/EditableText.vue
Labels: type:bug, review:frontend

#2854 F t31399 fragment cannot be assigned to orga
  client/js/store/statement/Fragment.js
Labels: type:bug, review:frontend

#2832 Fix(refs:T36703): unused checkbox
  client/js/components/statement/publicStatementLists/DpPublicStatement.vue
  client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/form_tools_mark-all.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_final_group_citizen.html.twig
Labels: type:bug, review:frontend, type:enhancement

#2858 f T26867 remove chapter from filter and export
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/form_filter.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
Labels: type:bug, review:frontend

#2860 fix: Cherry picks from oher Branches
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/EditableText.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  client/js/store/statement/Statement.js
Labels: type:bug, review:frontend

#2816 feat(refs T35963): enable split statements
  client/js/bundles/procedure/administrationSplitStatement.js
  client/js/bundles/procedure/administrationStatementSegmentsList.js
  client/js/components/addon/AddonWrapper.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
  client/js/components/statement/splitStatement/CardPane.vue
  client/js/components/statement/splitStatement/CardPaneCard.vue
  client/js/components/statement/splitStatement/DpCreateTag.vue
  client/js/components/statement/splitStatement/SearchSelect.vue
  client/js/components/statement/splitStatement/SegmentationEditor.vue
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/components/statement/splitStatement/TagSelect.vue
  client/js/lib/prosemirror/commands.js
  client/js/lib/prosemirror/marks.js
  client/js/lib/prosemirror/plugins.js
  client/js/lib/prosemirror/utilities.js
  client/js/store/statement/SplitStatementStore.js
  client/js/store/statement/storeHelpers/SplitStatementStore/HTMLIdxToProsemirrorIdx.js
  client/js/store/statement/storeHelpers/SplitStatementStore/PiTagsToJSONApi.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_split_statement.html.twig
Labels: review:frontend, type:enhancement

#2866 upgrade demosplan-ui to version 0.3.8
  package.json
  yarn.lock
Labels: review:frontend

#2853 Fix(T36635): improve error validation for DpMultiselect component
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
Labels: review:frontend, quick-win

#2823 fix(T36253): improve TreeList performance
  client/js/components/document/ElementsList.vue
Labels: review:frontend

#2868 fix(refs T26867): Cherry pick for t26867
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/form_filter.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
Labels: type:bug, review:frontend

#2870 Feat: add Routing.generate global and remove unused file
  client/js/VueConfigLocal.js
  client/setup/jest/setup.js
Labels: review:frontend, type:enhancement

#2867 chore (refs T34247): Add missing Hooks/Selectors.
  client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue
  tests/frontend/unit/__snapshots__/SearchModal.spec.js.snap
  tests/frontend/unit/store/storeHelpers/SplitStatementStore/HTMLIdxToProsemirrorIdx.spec.js
Labels: review:frontend, quick-win, type:enhancement

#2582 feat (refs T27469): Filter by unassigned segments.
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcSegmentFacetsProvider.php
Labels: review:frontend, review:backend

#2874 fix(refs T36849): display link inline
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
Labels: type:bug, review:frontend

#2875 fix: remove setupFiles in config because it is not used any more
  jest.config.js
Labels: type:bug, review:frontend

#2876 fix(refs T36849): display procedure title below link(s)
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
Labels: type:bug, review:frontend

#2877 chore (refs T36838): Add E-2-E Hooks/Selectors.
  client/js/components/procedure/admin/AdministrationProceduresList.vue
Labels: review:frontend, quick-win, type:enhancement

#2606 Harden file downloads
  demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/includes/item/files.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_cluster_detail_statement_data.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_global_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/public_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/view_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/includes/listentry_content.html.twig
Labels: review:frontend, review:backend

#2878 Cleanup calls of dpApi
  client/js/bundles/procedure/publicIndexMapAndList.js
  client/js/bundles/procedure/publicIndexSimpleList.js
  client/js/components/map/map/DpOlMap.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/procedure/DpDashboardTaskCard.vue
  client/js/components/procedure/DpSearchProcedures.vue
  client/js/components/procedure/DpSubmitterList.vue
  client/js/components/procedure/admin/AdministrationProceduresList.vue
  client/js/components/procedure/admin/AuthorizedUsersList.vue
  client/js/components/procedure/admin/NewBlueprintForm.vue
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
  client/js/components/procedure/imageAnnotator/DpConvertAnnotatedPdf.vue
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
  client/js/components/procedure/survey/DpSurveyCommentsList.vue
  client/js/components/statement/assessmentTable/DetailView/DetailView.vue
  client/js/components/statement/assessmentTable/EditableText.vue
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/components/statement/statement/DpVersionHistory.vue
  client/js/components/statement/statement/DpVersionHistoryItem.vue
  client/js/components/user/CustomerSettings/CustomerSettings.vue
  client/js/components/user/DpUserListExtended.vue
  client/js/lib/procedure/CreateProcedure.js
  client/js/lib/statement/AssessmentTable.js
  client/js/lib/statement/AssessmentTableOriginal.js
  client/js/lib/statement/DeleteFragmentButton.js
  client/js/store/core/utils/storeUtils.js
  client/js/store/map/Layers.js
  client/js/store/procedure/Boilerplates.js
  client/js/store/procedure/Location.js
  client/js/store/procedure/Procedure.js
  client/js/store/statement/AssessmentTable.js
  client/js/store/statement/Filter.js
  client/js/store/statement/Fragment.js
  client/js/store/statement/SplitStatementStore.js
  client/js/store/statement/Statement.js
Labels: review:frontend

#2879 fix(refs T36875): Pass ProcedureId as string instead of Param
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/paragraph_admin_new.html.twig
Labels: type:bug, review:frontend

#2885 chore (refs T36840): add missing Hooks/Selectors.
  client/js/components/statement/assessmentTable/DpFilterModal.vue
  client/js/components/statement/assessmentTable/FilterModalSelectItem.vue
Labels: review:frontend, quick-win, type:enhancement

#2741 chore: use existing password create function
  demosplan/DemosPlanCoreBundle/Logic/User/UserService.php
Labels: review:backend, quick-win

#2887 chore (refs T36569): Add missing Hooks/Selectors.
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  client/js/components/statement/statement/SelectStatementCluster.vue
  client/js/components/statement/voter/StatementVoter.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/Extension/fileupload.html.twig
Labels: review:frontend, type:enhancement

#2888 fix(refs T35941): rollback partial fix, serialize params (2847) (2859)
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/EditableText.vue
Labels: type:bug, review:frontend
