Repository demos-europe/demosplan-core, pull requests merged in 2024-12, with the labels that each got.

#4084 chore: bump demosplan-ui to 0.3.41
  package.json
  yarn.lock
Labels: type:bug, review:frontend, quick-win

#4076 fix(refs dplan-12315): Send correct data on statement modal edit
  client/js/bundles/core/listDraft.js
  client/js/components/statement/publicStatementModal/StatementModal.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_draft.html.twig
Labels: type:bug, review:frontend, type:enhancement

#4086 chore(refs dplan-12315): remove template tags
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_released_group.html.twig
Labels: review:frontend, type:enhancement

#4066 fix-DPLAN-12816-retain-layers-preselection-after-saving-or-updating-layers
  demosplan/DemosPlanCoreBundle/Logic/Map/MapHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Map/MapService.php
  demosplan/DemosPlanCoreBundle/Repository/MapRepository.php
  tests/backend/core/Map/Functional/MapHandlerTest.php
Labels: type:bug, review:backend

#4089 f DPLAN-12816 adjust tests
  tests/backend/core/Map/Functional/MapHandlerTest.php
Labels: review:backend

#4090 f DPLAN-12816 adjust tests
  tests/backend/core/Map/Functional/MapHandlerTest.php
Labels: review:backend

#4087 fix(refs DPLAN-12844): Pass Text as Propper String
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/send_statement.html.twig
Labels: type:bug, review:frontend

#4093 chore: Bump Node
  package.json
Labels: review:frontend, type:enhancement

#4042 feat (refs DPLAN-12914): institution tags and categories
  client/js/bundles/procedure/institutionTagManagement.js
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionTagManagement.vue
  client/js/components/procedure/admin/InstitutionTagManagement/NewCategoryForm.vue
  client/js/components/procedure/admin/InstitutionTagManagement/NewTagForm.vue
  client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/TagListItem.vue
  client/js/components/procedure/admin/TagList.vue
  composer.json
  composer.lock
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/11/Version20241121152930.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/11/Version20241122110226.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/11/Version20241122120756.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/11/Version20241127130549.php
  demosplan/DemosPlanCoreBundle/Entity/User/Customer.php
  demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTag.php
  demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTagCategory.php
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/ResourceTypeStore.php
  demosplan/DemosPlanCoreBundle/Logic/Customer/CustomerDeleter.php
  demosplan/DemosPlanCoreBundle/Logic/Orga/OrgaDeleter.php
  demosplan/DemosPlanCoreBundle/Repository/InstitutionTagCategoryRepository.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/InstitutionTagCategoryResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/InstitutionTagResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagCategoryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagResourceType.php
  package.json
  tests/frontend/unit/NewTagForm.spec.js
  translations/messages+intl-icu.de.yml
  yarn.lock
Labels: review:frontend, review:backend, type:story

#3985 feat (DPLAN-11405): delete_command adjustment and test adjustment
  demosplan/DemosPlanCoreBundle/Command/Data/DeleteProcedureCommand.php
  tests/backend/core/Core/Functional/Command/DeleteProcedureCommandTest.php
Labels: review:backend

#4110 Use if condition to access voting and publication area
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  config/permissions.yml
Labels: type:bug, review:frontend

#4001 fix (DPLAN-12733) Add tests for DraftStatementFileHandlerTest
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/FileFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/DraftStatementFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/DraftStatementFileFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/User/DepartmentFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/User/UserFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementFileHandler.php
  tests/backend/core/DraftStatementFIle/DraftStatementFileHandlerTest.php
Labels: review:backend

#4116 fix(refs DPLAN 12667) move receiver address into globalconfig - env variable
  .env
  config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/EventSubscriber/ProcedureMetricsEmailEventSubscriber.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
Labels: review:backend

#4117 F dplan 12667 pick procedureMetrics Mail for release ewm
  .env
  config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/EventSubscriber/ProcedureMetricsEmailEventSubscriber.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
Labels: review:backend

#4085 chore: Refactor webpack config
  client/fe/config/config.js
  client/fe/webpack/resolveAliases.js
  config.webpack.js
Labels: review:frontend, type:enhancement

#4092 chore(refs dplan-12315): Set deep for watcher explicitly
  client/js/components/map/admin/AdminLayerListItem.vue
  client/js/components/map/admin/MapAdminScales.vue
  client/js/components/map/map/DpOlMapLayer.vue
  client/js/components/map/map/DpOlMapLayerVector.vue
  client/js/components/map/map/DpOlMapScaleSelect.vue
  client/js/components/map/map/MapView.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue
  client/js/components/procedure/DpSimplifiedNewStatementForm.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/procedure/admin/InstitutionTagManagement.vue
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  client/js/components/procedure/basicSettings/DpProcedureCoordinateInput.vue
  client/js/components/procedure/basicSettings/ProcedureCoordinateGeolocation.vue
  client/js/components/procedure/publicindex/map/Map.vue
  client/js/components/statement/assessmentTable/DpEditField.vue
  client/js/components/statement/assessmentTable/DpEditFieldSingleSelect.vue
  client/js/components/statement/assessmentTable/DpFilterModal.vue
  client/js/components/statement/assessmentTable/DpMoveStatementModal.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
  client/js/components/statement/assessmentTable/StatementReplySelect.vue
  client/js/components/statement/assessmentTable/TocView/SearchAndSorting.vue
  client/js/components/statement/fragment/SelectDocument.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  client/js/components/user/DpTableCardList/DpTableCard.vue
Labels: review:frontend, type:enhancement

#4121 fix(refs DPLAN-12981, #AB17874): update prop on save
  client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/TagListItem.vue
Labels: type:bug, review:frontend

#4124 fix(refs DPLAN-13017): update list after delete
  client/js/components/procedure/admin/InstitutionTagManagement/TagListItem.vue
Labels: type:bug, review:frontend

#4095 chore: Bump Sass-loader to 16.0.3
  client/fe/webpack/moduleRules.js
  client/fe/webpack/plugins.js
  package.json
  yarn.lock
Labels: review:frontend, dependencies:yarn, type:enhancement

#4126 Fix User List Item Load
  client/js/components/user/DpUserList/DpUserListItem.vue
Labels: type:bug, review:frontend

#4120 Access to area and documentation in statement
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  config/permissions.yml
Labels: type:bug

#3725 chore (refs DPLAN-12535): adjust Hook/Selector for statements list link.
  config/menus.yml
Labels: review:frontend, quick-win, type:enhancement

#3681 chore: Add missing Cypress Hooks/Selectors.
  client/js/components/report/DpReportListing.vue
  client/js/components/statement/HeightLimit.vue
  client/js/components/statement/StatementMetaTooltip.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/includes/search_and_sorting.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, quick-win, type:enhancement

#4135 chore: To be aligned with the changes in demosplan-ui.
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_procedure_type_edit.html.twig
Labels: type:bug, review:frontend, type:enhancement

#4145 fix(refs DPLAN-13038): Use Pascalcase for store name
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/FragmentsButton.vue
Labels: type:bug, review:frontend

#4146 fix(refs dplan-13039) Add missing attributes for layer
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListWrapper.vue
  client/js/store/map/Layers.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
Labels: type:bug, review:frontend

#4053 chore: declare dev dependencies as such
  composer.json
  composer.lock
  symfony.lock
Labels: review:backend

#4099 chore: fix a bunch of backend tests
  demosplan/DemosPlanCoreBundle/Controller/GenericApiController.php
  tests/backend/core/Core/Functional/Command/AddonAutoinstallCommandTest.php
  tests/backend/core/DemosPlanCoreBundle/Entity/User/SecurityUserTest.php
Labels: review:backend

#4097 chore: update csv lib for symfony 6 upgrade
  composer.json
  composer.lock
  config/bundles.php
  config/packages/intriro_csv.yml
  config/services.yml
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
  demosplan/DemosPlanCoreBundle/Logic/FileService.php
  demosplan/DemosPlanCoreBundle/Logic/LocationUpdateService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  symfony.lock
  tests/backend/core/Statement/Functional/StatementHandlerTest.php
  tests/backend/core/Statement/Functional/res/tagTopics.csv
Labels: review:backend

#4052 chore: autoinstall addons during container build
  docker/build.sh
  docker/demosplan-production/Dockerfile
  docker/demosplan-production/php-fpm.conf
  docker/demosplan-production/php-fpm_www.conf
  docker/rsyncInclude.txt
Labels: devops

#4080 chore: symfony/http-client has the same versions as other core bundles
  .github/dependabot.yml
Labels: review:backend

#3929 chore: improve csp for script and style
  config/config_dev_container.yml
  config/packages/nelmio_security.yaml
  config/parameters_default.yml
  config/services.yml
  demosplan/DemosPlanCoreBundle/Twig/Extension/WebpackBundleExtension.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/procedure_newslist.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail_form_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_index_globalnewslist.html.twig
Labels: review:frontend, review:backend

#4118 chore: Run lint fix
  client/fe/config/projectConfig.js
  client/fe/index.js
  client/js/InitVue.js
  client/js/bootstrap.js
  client/js/bundles/admin/statistics.js
  client/js/components/map/map/DpOlMapDrawPoint.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/statement/assessmentTable/utils/changeUrlforPager.js
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/lib/addon/loadAddonComponents.js
  client/js/lib/procedure/charts/DonutChart.js
  client/js/lib/statement/DeleteFragmentButton.js
  client/js/store/core/initStore.js
  config/linters/eslintrc.complete.js
  stylelint.config.js
  tests/frontend/unit/StatusBadge.spec.js
  tests/frontend/unit/store/Statement.spec.js
Labels: type:enhancement

#4151 chore: Remove unused Code
  client/js/components/user/DpUserList/DpUserFormFields.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/gateway_newUser.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_departments.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/list_orgas.html.twig
Labels: review:frontend, type:enhancement

#4158 Show Attachments in statement Detail
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilderWithZipSupport.php
Labels: type:bug, review:backend

#4157 Show attachments in statement detail by zip importer
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilderWithZipSupport.php
Labels: type:bug, review:backend

#4130 Conditional sidebar menu in statement detail
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
Labels: type:bug, review:frontend
