Repository demos-europe/demosplan-core, pull requests merged in 2024-04, with the labels that each got.

#2893 chore (refs T36853): Add missing Hooks/Selectors.
  client/js/components/statement/listStatements/ListStatements.vue
Labels: quick-win, support:frontend, type:enhancement

#2896 chore (refs DPP-11374): Add missing Hooks/Selectors.
  client/js/components/procedure/admin/DpNewProcedure/CoupleTokenInput.vue
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
Labels: quick-win, support:frontend, type:enhancement

#2898 chore (refs DPLAN-3254): Add missing Hooks/Selectors.
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: review:frontend, quick-win, type:enhancement

#2889 T36340 Allow iteration of procedure phases
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/03/Version20240313120508.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/03/Version20240328093128.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedurePhaseResourceType.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/UI/form/label.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:backend

#2900 feat(refs DPLAN-11388): Fix Template
  client/js/components/map/map/DpMapView.vue
Labels: type:bug, review:frontend, quick-win

#2826 F t36340 preparation phasecounter
  config/permissions.yml
  config/services_repositories.yml
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/03/Version20240313115724.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/03/Version20240313120508.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/03/Version20240318172346.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/03/Version20240321192129.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2024/03/Version20240328093128.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ProcedureConditionDefinition.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/PrepareReportFromProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureToLegacyConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedurePhaseRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/AdminProcedureResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedurePhaseResourceType.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/UI/form/label.html.twig
  tests/backend/core/Procedure/Functional/ProcedureHandlerTest.php
  tests/backend/core/Procedure/Functional/ProcedureServiceTest.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#2901 feat (DPLAN-3274): update demosplan-addon v0.29
  composer.lock
Labels: quick-win

#2907 feature: change method from private to protected
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Labels: review:backend

#2921 fix(refs DPLAN-11392): Add Pattern to iterator input
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: type:bug, review:frontend

#2905 fix (refs DPLAN-1924): change default ul latex pdf lineWidth
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry_condensed.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_original_entry.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_public_citizen.tex.twig
  tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php
Labels: review:backend

#2906 feat (DPLAN-11355): get procedure by phase id
  composer.lock
  demosplan/DemosPlanCoreBundle/Repository/ProcedurePhaseRepository.php
Labels: review:backend

#2935 feat (DPLAN-11392): check input of phase iteration on update procedure.
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#2932 chore (refs DPLAN-3253): Add missing Hooks/Selectors.
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/DpExportModal.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_pageheader.html.twig
Labels: review:frontend, quick-win, type:enhancement

#2937 F (refs dplan 1924) change default ul latex pdf line width (#2929)
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
  demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry_condensed.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_original_entry.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_paragraph.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_export_entry_public_citizen.tex.twig
  tests/backend/core/Core/Unit/Utilities/Twig/LatexExtensionTest.php
Labels: review:backend

#2936 feat (DPLAN-11355): trigger no update for procedure phases during procedure creation
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
Labels: review:backend

#2941 F dplan 1924 adjust anonymous export templates
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry_anonymous.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_assessment_table_entry_anonymous_condensed.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/export_fragments_anonymous.tex.twig
Labels: review:backend

#2943 fix (refs DPLAN-1140): add Orga.Address.HouseNumber to eMail-invitation templates in addition to the street property
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_send_invitation_email.html.twig
Labels: type:bug, quick-win

#2947 chore: remove vue-multiselect as direct dependency
  package.json
  yarn.lock
Labels: review:frontend

#2939 fix(refs dplan-11402, dplan-11403): Refactor logic to display Permissions for selected Phase
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
  client/js/components/procedure/basicSettings/ParticipationPhases.vue
  client/js/lib/procedure/AdministrationMaster.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  tests/frontend/unit/ParticipationPhases.spec.js
Labels: type:bug, review:frontend

#2950 feat (DPLAN-3274): called method does not exist
  demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
Labels: review:backend

#2951 fix(refs CareKan-34): Use proper Event when using DpSelect for Departments
  client/js/components/user/DpUserList/DpUserFormFields.vue
Labels: type:bug, review:frontend, quick-win

#2956 feat (DPLAN-11392): fix detection of change of public phase change
  demosplan/DemosPlanCoreBundle/Logic/Procedure/PrepareReportFromProcedureService.php
Labels: review:backend

#2957 B dplan 11420 reflect censored texts also in pdfs
  demosplan/DemosPlanCoreBundle/Twig/Extension/LatexExtension.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/pdfexport_condensed.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/pdfexport.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/export_datasheet_statementV1.tex.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/export_datasheet_statementV2.tex.twig
Labels: review:backend

#2948 bug(refs DPLAN-11421): Add readon link for news
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/procedure_newslist.html.twig
Labels: type:bug, review:frontend, quick-win

#2955 chore (refs DPLAN-11413): replace v-tooltip directive with DpContextu…
  client/js/components/map/map/DpMapView.vue
  client/js/components/map/publicdetail/controls/MapTools.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListCategory.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
  client/js/components/procedure/DpSurveyStatus.vue
  client/js/components/procedure/admin/AuthorizedUsersList.vue
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
  client/js/components/statement/DpBoilerPlate.vue
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  client/js/components/user/DpUserList/DpUserList.vue
Labels: review:frontend, type:enhancement

#2961 chore: install addon from github branch
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend

#2962 fix: elevate slidebar above z-fixed
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_slidebar.scss
Labels: review:frontend

#2574 feature: enable resource property sortability by default
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/EventSubscriber/ProcedureCoupleTokenSubscriber.php
Labels: review:backend

#2963 Add global bottom padding to content area
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
Labels: review:frontend

#2894 feat(refs T35963): Add localisation and phases to statement meta
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaMultiselect.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_statement_segments_list.html.twig
Labels: review:frontend, type:story

#2946 T dplan11397 object manager
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementFragmentService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Repository/ContextualHelpRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureBehaviorDefinitionRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureUiDefinitionRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ReportRepository.php
  demosplan/DemosPlanCoreBundle/Repository/StatementFormDefinitionRepository.php
  demosplan/DemosPlanCoreBundle/Repository/TagRepository.php
  demosplan/DemosPlanCoreBundle/Repository/TagTopicRepository.php
Labels: type:bug, review:backend

#2942 feature (ref dplan-11397): remove return type in phpdoc when return i…
  demosplan/DemosPlanCoreBundle/Repository/AddressBookEntryRepository.php
  demosplan/DemosPlanCoreBundle/Repository/BoilerplateCategoryRepository.php
  demosplan/DemosPlanCoreBundle/Repository/BoilerplateGroupRepository.php
  demosplan/DemosPlanCoreBundle/Repository/BoilerplateRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ContextualHelpRepository.php
  demosplan/DemosPlanCoreBundle/Repository/CountyRepository.php
  demosplan/DemosPlanCoreBundle/Repository/DevelopmentUserStoryVoteRepository.php
  demosplan/DemosPlanCoreBundle/Repository/DraftStatementVersionRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ElementsRepository.php
  demosplan/DemosPlanCoreBundle/Repository/GdprConsentRepository.php
  demosplan/DemosPlanCoreBundle/Repository/GisLayerCategoryRepository.php
  demosplan/DemosPlanCoreBundle/Repository/InstitutionMailRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ManualListSortRepository.php
  demosplan/DemosPlanCoreBundle/Repository/MapRepository.php
  demosplan/DemosPlanCoreBundle/Repository/MunicipalityRepository.php
  demosplan/DemosPlanCoreBundle/Repository/NotificationReceiverRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ParagraphRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ParagraphVersionRepository.php
  demosplan/DemosPlanCoreBundle/Repository/PriorityAreaRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  demosplan/DemosPlanCoreBundle/Repository/ReportRepository.php
  demosplan/DemosPlanCoreBundle/Repository/SlugRepository.php
  demosplan/DemosPlanCoreBundle/Repository/StatementVoteRepository.php
  demosplan/DemosPlanCoreBundle/Repository/UserRepository.php
  demosplan/DemosPlanCoreBundle/Traits/RepositoryLegacyShizzle.php
Labels: type:bug, review:backend

#2976 chore (refs DPLAN-11439): Distinct route for ai api file access to allow jwt authentication
  demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
Labels: review:backend

#2974 fix(refs DPLAN-11457): Remove "Dead" Code
  client/js/components/map/publicdetail/Map.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
Labels: type:bug, review:frontend

#2972 feat(DPLAN-3306): move pagionation to the sticky element
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend, quick-win

#2981 chore: update php vendors
  composer.lock
Labels: review:backend

#2982 fix (refs DPLAN-15514): bump demosplan addon
  composer.lock
Labels: review:backend

#2992 fix: Change type of Quotes to work within Quotes
  tests/frontend/unit/ParticipationPhases.spec.js
Labels: type:bug, review:frontend, quick-win

#2986 chore: remove menu highlighting that is not used any more
  composer.lock
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  demosplan/DemosPlanCoreBundle/Permissions/Permission.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Permissions/ProjectPermissions.php
  tests/backend/core/Core/Unit/Entity/PermissionTest.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
  tests/backend/core/Statement/Functional/StatementAnonymizeServiceTest.php
  tests/backend/core/Statement/Functional/StatementHandlerTest.php
Labels: review:backend

#2977 feat(refs DPLAN-11448): Fix split statement
  client/js/components/statement/splitStatement/SplitStatementView.vue
Labels: type:bug, review:frontend

#2931 feature (ref dplan-11397): define questionhelper as a type of variable
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonBuildFrontendCommand.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonUninstallCommand.php
Labels: type:bug, review:backend

#2985 F dplan 11443 adjust resource types map section
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Entity/Setting.php
  demosplan/DemosPlanCoreBundle/Logic/ApiRequest/ResourceType/ResourceTypeStore.php
  demosplan/DemosPlanCoreBundle/Logic/ContentService.php
  demosplan/DemosPlanCoreBundle/Repository/SettingRepository.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/ProcedureMapSettingResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureSettingsResourceType.php
Labels: review:backend

#2971 fix (DPLAN-11429): fix false mandatory field error
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  tests/backend/core/Procedure/Functional/ServiceStorageTest.php
Labels: review:backend

#2970 chore (refs DPLAN-11413): add DpContextualHelp instead of v-tool…
  client/js/InitVue.js
  client/js/components/map/publicdetail/DpPublicDetail.vue
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
  client/js/components/procedure/basicSettings/DpMasterBasicSettings.vue
  client/js/components/statement/DpPublicDetailNoMap.vue
  client/js/components/statement/assessmentTable/DetailView/DetailView.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_tooltip.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_dashboard.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_procedure_proposal.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_masters_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail_form_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/Extension/contextual_help.html.twig
  templates/bundles/DemosPlanCoreBundle/UI/form/label.html.twig
Labels: review:frontend, type:enhancement
