Repository demos-europe/demosplan-core, pull requests merged in 2025-08, with the labels that each got.

#4973 fix: increase search field width
  client/js/components/procedure/admin/AdministrationProceduresList.vue
Labels: review:frontend, review:backend, quick-win

#4850 refactor (refs DPLAN-4128): delete CoreService dependencies from Cont…
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/BounceChecker.php
  demosplan/DemosPlanCoreBundle/Logic/ContentService.php
  demosplan/DemosPlanCoreBundle/Logic/Customer/CustomerDeleter.php
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphService.php
  demosplan/DemosPlanCoreBundle/Logic/Document/SingleDocumentService.php
  demosplan/DemosPlanCoreBundle/Logic/EditorService.php
  demosplan/DemosPlanCoreBundle/Logic/EmailAddressService.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeDisplayService.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeRollbackVersionService.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
  demosplan/DemosPlanCoreBundle/Logic/Faq/FaqService.php
  demosplan/DemosPlanCoreBundle/Logic/FloodControlService.php
  demosplan/DemosPlanCoreBundle/Logic/Forum/ForumService.php
  demosplan/DemosPlanCoreBundle/Logic/Help/HelpService.php
  demosplan/DemosPlanCoreBundle/Logic/Map/MapService.php
  demosplan/DemosPlanCoreBundle/Logic/News/ProcedureNewsService.php
  demosplan/DemosPlanCoreBundle/Logic/OpenGeoDbService.php
  demosplan/DemosPlanCoreBundle/Logic/Orga/OrgaDeleter.php
  demosplan/DemosPlanCoreBundle/Logic/OriginalStatementAnonymizationService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureCategoryService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureListService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureToLegacyConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureTypeService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/UserFilterSetService.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ExportReportService.php
  demosplan/DemosPlanCoreBundle/Logic/ResourcePersister.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/DraftsInfoService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssignService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/CountyService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/GdprConsentRevokeTokenService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/MunicipalityService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/OriginalStatementCsvExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/PriorityAreaService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementAnonymizeService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementClusterService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementCopyAndMoveService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementToLegacyConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/SubmitterService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/TagService.php
  demosplan/DemosPlanCoreBundle/Logic/StatementAttachmentService.php
  demosplan/DemosPlanCoreBundle/Logic/User/AddressBookEntryService.php
  demosplan/DemosPlanCoreBundle/Logic/User/BrandingService.php
  demosplan/DemosPlanCoreBundle/Logic/User/MasterToebService.php
  demosplan/DemosPlanCoreBundle/Logic/User/RoleService.php
  demosplan/DemosPlanCoreBundle/Logic/Workflow/PlaceService.php
  demosplan/DemosPlanCoreBundle/Services/Queries/SqlQueriesService.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/CustomFieldCreator.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/CustomFieldValueCreator.php
  tests/backend/core/Core/Functional/HoneypotTest.php
  tests/backend/core/News/Functional/ProcedureNewsServiceTest.php
Labels: review:backend, type:enhancement

#5016 fix: Time based procedure phase switch (refs DPLAN-16177)
  CHANGELOG.md
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/08/Version20250803194156.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/08/Version20250805123542.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#4970 feat(refs dplan-14969, #AB 23560): Add timer and session expiration warnings
  CHANGELOG.md
  client/js/InitVue.js
  client/js/components/shared/SessionTimer.vue
  client/js/store/core/NotificationStoreAdapter.js
  client/js/store/core/Notify.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/js/dplan.settings.js.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#4980 Fix null safety issues in UserRepository
  demosplan/DemosPlanCoreBundle/Repository/UserRepository.php
Labels: review:backend

#5021 F dplan-14969 validate keycloak in env
  demosplan/DemosPlanCoreBundle/EventListener/ExpirationTimestampRequestListener.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/LogoutSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/User/OzgKeycloakLogoutManager.php
Labels: type:bug, type:story

#5005 feat: add Azure OAuth authentication for provisioned users
  client/js/components/user/IdpLoginForm/IdpLoginForm.vue
  demosplan/DemosPlanCoreBundle/Controller/Platform/AzureController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/alternative_login.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4957 Add command to configure procedure types based on templates
  demosplan/DemosPlanCoreBundle/Command/ApplyProcedureTypeTemplateCommand.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Procedure/ProcedureTypeFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/Statement/StatementFormDefinitionFactory.php
  tests/backend/core/Core/Functional/Command/ConfigureProcedureTypeCommandSimpleTest.php
  tests/backend/core/Core/Functional/Command/ConfigureProcedureTypeCommandTest.php
Labels: review:backend

#5025 fix(refs:DPLAN-16180): increase icon css specificity
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_procedurelist.scss
Labels: type:bug, review:frontend

#5029 fix: implement dynamic session handler factory for Redis/Database support
  .env
  CHANGELOG.md
  composer.json
  composer.lock
  config/packages/framework.yaml
  config/services.yml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserController.php
  demosplan/DemosPlanCoreBundle/Logic/DatabaseSessionHandler.php
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Logic/SessionHandlerFactory.php
Labels: review:backend

#5014 F dplan-16008 update custom fields
  CHANGELOG.md
  demosplan/DemosPlanCoreBundle/CustomField/AbstractCustomField.php
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldInterface.php
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldOption.php
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldValue.php
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldValuesList.php
  demosplan/DemosPlanCoreBundle/CustomField/RadioButtonField.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/CustomFields/CustomFieldConfigurationFactory.php
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/CustomFields/CustomFieldOptionFactory.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/07/Version20250723134332.php
  demosplan/DemosPlanCoreBundle/Logic/EntityContentChangeService.php
  demosplan/DemosPlanCoreBundle/Repository/CustomFieldJsonRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomFieldResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureTemplateResourceType.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/CustomFieldFactory.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/CustomFieldUpdater.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/CustomFieldValueCreator.php
  tests/backend/core/Core/Functional/EntityContentChangeServiceTest.php
  tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/SegmentBulkEditorServiceTest.php
  tests/backend/core/CustomField/CustomFieldUpdaterTest.php
  tests/backend/core/Procedure/Functional/ProcedureDeleterTest.php
Labels: review:backend, type:story

#5055 fix(refs DPLAN-16010): Add check for data before using it
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
Labels: type:bug, review:frontend

#5027 feat(refs: DPLAN-16008): update customField dialogs for customField changes
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: review:frontend, type:story

#5064 f DPLAN-16340 remove join on strings
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
Labels: review:frontend

#5074 f DPLAN-16339 remove extra closing brace
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: quick-win

#5091 fix(refs:DPLAN-16246): fix TW class syntax
  client/js/components/procedure/admin/InstitutionTagManagement/TagListItem.vue
Labels: type:bug, review:frontend, quick-win

#5092 fix(refs DPLAN-16193): change buttons in layer and organisation lists
  client/js/components/map/admin/AdminLayerList.vue
  client/js/components/procedure/admin/AdministrationMemberList.vue
  client/js/components/procedure/admin/DpAddOrganisationList.vue
Labels: type:bug, review:frontend

#5095 chore(refs dplan-15846): Fix linting errors in LayerSettings
  client/js/components/map/admin/LayerSettings.vue
Labels: review:frontend

#5003 Picked feat dplan 16237 add configurable feedback control for public participation
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaEmail.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaSnailMailOrEmail.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/07/Version20250703101620.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureToLegacyConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail_form_personal_data.html.twig
  tests/backend/core/Core/Functional/DynamicTransformerTest.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#5096 fix(refs DPLAN-16415): change cancel button in add organisation dialog
  client/js/components/procedure/admin/DpAddOrganisationList.vue
Labels: type:bug, review:frontend

#5101 fix(refs DPLAN-16206): put v-model to name input
  client/js/components/procedure/admin/NewBlueprintForm.vue
Labels: type:bug, review:frontend

#5103 fix(refs dplan-16226): Add two-way data binding to email input in DpNewProcedure
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
Labels: type:bug, review:frontend

#5122 fix(refs dplan-16022): Use string values for checkbox in StatementModal
  client/js/components/statement/publicStatementModal/StatementModal.vue
Labels: type:bug, review:frontend

#5123 fix(refs DPLAN-16190): add reset of selection after deleting elements
  client/js/components/procedure/admin/AdministrationMemberList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/OrganisationTable.vue
Labels: type:bug, review:frontend

#5126 fix(refs:DPLAN-15507): use correct word for tag topic
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend, quick-win

#5065 f DPLAN-16398 improve email footer replacement
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_member_email.html.twig
Labels: review:backend

#5127 fix(refs DPLAN-16049): change height of metadata menu container
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  yarn.lock
Labels: type:bug, review:frontend

#5077 Fix(DPLAN-16341): fix users creation organisation dropdown
  client/js/components/user/DpUserList/DpUserFormFields.vue
  client/js/store/user/UserFormFields.js
Labels: review:frontend

#5142 fix(refs:DPLAN-16428): use v-model for inputs
  client/js/components/procedure/basicSettings/ProcedureCoordinateGeolocation.vue
Labels: type:bug, review:frontend

#5140 fix(DPLN-16342): issue by displaying documents tree list
  client/js/components/document/ElementsList.vue
Labels: quick-win

#5154 chore: bump masterportalapi to v2.50.0, ol to 10.6.0
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: review:frontend
