Repository demos-europe/demosplan-core, pull requests merged in 2025-04, with the labels that each got.

#4472 test(refs DPLAN-15256): fix several jest tests
  client/js/VueConfigLocal.js
  client/js/components/statement/StatementExportModal.vue
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/DpEditSelectedItemsMenu.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsFragments.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/ExportModal.vue
  client/js/components/statement/assessmentTable/TocView/SearchAndSorting.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  jest.config.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_filter.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_view.html.twig
  tests/frontend/unit/DpAdminLayerList.spec.js
  tests/frontend/unit/DpAutofillSubmitterData.spec.js
  tests/frontend/unit/DpBulkEditStatement.spec.js
  tests/frontend/unit/DpClaim.spec.js
  tests/frontend/unit/DpEditFieldMultiSelect.spec.js
  tests/frontend/unit/DpLayerLegend.spec.js
  tests/frontend/unit/DpProcedureCoordinateInput.spec.js
  tests/frontend/unit/DpPublicLayerList.spec.js
  tests/frontend/unit/DpPublicLayerListCategory.spec.js
  tests/frontend/unit/DpPublicStatement.spec.js
  tests/frontend/unit/ExportModal.spec.js
  tests/frontend/unit/FilterModalSelectItem.spec.js
  tests/frontend/unit/NewTagForm.spec.js
  tests/frontend/unit/ParticipationPhases.spec.js
  tests/frontend/unit/SearchModal.spec.js
  tests/frontend/unit/StatementExportModal.spec.js
  tests/frontend/unit/Status.spec.js
  tests/frontend/unit/StatusBadge.spec.js
  tests/frontend/unit/__snapshots__/DpProcedureCoordinateInput.spec.js.snap
  tests/frontend/unit/__snapshots__/SearchModal.spec.js.snap
  tests/frontend/unit/store/Filter.spec.js
  tests/frontend/unit/store/Layers.spec.js
  tests/frontend/unit/store/Notify.spec.js
  tests/frontend/unit/store/Statement.spec.js
Labels: review:frontend

#4493 b(refs:DPLAN-15164): radio btn spacing
  client/js/components/procedure/DpSearchProcedures.vue
Labels: type:bug, review:frontend

#4452 feat (refs AB#22794): implement AVScan via remote socket
  .env
  CHANGELOG.md
  config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Tools/VirusCheckSocket.php
  tests/backend/core/Core/Unit/Tools/VirusCheckSocketTest.php
Labels: review:backend

#4521 f DPLAN-15355 delete slugs when relevant orga or procedure is deleted
  demosplan/DemosPlanCoreBundle/Logic/Orga/OrgaDeleter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureDeleter.php
Labels: review:backend

#4522 b(refs: DPLAN-12821) change abort route
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: review:frontend

#4527 b(refs: DPLAN-15374) Add Translator.trans function to confirm texts
  client/js/components/statement/listStatements/ListStatements.vue
Labels: type:bug, review:frontend

#4524 bug (refs DPLAN-15337): Use dpDraggable
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
  client/js/store/statement/Filter.js
  tests/frontend/unit/DpBulkEditStatement.spec.js
  tests/frontend/unit/StatementExportModal.spec.js
Labels: type:bug, review:frontend

#4534 bug(refs DPLAN-15384): Add condition for menu entry final email
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
Labels: type:bug, review:frontend, quick-win

#4535 B dplan 15049 get config default map fields
  demosplan/DemosPlanCoreBundle/Logic/Map/CoordinateJsonConverter.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureMapSettingResourceType.php
  tests/backend/core/Procedure/Functional/ProcedureMapSettingTest.php
Labels: type:bug, review:backend

#4541 fix: Require location always.
  client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue
Labels: type:bug, review:frontend

#4543 DPLAN-15259 bump addon auto-install versions
  composer.json
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Logic/User/OrgaService.php
Labels: review:backend

#4545 b(refs: DPLAN-15174) add margin for more space between the elements
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/public_statement.html.twig
Labels: type:bug, review:frontend

#4546 b(refs: DPLAN-15174) add margin for more space between the elements
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
Labels: type:bug, review:frontend

#4533 fix(DPLAN-15276): missing parentheses in a function
  client/js/components/faq/DpFaqItem.vue
Labels: review:frontend

#4538 feat(DPLAN-15376): display user information (such as department or role) for a newly added user
  client/js/components/user/DpCreateItem.vue
  client/js/components/user/DpUserList/DpUserFormFields.vue
  client/js/components/user/DpUserList/DpUserListItem.vue
Labels: review:frontend

#4537 B dplan 15192 fix wizard btns
  client/js/lib/procedure/DPWizard.js
Labels: review:frontend

#4550 chore(refs DPLAN-15320, #AB9149): bump demosplan-ui v0.4.11
  package.json
  yarn.lock
Labels: review:frontend

#4552 chore: validate fields before triggering addon calls
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
Labels: review:frontend

#4553 fix(refs dplan-15400): Update Roles after changing the orga
  client/js/components/user/DpUserList/DpUserFormFields.vue
Labels: review:frontend

#4555 cherry-pick from main
  client/js/components/faq/DpFaqItem.vue
  client/js/lib/procedure/DPWizard.js
Labels: review:frontend

#4557 chore(refs DPLAN-15396, #AB9149): bump demosplan-ui to v0.4.12
  package.json
  yarn.lock
Labels: review:frontend

#4556 bug(refs DPLAN-15396): Fix custom search
  client/js/components/procedure/SegmentsList/CustomSearch.vue
  client/js/components/statement/listStatements/CustomSearchStatements.vue
Labels: type:bug, review:frontend

#4561 bug(refs DPLAN-15421): Enable saving button for documents
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaLocationAndDocumentReference.vue
Labels: type:bug, review:frontend

#4564 fix(refs DPLAN-15379): use updated data for checks
  client/js/components/assessmenttable/DpNewStatement.vue
  client/js/store/statement/AssessmentTable.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: type:bug, review:frontend

#4565 feat (ADO-10592): pick add orga service interface and bump demosplan addon
  CHANGELOG.md
  composer.json
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Event/Statement/ManualOriginalStatementCreatedEvent.php
  demosplan/DemosPlanCoreBundle/Logic/User/OrgaService.php
Labels: review:backend

#4559 f-DPLAN-15372 set visibility group id to null when unset overlays
  client/js/components/map/admin/AdminLayerListItem.vue
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/04/Version20250409062943.php
Labels: quick-win

#4566 fix(DPLAN-15267): statementPdfImport page issue
  client/js/components/procedure/imageAnnotator/DpSendBeacon.vue
Labels: review:frontend, quick-win

#4571 F(DPLAN-15450): adjust the addons on the StatementSegment page
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: review:frontend

#4575 chore: bump demosplan-ui from v0.4.12 to v0.4.13
  package.json
  yarn.lock
Labels: review:frontend

#4569 feat: Pass demosplan-ui as prop to addons
  client/js/components/addon/AddonWrapper.vue
  client/js/components/procedure/AdministrationImport/AdministrationImport.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  config.webpack.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/404.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/base_oeb.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/emptybase.html.twig
Labels: type:bug, review:frontend, type:enhancement

#4567 fix(refs #AB9149): remove obsolete .native modifier
  client/js/components/statement/splitStatement/CardPane.vue
  client/js/components/statement/splitStatement/CardPaneCard.vue
  client/js/components/statement/splitStatement/SegmentationEditor.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
Labels: review:frontend

#4576 feat (refs DPLAN-15074): Enable (statement and segment) excel-import
  config/permissions.yml
Labels: quick-win

#4563 B dplan 12531 conditionally render input / delete btn
  client/js/bundles/procedure/administrationListBoilerplate.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_boilerplate.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4577 bug(refs DPLAN-15136): Add v-model for inputs in new statement
  client/js/components/assessmenttable/DpNewStatement.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: type:bug, review:frontend

#4584 bug(refs DPLAN-15488): Fix editable list
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementPublicationAndVoting.vue
  client/js/components/statement/voter/StatementVoter.vue
Labels: type:bug, review:frontend

#4587 bug(refs DPLAN-15495): Fix path for new statement
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
Labels: type:bug, review:frontend

#4511 feat(refs DPLAN-15338, #AB26283): add interface to create segments fields
  client/js/bundles/procedure/administrationCustomFieldsList.js
  client/js/components/procedure/admin/AdministrationCustomFieldsList.vue
  client/js/components/procedure/admin/CreateCustomFieldForm.vue
  config/menus.yml
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_custom_fields_list.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_dashboard.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4544 chore (refs DPLAN-1902): check for malicious headers
  CHANGELOG.md
  demosplan/DemosPlanCoreBundle/EventSubscriber/CsrfSubscriber.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/RatelimitRequestSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/HeaderSanitizerService.php
  demosplan/DemosPlanCoreBundle/Middlewares/TusCors.php
  tests/backend/core/Core/Functional/CsrfSubscriberTest.php
  tests/backend/core/Core/Unit/EventSubscriber/CsrfSubscriberTest.php
  tests/backend/core/Core/Unit/EventSubscriber/RatelimitRequestSubscriberTest.php
  tests/backend/core/Core/Unit/Logic/HeaderSanitizerServiceTest.php
  tests/backend/core/Core/Unit/Middlewares/TusCorsTest.php
Labels: review:backend

#4530 chore: add requestId in logfiles
  config/services.yml
  demosplan/DemosPlanCoreBundle/Monolog/Processor/RequestIdProcessor.php
  tests/backend/core/Monolog/Unit/RequestIdProcessorTest.php
Labels: review:backend

#4539 chore (refs DPLAN-602): invalidate links after usage
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAuthenticationController.php
  demosplan/DemosPlanCoreBundle/Logic/User/UserHasher.php
  tests/backend/core/User/Unit/TokenInvalidationTest.php
  tests/backend/core/User/Unit/UserHasherTokenInvalidationTest.php
Labels: review:backend

#4581 chore: Bump a bunch of Yarn dependencies and clean dependabot.yml
  .github/dependabot.yml
  client/fe/webpack/moduleRules.js
  config.webpack.js
  package.json
  yarn.lock
Labels: review:frontend, dependencies:yarn, type:enhancement

#4594 fix(DPLAN-15284): splitStatement: dropdown menu open direction
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/components/statement/splitStatement/TagSelect.vue
Labels: review:frontend

#4606 fix: inverse side does not exists
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
Labels: review:backend, quick-win

#4610 fix(refs DPLAN-12612): remove toggle for chapter based doc categories
  client/js/components/document/ElementsAdminItem.vue
Labels: type:bug, review:frontend
