Repository demos-europe/demosplan-core, pull requests merged in 2025-07, with the labels that each got.

#4821 fix(DPLAN-11742): console issue when deleting an unregistered public agency
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/unregistered_publicagency_list.html.twig
Labels: review:frontend, quick-win

#4857 fix(refs dplan-16005): Render correct translation in StatementModalRecheck
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#4866 upgrade demosplan-ui
  package.json
  yarn.lock
Labels: review:frontend

#4867 fix(refs dplan-12599): Remove whitespace in map description
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_admin_gislayer_list.html.twig
Labels: type:bug, review:frontend

#4869 fix(DPLAN-16032): use all() instead of get() for array parameters in UserHandler
  demosplan/DemosPlanCoreBundle/Logic/User/UserHandler.php
Labels: type:bug, review:backend

#4880 fix(refs: DPLAN-16053): add contextualHelp to fields of API call
  client/js/store/map/Layers.js
Labels: type:bug, review:frontend, quick-win

#4890 fix(DPLAN-15970): increase JWT token rate limit from 100 to 500 requests
  config/packages/rate_limiter.yaml
Labels: type:bug, review:backend, quick-win

#4888 chore: update php dependencies
  composer.lock
Labels: review:backend

#4781 chore: add caching to nginx
  docker/demosplan-production/nginx.conf.template
Labels: devops

#4898 fix(refs dplan-16070): Use proper Id to set selectedState
  client/js/store/statement/Statement.js
Labels: type:bug, review:frontend

#4887 Fix(dplan-16033): several issues on the organisation list page
  client/js/components/user/DpCreateItem.vue
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
  client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue
  client/js/components/user/DpUserList/DpUserFormFields.vue
  client/js/components/user/DpUserList/DpUserListItem.vue
  tests/frontend/unit/DpBulkEditStatement.spec.js
Labels: review:frontend

#4902 fix(refs: DPLAN-15083): replace VPopover with DpTooltip
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
Labels: type:bug, review:frontend

#4904 fix(refs dplan-15860): Rerender automatically after deleting a SimilarStatementSubmitters entry
  client/js/bundles/procedure/administrationStatementSegmentsList.js
  client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#4882 Feat dplan 16042 add configurable feedback control for public participation
  CHANGELOG.md
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaEmail.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaSnailMailOrEmail.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/07/Version20250703101620.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureToLegacyConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail_form_personal_data.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#4885 fix(refs dplan-16035): Transform geojson for diplan-karte
  client/js/components/map/publicdetail/DiplanKarteWrapper.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
  client/js/lib/map/transformFeature.js
  tests/frontend/unit/transformFeature.test.js
Labels: review:frontend

#4912 fix an error that is preventing the build process
  client/js/components/statement/publicStatementModal/formGroups/FormGroupEvaluationMailViaEmail.vue
Labels: review:frontend

#4917 feat(refs: DPLAN-15854): update diplan-karten to 1.0.1
  package.json
  yarn.lock
Labels: review:frontend

#4920 fix(refs dplan-16090): mobile layout breadcrump
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_pageheader.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/proceduremenu_statements.html.twig
Labels: type:bug, review:frontend

#4919 Fix(DPLAN-15946): Fix(DPLAN-15946): error while changing the FAQ’s status
  client/js/components/faq/DpFaqItem.vue
Labels: review:frontend, quick-win

#4918 fix(refs: DPLAN-16101): filter elements before delete
  client/js/components/document/ElementsAdminList.vue
Labels: type:bug, review:frontend

#4922 fix: resolve critical PHPStan errors
  demosplan/DemosPlanCoreBundle/Application/ConsoleApplication.php
  demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementController.php
  tests/backend/core/Core/Unit/Faker/Provider/ApproximateLengthTextTest.php
Labels: review:backend

#4872 refactor(DPLAN-15945): optimize tag and boilerplate import logic
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/TagService.php
  tests/backend/core/Statement/Functional/StatementHandlerTagImportTest.php
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:backend, type:enhancement

#4936 fix (refs: DPLAN-15999): Use all() method is designed to handle array…
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
Labels: type:bug

#4931 Fix: resolve PHPStan errors preventing runtime exceptions
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
  demosplan/DemosPlanCoreBundle/Command/Data/RemoveUserDataCommand.php
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/StatementFragment.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/TransformMessageBagService.php
  tests/backend/core/Core/Functional/TransformMessageBagServiceTest.php
Labels: review:backend

#4923 fix(refs DPLAN-16080): use search button in DpAutocomplete for small screens
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
Labels: type:bug, review:frontend

#4940 feat (ref: DPLAN-16067) : adjust translation key text
  translations/messages+intl-icu.de.yml
Labels: review:backend, quick-win

#4947 fix: Pass order without gaps
  client/js/components/map/map/DpOlMap.vue
Labels: type:bug, review:frontend

#4726 chore(refs dplan-15761): Reduce root emit in layerlist
  client/js/components/map/admin/AdminLayerList.vue
  client/js/components/map/admin/AdminLayerListItem.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerList.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListCategory.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListLayer.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListWrapper.vue
  client/js/store/map/Layers.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
  tests/frontend/unit/DpAdminLayerList.spec.js
  tests/frontend/unit/store/Layers.spec.js
Labels: review:frontend, type:enhancement

#4950 Fix ProcedurePhase:: initialization
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
Labels: review:backend

#4952 fix(refs: DPLAN-16074): Move getFeatureInfo request to the Frontend
  client/js/components/map/publicdetail/Map.vue
Labels: type:bug, review:frontend

#4926 fix(refs dplan-16085): Add mobile version of StatementModal nav
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImportErrors.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_progress-bar.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_statement.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_display-visibility.scss
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#4953 fix(refs DPLAN-16134): Only send valid fields when requesting Layers
  client/js/components/map/admin/AdminLayerList.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/store/map/Layers.js
Labels: type:bug, review:frontend

#4935 fix(refs: DPLAN-16083): change location popup style for mobile
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
Labels: type:bug, review:frontend

#4939 Fix(DPLAN-15946): error while saving the available groups on the FAQ page
  client/js/components/faq/DpFaqItem.vue
Labels: review:frontend, quick-win

#4958 fix(DPLAN-15849): use dp-inline-notification to display the warning messages
  client/js/components/statement/assessmentTable/CopyStatementModal.vue
  client/js/components/statement/assessmentTable/DpMoveStatementModal.vue
Labels: review:frontend

#4968 B dplan 16159 fix custom search layout
  client/js/components/procedure/SegmentsList/CustomSearch.vue
  client/js/components/statement/listStatements/CustomSearchStatements.vue
Labels: type:bug, review:frontend

#4965 fix(DPLAN-1880): Fix double-login requirement for newly authorized users
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/OzgKeycloakAuthenticator.php
Labels: review:backend

#4966 fix(DPLAN-12647): empty input fields
  client/js/components/procedure/admin/AuthorizedUsersList.vue
Labels: review:frontend

#4969 fix (refs: DPLAN-16094): remove click listener
  client/js/lib/core/libs/touchFriendlyUserbox.js
Labels: type:bug, review:frontend

#4963 fix(refs DPLAN-16160): Add padding left to BTN in side menu
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_sidemenu.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/sidemenu.html.twig
Labels: type:bug, review:frontend

#4974 Fix DPLAN-16144 initialize $key property before accessing
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
Labels: review:backend, quick-win

#4976 fix(refs DPLAN-16172): use modelValue for DpInput
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementEntry.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementSubmitter.vue
Labels: review:frontend, quick-win

#4983 fix (refs: DPLAN-16082): add padding to mobile view
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tabs.scss
Labels: type:bug, review:frontend

#4989 Fix DPLAN-16144 Fix PHP 7.4+ typed property initialization issues
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
Labels: review:backend

#4994 Fix DPLAN-16144 Change direct property access to use getters in copyValuesFromPhase
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedurePhase.php
  tests/backend/core/Document/Functional/ElementsServiceTest.php
Labels: review:backend

#5004 feat: add Azure OAuth authentication for provisioned users
  config/services.yml
  demosplan/DemosPlanCoreBundle/Controller/Platform/AzureController.php
  demosplan/DemosPlanCoreBundle/Logic/AzureUserDataMapper.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/AzureAuthenticator.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/AzureUserBadgeCreator.php
  demosplan/DemosPlanCoreBundle/ValueObject/AzureUserData.php
  demosplan/DemosPlanCoreBundle/ValueObject/AzureUserDataInterface.php
  tests/backend/core/Core/Functional/AzureUserDataTest.php
Labels: review:backend
