Repository demos-europe/demosplan-core, pull requests merged in 2025-02, with the labels that each got.

#4292 feat(refs DPLAN-12969, #AB21841): allow grouping filter options with 'OR' conjunction
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/SegmentsList/FilterFlyoutCheckbox.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
  client/js/store/procedure/FilterFlyout.js
Labels: review:frontend, type:story

#4287 build: bump demosplan-ui to v.0.3.45
  package.json
  yarn.lock
Labels: review:frontend

#4304 chore: Extend eslint config
  eslintrc.js
Labels: review:frontend, type:enhancement

#4293 style: fix linting errors
  client/js/bundles/core/publicDetail.js
  client/js/bundles/faq/faqlist.js
  client/js/bundles/procedure/administrationDashboard.js
  client/js/bundles/procedure/institutionTagManagement.js
  client/js/bundles/statement/fragmentStatement.js
  client/js/bundles/statement/listStatements.js
  client/js/bundles/user/alternativeLogin.js
  client/js/bundles/user/citizenRegisterForm.js
  client/js/bundles/user/resetPassword.js
  client/js/components/faq/DpFaqItem.vue
  client/js/components/map/publicdetail/DpPublicDetail.vue
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementPublicationAndVoting.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
  client/js/components/procedure/basicSettings/DpBasicSettings.vue
  client/js/components/statement/assessmentTable/DetailView/DetailView.vue
  client/js/components/statement/assessmentTable/DpEditFieldSingleSelect.vue
  client/js/components/statement/assessmentTable/StatementReplySelect.vue
  client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/components/statement/splitStatement/SegmentationEditor.vue
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/components/statement/statement/StatementPublish.vue
  client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
  client/js/components/user/CustomerSettings/CustomerSettingsMap.vue
  client/js/components/user/DpCreateItem.vue
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue
  client/js/components/user/DpUserList/DpUserFormFields.vue
  client/js/components/user/orgaDataEntry/EmailNotificationSettings.vue
  client/js/components/user/orgaDataEntry/OrganisationCompetence.vue
  client/js/lib/prosemirror/utilities.js
  client/js/store/core/initStore.js
  client/js/store/map/Layers.js
  tests/frontend/unit/ExportModal.spec.js
  tests/frontend/unit/StatusBadge.spec.js
  tests/frontend/unit/__mocks__/MapLayer.mock.js
  tests/frontend/unit/store/Layers.spec.js
  tests/frontend/unit/store/Notify.spec.js
  tests/frontend/unit/store/Statement.spec.js
  tests/frontend/unit/utils.spec.js
Labels: review:frontend

#4306 fix(refs DPLAN-12969, #AB21841): use correct operator
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
Labels: type:bug, review:frontend, type:story

#4308 bug(refs DPLAN-14923): Fix resetting filter
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
Labels: type:bug, review:frontend

#4309 f DS-30 adjust route to get file :
  templates/bundles/DemosPlanCoreBundle/DemosPlanNews/public_newsdetail.html.twig
Labels: review:backend

#4307 feat (refs DPLAN-14844): Allow additional flag per URL to filter by permission
  config/parameters_default.yml
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Logic/DefaultTwigVariablesService.php
  demosplan/DemosPlanCoreBundle/Permissions/Permissions.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
Labels: review:backend

#4312 fix(refs DPLAN-14938): display correct file size for pictogram upload
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/Extension/fileupload.html.twig
Labels: review:frontend

#4310 fix(refs DPLAN-14736): reduce number of requests
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
  client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue
Labels: type:bug, review:frontend

#4320 bug(refs DPLAN-14849): Add confirm notification for deleting layers
  client/js/store/map/Layers.js
Labels: type:bug, review:frontend

#4325 bug(refs dplan-12673): fix customer settings
  client/js/components/user/CustomerSettings/CustomerSettingsBranding.vue
  client/js/components/user/CustomerSettings/CustomerSettingsSupport.vue
Labels: type:bug, review:frontend

#4328 chore: use named arguments to fix incorrect fileupload params
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, review:backend

#4329 f DPLAN-14951 allow post code with 4 digits
  demosplan/DemosPlanCoreBundle/Validator/PostcodeConstraintValidator.php
Labels: review:backend, quick-win

#4332 chore: improve fileupload twig function documentation
  templates/bundles/DemosPlanCoreBundle/Extension/fileupload.html.twig
Labels: documentation, review:frontend

#4335 f DPLAN-14977 : adjust pictogram min resolution
  config/parameters_default.yml
  translations/messages+intl-icu.de.yml
Labels: review:backend

#4339 f_DPLAN-14943 alter statement validation. Do not assert parentStatementOfSegment is Null by default Group
  composer.json
  composer.lock
  demosplan/DemosPlanCoreBundle/Entity/Statement/Statement.php
  demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
  demosplan/DemosPlanCoreBundle/Validator/StatementValidator.php
Labels: type:bug

#4340 chore: ubuntu 20.04 as a runner is deprecated
  .github/workflows/reviewdog.yml
Labels: devops, quick-win

#4334 feat(refs DPLAN-14634, #AB22463): sort categories + tags by creationDate
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
  demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTag.php
  demosplan/DemosPlanCoreBundle/Entity/User/InstitutionTagCategory.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/InstitutionTagCategoryResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/InstitutionTagResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagCategoryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InstitutionTagResourceType.php
Labels: review:frontend, review:backend, type:enhancement

#4134 F dplan 12013 #2 topical tags
  CHANGELOG.md
  client/js/bundles/procedure/administrationListBoilerplate.js
  client/js/bundles/statement/listTags.js
  client/js/components/procedure/admin/AdministrationPlaces.vue
  client/js/components/procedure/admin/InstitutionTagManagement/NewTagForm.vue
  client/js/components/statement/splitStatement/DpCreateTag.vue
  client/js/components/tags/TagListBulkControls.vue
  client/js/components/tags/TagListEditForm.vue
  client/js/components/tags/TagsCreateForm.vue
  client/js/components/tags/TagsImportForm.vue
  client/js/components/tags/TagsList.vue
  client/js/components/tags/TagsListHeader.vue
  client/js/store/core/initStore.js
  client/js/store/statement/SplitStatementStore.js
  composer.json
  composer.lock
  config/services.yml
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementTagController.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Procedure.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/TagTopic.php
  demosplan/DemosPlanCoreBundle/Event/Procedure/PostNewProcedureCreatedEvent.php
  demosplan/DemosPlanCoreBundle/Event/Statement/ExcelImporterHandleImportedTagsRecordsEvent.php
  demosplan/DemosPlanCoreBundle/Event/Statement/ExcelImporterHandleSegmentsEvent.php
  demosplan/DemosPlanCoreBundle/Event/Statement/ExcelImporterPrePersistTagsEvent.php
  demosplan/DemosPlanCoreBundle/Event/Tag/DeleteTagEvent.php
  demosplan/DemosPlanCoreBundle/Exception/TagInUseException.php
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/RpcTagAndTopicDeleter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  demosplan/DemosPlanCoreBundle/Repository/TagTopicRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/TagResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/TagTopicResourceType.php
  package.json
  templates/bundles/DemosPlanCoreBundle/DemosPlanFaq/faq_admin_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_boilerplate.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
Labels: review:frontend, review:backend, type:story

#4354 bug(refs DPLAN-14790): Extend safelist for purge css
  CHANGELOG.md
  client/fe/config/config.js
Labels: type:bug, review:frontend

#4349 bug(refs DPLAN-14953): Sanitize statement text
  client/js/components/shared/TextContentRenderer.vue
Labels: type:bug, review:frontend

#4350 bug(refs DPLAN-119521): confirm conditionally
  client/js/components/statement/StatementExportModal.vue
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend

#4336 Refac(dplan 12188) no reset button
  client/js/components/user/DpUserList/DpUserList.vue
Labels: review:frontend

#4357 chore(refs DPLAN-14634, #AB22463): bump demosplan-ui from v0.3.45 to v0.3.47
  package.json
  yarn.lock
Labels: review:frontend

#4337 chore: silence user has no password logmessage
  demosplan/DemosPlanCoreBundle/EventListener/DoctrineLoggerListener.php
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
Labels: review:backend, quick-win

#4361 b(refs:DPLAN-12943) STN filter icon
  client/js/components/statement/assessmentTable/DpFilterModal.vue
Labels: review:frontend

#4368 tests: Fix test for StatementExportModal
  tests/frontend/unit/StatementExportModal.spec.js
Labels: review:frontend, type:enhancement

#4363 fix DPLAN-15021 jump to next record when detecting all elements of da…
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementHandler.php
  tests/backend/core/Core/Functional/MatomoApiTest.php
  tests/backend/core/Core/Functional/RatelimitRequestSubscriberTest.php
  tests/backend/core/Map/Functional/MapHandlerTest.php
  tests/backend/core/Statement/Functional/res/tagTopics.csv
Labels: type:bug, review:backend

#4370 chore(refs DPLAN-14634, #AB22463): bump demosplan-ui from v0.3.47 to v0.3.48
  package.json
  yarn.lock
Labels: review:frontend

#4344 feat(refs DPLAN-14634, #AB22463): add flyout for selecting filter categories
  client/js/components/procedure/SegmentsList/CustomSearch.vue
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
  client/js/store/procedure/FilterFlyout.js
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#4372 feat (DPLAN-14868): xlsx export assessmenttable
  client/js/components/statement/assessmentTable/ExportModal.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Labels: review:frontend, review:backend, quick-win, type:story

#4373 fix(DPLAN-15055): display a confirm message before deleting a Tag/Topic
  CHANGELOG.md
  client/js/components/tags/TagListEditForm.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4374 feat DPLAN-15068 Add template for tag topic import
  client/js/components/tags/TagsImportForm.vue
  demosplan/DemosPlanCoreBundle/Resources/public/files/tag_topics_import_template.csv
Labels: review:frontend

#4369 feat(refs DPLAN-14634): persist selected filters via localStorage
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
Labels: review:frontend

#4360 fix(DPLAN-15035): issue with saving the unchanged Tag/Topic title
  CHANGELOG.md
  client/js/components/tags/TagListEditForm.vue
  client/js/components/tags/TagsList.vue
Labels: review:frontend

#4345 f_DPLAN-14976 limit user administration scope for organisation-administration to own orga via new permission
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/AdministratableUserResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
  translations/messages+intl-icu.de.yml
Labels: type:bug

#4375 chore (refs DPLAN-14978): create report entries and dispatch events
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
Labels: type:bug, review:backend

#4384 refactor parameters in the statement request
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend

#4378 chore: Bump Stylelint@16.14.1 and run lint --fix
  demosplan/DemosPlanCoreBundle/Resources/client/scss/_settings.font-awesome.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_map.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_nav.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_procedurelist.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_sidemenu.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_skeleton-box.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_statement-meta-box.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_support.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_tiptap.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_a11y-datepicker.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_box.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_button.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_modal.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_wizard.scss
  demosplan/DemosPlanCoreBundle/Resources/client/scss/utility/_color.scss
  package.json
  stylelint.config.js
  yarn.lock
Labels: review:frontend, type:enhancement

#4388 chore: lower stdout noise in maintenance command, improve logging
  demosplan/DemosPlanCoreBundle/Command/MaintenanceCommand.php
  demosplan/DemosPlanCoreBundle/Controller/Platform/FileController.php
Labels: review:backend

#4297 F dplan 14866 export synopsis without personal data
  CHANGELOG.md
  client/js/components/statement/StatementExportModal.vue
  client/js/components/statement/listStatements/ListStatements.vue
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentExporterFileNameGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  tests/backend/core/Statement/Functional/SegmentsByStatementsExporterTest.php
Labels: review:frontend, review:backend

#4391 chore: Fix linter issues
  client/js/bundles/procedure/administrationListBoilerplate.js
  client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
  client/js/components/shared/TextContentRenderer.vue
  client/js/components/statement/splitStatement/DpCreateTag.vue
  client/js/components/tags/TagListEditForm.vue
  client/js/components/tags/TagsCreateForm.vue
  client/js/components/tags/TagsImportForm.vue
  client/js/components/tags/TagsList.vue
  client/js/components/user/DpUserList/DpUserList.vue
  client/js/store/core/initStore.js
  client/js/store/map/Layers.js
  client/js/store/procedure/FilterFlyout.js
  tests/frontend/unit/store/Notify.spec.js
Labels: review:frontend, type:enhancement

#4371 Fix or skip BE tests
  demosplan/DemosPlanCoreBundle/ResourceTypes/TagTopicResourceType.php
  tests/backend/core/Core/Functional/Command/AddonAutoinstallCommandTest.php
  tests/backend/core/Core/Unit/Logic/PermissionsTest.php
  tests/backend/core/Core/Unit/Utilities/Twig/RouterTest.php
  tests/backend/core/Document/Unit/DocumentBundleImporterTest.php
  tests/backend/core/Import/ZipImportServiceTest.php
  tests/backend/core/News/Functional/GlobalNewsHandlerTest.php
  tests/backend/core/Procedure/Functional/ProcedureServiceTest.php
  tests/backend/core/Report/Functional/ReportMessageConverterTest.php
  tests/backend/core/Statement/Functional/ImageLinkConverterTest.php
Labels: review:backend, type:enhancement

#4395 Fix(dplan-15103): split statement view: show new tag in the topic list after creating
  CHANGELOG.md
  client/js/components/statement/splitStatement/DpCreateTag.vue
Labels: review:frontend

#4401 chore (refs AB#20399): use symfony to set trusted proxies
  config/packages/framework.yaml
  config/parameters_default.yml
  demosplan/DemosPlanCoreBundle/Application/FrontController.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/TrustedProxiesSubscriber.php
  demosplan/DemosPlanCoreBundle/Resources/config/GlobalConfig.php
Labels: review:backend

#4396 B dplan 2859 custom search stn
  client/js/components/statement/assessmentTable/SearchModal/SearchModal.vue
  client/js/components/statement/listStatements/CustomSearchStatements.vue
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/components/statement/listStatements/availableFilterFields.json
Labels: review:frontend

#4403 fix DPLAN-15092 Use $pathStartResourceType as this buildConditions me…
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Labels: type:bug

#4376 add missed onDelete cascade to Boilerplate and BoilerplateCategory
  demosplan/DemosPlanCoreBundle/Entity/Procedure/Boilerplate.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/BoilerplateCategory.php
  tests/backend/core/Procedure/Functional/BoilerplateServiceTest.php
Labels: type:bug, review:backend

#4404 fix(DPLAN-12263): the item was still displaying in the list after deleting it
  client/js/components/statement/listStatements/ListStatements.vue
Labels: review:frontend
