Repository demos-europe/demosplan-core, pull requests merged in 2025-09, with the labels that each got.

#4603 style(refs: DPLAN:15522): adjust custom event names
  client/js/components/document/ElementsList.vue
  client/js/components/map/map/DpOlMapLayerVector.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/map/publicdetail/controls/CustomLayer.vue
  client/js/components/map/publicdetail/controls/MapTools.vue
  client/js/components/map/publicdetail/controls/layerlist/DpPublicLayerListWrapper.vue
  client/js/components/map/publicdetail/controls/legendList/DpLayerLegend.vue
  client/js/components/news/DpNewsItemStatus.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/procedure/basicSettings/DpProcedureCoordinate.vue
  client/js/components/procedure/basicSettings/ProcedureCoordinateGeolocation.vue
  client/js/components/procedure/imageAnnotator/DpLabelModal.vue
  client/js/components/procedure/publicindex/drawer/Drawer.vue
  client/js/components/procedure/publicindex/drawer/Search.vue
  client/js/components/report/DpReportGroup.vue
  client/js/components/statement/DpBoilerPlate.vue
  client/js/components/statement/DpBoilerPlateModal.vue
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/DpAssessmentTableCard.vue
  client/js/components/statement/assessmentTable/DpEditField.vue
  client/js/components/statement/assessmentTable/DpFilterModal.vue
  client/js/components/statement/assessmentTable/DpFragmentList.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/FilterModalSelectItem.vue
  client/js/components/statement/assessmentTable/Fragment.vue
  client/js/components/statement/assessmentTable/TableCardFlyoutMenu.vue
  client/js/components/statement/assessmentTable/TocView/AssessmentTableToc.vue
  client/js/components/statement/fragment/Edit.vue
  client/js/components/statement/fragmentList/Fragment.vue
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTableItem.vue
  client/js/components/statement/publicStatementLists/DpPublicStatement.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  client/js/components/statement/publicStatementModal/formGroups/FormGroupMapReference.vue
  client/js/components/statement/segments/DpInsertableRecommendation.vue
  client/js/components/statement/splitStatement/DpCreateTag.vue
  client/js/components/statement/splitStatement/FloatingContextButton.vue
  client/js/components/statement/splitStatement/SearchSelect.vue
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/components/statement/statement/DpAutofillSubmitterData.vue
  client/js/components/statement/statement/SelectStatementCluster.vue
  client/js/components/user/DpMasterToebList.vue
  client/js/components/user/DpMasterToebList/DpDeleteMasterToeb.vue
  client/js/components/user/DpMasterToebList/DpFilterMasterToeb.vue
  client/js/components/user/DpMasterToebList/DpNewMasterToeb.vue
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/components/user/DpOrganisationList/DpOrganisationListItem.vue
  client/js/components/user/DpTableCardList/DpTableCardListHeader.vue
  client/js/components/user/DpUserListExtended.vue
  client/js/components/user/DpUserListExtendedItem.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_filter.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
Labels: review:frontend

#5156 fix: rename data-cy attribute in the action box to be consistent with…
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/includes/actionbox.html.twig
Labels: review:frontend

#5172 fix(refs DPLAN-16414): provide index again
  client/js/components/statement/assessmentTable/DpTable.vue
Labels: review:frontend

#5174 bump demosplan-addon from v0.59 to v0.60
  composer.json
Labels: review:backend, quick-win

#5177 bump demosplan-addon from v0.59 to v0.60
  composer.lock
Labels: review:backend, quick-win

#5173 fix: reset padding only for layout__item
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/_proceduresearch.scss
Labels: review:frontend, quick-win

#5179 chore: odt export assessmenttable
  CHANGELOG.md
  client/js/components/statement/assessmentTable/ExportModal.vue
  config/parameters_default.yml
  config/permissions.yml
  config/services.yml
  config/statement/assessment_export_options.yml
  demosplan/DemosPlanCoreBundle/Controller/Statement/StatementExportController.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceOutput.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocumentWriterSelector.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Export/OdtHtmlProcessor.php
  demosplan/DemosPlanCoreBundle/Logic/FileResponseGenerator/DocxResponseGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/StyleInitializer.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentExportOptions.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentHandler.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableDocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableFileExporterAbstract.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTablePdfExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableZipExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/OriginalStatementExporter.php
  tests/backend/core/Logic/Export/DocumentWriterSelectorTest.php
  tests/backend/core/Logic/Export/DocxExporterOdtTest.php
  tests/backend/core/Logic/Export/OdtHtmlProcessorTest.php
  tests/backend/core/SegmentExport/StyleInitializerTest.php
  tests/backend/core/Statement/Functional/StatementExportTest.php
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend

#5192 fix(DPLAN-16347): unable to display fragments - v2
  client/js/store/statement/Fragment.js
Labels: review:frontend

#5213 Fix SonarCloud quality gate violations
  client/js/components/statement/publicStatementModal/StatementModal.vue
  config/services.yml
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureHandler.php
  tests/backend/core/Procedure/Functional/ProcedureHandlerTest.php
Labels: review:frontend, review:backend

#5226 fix(refs dplan-16320): Use modelValue for DpInput in single-document_admin_edit
  templates/bundles/DemosPlanCoreBundle/DemosPlanDocument/single_document_admin_edit.html.twig
Labels: type:bug, review:frontend

#5229 b_(refs DPLAN-16547): adjusted phase filtering
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:enhancement

#5234 f DPLAN-16042 : Add proceduresettings.publicParticipationFeedbackEnabled check to feedback block
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
Labels: review:frontend

#5235 f DPLAN-16042 : Add proceduresettings.publicParticipationFeedbackEnabled check to feedback block
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
Labels: review:frontend

#5248 fix(refs DPLAN-16591): import cookie banner styles
  client/css/tailwind.css
Labels: review:frontend

#5170 feat(refs DPLAN-15947): make custom fields deletable
  CHANGELOG.md
  client/js/components/procedure/admin/AdministrationCustomFieldsList.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#5261 feat(refs:DPLAN-15660): turn off scales when diplankarte
  client/js/components/map/admin/MapAdmin.vue
Labels: review:frontend, quick-win, type:story

#5262 feat(refs dplan-16594, #AB41902): Connect diplan-karten to admin dialog - basic settings
  client/js/bundles/map/publicDetailDiplanKarte.js
  client/js/components/map/publicdetail/diplankarte/DiplanKarteWrapper.vue
  client/js/components/map/publicdetail/diplankarte/config/layerConfig.json
  client/js/components/map/publicdetail/diplankarte/config/portalConfig.json
  client/js/lib/map/transformFeature.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
Labels: review:frontend, type:story

#5285 fix: add prosemirror resolutions
  package.json
  yarn.lock
Labels: type:bug, dependencies
