Repository demos-europe/demosplan-core, pull requests merged in 2025-06, with the labels that each got.

#4725 chore: Skip Tests in PublicDetailLayerList
  tests/frontend/unit/DpPublicLayerListCategory.spec.js
  tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap
Labels: review:frontend

#4723 feat(refs DPLAN-13005): refactor and expand search function
  client/js/components/procedure/admin/DpAddOrganisationList.vue
  demosplan/DemosPlanCoreBundle/ResourceTypes/InvitablePublicAgencyResourceType.php
  tests/backend/core/Core/Functional/Command/DeleteOrgaCommandTest.php
Labels: review:frontend, review:backend, type:story

#4756 fix: remove obsolete component
  client/js/bundles/map/publicDetailDiplanKarte.js
Labels: review:frontend

#4683 feat(refs DPLAN-15588, #AB28108): use diplan-karten in public detail
  .yarnrc.yml
  CHANGELOG.md
  client/js/bundles/map/publicDetailDiplanKarte.js
  client/js/components/map/publicdetail/DiplanKarteWrapper.vue
  client/js/components/map/publicdetail/Map.vue
  client/js/components/procedure/publicindex/map/Map.vue
  composer.json
  config/packages/nelmio_security.yaml
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Command/ElasticsearchPopulateCommand.php
  docker/build.sh
  docker/demosplan-production/Dockerfile
  package.json
  templates/bundles/DemosPlanCoreBundle/DemosPlanMap/map_public_participation_detail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
  yarn.lock
Labels: review:frontend

#4760 fix DPLAN-15776: Display FileNames when exporting Original stn as csv, also Stn as excel
  demosplan/DemosPlanCoreBundle/Logic/Statement/Exporter/StatementArrayConverter.php
  tests/backend/core/Statement/Export/StatementArrayConverterTest.php
Labels: type:bug

#4740 chore: fix unique constraint failure in test
  tests/backend/core/Core/Unit/Logic/Segment/RpcBulkEditor/SegmentBulkEditorServiceTest.php
Labels: review:backend

#4761 refactor(refs DPLAN-15243, #AB25724): use filter group
  client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
  demosplan/DemosPlanCoreBundle/Logic/Segment/RpcBulkEditor/RpcStatementIdLoader.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/Exporter/StatementArrayConverter.php
  tests/backend/core/Statement/Functional/StatementExportTest.php
Labels: review:frontend, review:backend, type:enhancement

#4704 f-DPLAN-11632 Case insensitive email address comparison
  demosplan/DemosPlanCoreBundle/Repository/EmailAddressRepository.php
Labels: type:bug, review:backend

#4782 feat(refs DPLAN-15771, #AB29551): add selectAll to layers
  client/js/components/map/admin/LayerSettings.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
  client/js/components/statement/listStatements/ListStatements.vue
  client/js/components/user/DpTableCardList/DpTableCardListHeader.vue
  client/js/components/user/DpUserListExtended.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_master.html.twig
Labels: review:frontend, type:story

#4741 chore: fix occasionally failing elements test
  tests/backend/core/Document/Functional/ElementsServiceTest.php
Labels: review:backend

#4719 feat(refs DPLAN-13004, #AB17835): allow filtering of institution tags
  CHANGELOG.md
  client/js/bundles/procedure/administrationNewMemberList.js
  client/js/components/procedure/admin/DpAddOrganisationList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
  client/js/lib/procedure/FilterFlyout/filterHelpers.js
  client/js/lib/procedure/FilterFlyout/filterStorage.js
Labels: review:frontend

#4759 fix: redirect to 404 instead of missing template
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
Labels: review:backend

#4786 chore: bump demosplan-ui from 0.4.16 to 0.4.17
  package.json
  yarn.lock
Labels: review:frontend

#4785 fix: phpunit tests to run in teamctiy
  tests/backend/core/Core/Functional/Command/DisablePermissionForCustomerOrgaRoleCommandTest.php
  tests/backend/core/Core/Functional/Command/EnablePermissionForCustomerOrgaRoleCommandTest.php
  tests/backend/core/Core/Functional/Command/PermissionForCustomerOrgaRoleCommandTest.php
  tests/backend/core/Core/Functional/StatementSynchronizerTest.php
Labels: review:backend

#4777 DPLAN-15804: include specialties to InvitedPublicAgencyResourceType
  config/json-schema/rpc-invited-institutions-bulk-delete-schema.json
  demosplan/DemosPlanCoreBundle/Logic/RpcInstitutionInvitationRemover.php
  demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/InvitedPublicAgencyResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InvitedPublicAgencyResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ProcedureResourceType.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#4800 chore(refs DPLAN-15256): skip breaking FE Test
  tests/frontend/unit/DpBulkEditStatement.spec.js
Labels: review:frontend, type:enhancement

#4802 fix(DPLAN-2000): add sort param by fetching the list of places
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
Labels: review:frontend, quick-win

#4791 fix(refs: DPLAN-15203): fix save event
  client/js/components/procedure/Shared/SimilarStatementSubmitters/SimilarStatementSubmitters.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementEntry.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaLocationAndDocumentReference.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementSubmitter.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
Labels: type:bug, review:frontend

#4810 fix(refs DPLAN-15821): add spread operator to updateStore
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
Labels: type:bug, review:frontend

#4814 fix(refs: closed DPLAN-15554) Adding data-dp-validate-topic attributes to form fieldsets
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: type:bug, review:frontend

#4795 fix(DPLAN-1987): add c-styled-html class for the editor wrapper
  client/js/components/statement/splitStatement/SegmentationEditor.vue
Labels: review:frontend, quick-win

#4805 fix(DPLAN-2002): change the styling of the map-pin icon if the polygon feature applied to the segment
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: review:frontend

#4796 fix(refs dplan-15818): Enable expanding custom fields options
  client/js/components/procedure/admin/AdministrationCustomFieldsList.vue
Labels: type:bug, review:frontend

#4774 fix(refs DPLAN-15812): Use new Data from DpDraggable
  client/js/components/map/admin/AdminLayerList.vue
  client/js/components/map/admin/AdminLayerListItem.vue
  client/js/components/map/publicdetail/controls/legendList/DpLayerLegendItem.vue
  client/js/store/map/Layers.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_index_filter.html.twig
  tests/frontend/unit/__snapshots__/DpAdminLayerList.spec.js.snap
Labels: type:bug, review:frontend

#4837 fix(refs DPLAN-15912): Role Back imprudent changes.
  client/js/store/map/Layers.js
Labels: type:bug, review:frontend

#4816 fix(DPLAN-1987): add c-styled-html class to dp-edit-field
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
Labels: review:frontend, quick-win

#4742 chore: fix race condition in test when relationship is not loaded yet
  demosplan/DemosPlanCoreBundle/Validator/ProcedureInCoupleAlreadyUsedConstraintValidator.php
Labels: review:backend

#4729 fix: Populate _ms_error_message field with actual mail error details
  demosplan/DemosPlanCoreBundle/Logic/MailService.php
Labels: review:backend

#4844 fix ( ref: DPLAN-584 ) set email while create user : email has to be …
  demosplan/DemosPlanCoreBundle/ResourceTypes/AdministratableUserResourceType.php
Labels: type:bug, review:backend, quick-win

#4831 feat: DPLAN-15078: Add permission field_submit_anonymous_statements
  CHANGELOG.md
  client/js/bundles/procedure/administrationEdit.js
  client/js/components/statement/publicStatementModal/StatementModal.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/06/Version20250623114024.php
  demosplan/DemosPlanCoreBundle/Entity/Procedure/ProcedureSettings.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureToLegacyConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ServiceStorage.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/public_detail.html.twig
  tests/backend/core/Procedure/Functional/ServiceStorageTest.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#4849 fix(refs dplan-12906): Adjust layout of radio btn text
  client/js/components/statement/statement/StatementPublish.vue
Labels: type:bug, review:frontend
