Repository demos-europe/demosplan-core, pull requests merged in 2025-01, with the labels that each got.

#4163 B dplan 13034 use api2 to create user
  client/js/bundles/user/listUser.js
  client/js/components/user/DpCreateItem.vue
  client/js/components/user/DpUserList/DpUserFormFields.vue
  client/js/components/user/DpUserList/DpUserList.vue
  client/js/components/user/DpUserList/DpUserListItem.vue
  client/js/components/user/DpUserListExtended.vue
  client/js/components/user/DpUserListExtendedItem.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Entity/User/Role.php
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/UserResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/AdministratableUserResourceType.php
Labels: type:bug, review:frontend, review:backend

#4199 chore: trim github repository url
  demosplan/DemosPlanCoreBundle/Command/Addon/AddonInstallFromZipCommand.php
Labels: review:backend, quick-win

#4200 feat(refs DPLAN-12968, #AB21840): set margin outside of component
  CHANGELOG.md
  client/js/components/document/ElementsAdminBulkEdit/ElementsAdminBulkEdit.vue
  client/js/components/map/admin/MapAdminScales.vue
  client/js/components/procedure/AdministrationImport/ExcelImport/ExcelImportErrors.vue
  client/js/components/procedure/SegmentsBulkEdit/ActionStepper/ActionStepperResponse.vue
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/procedure/StatementSegmentsList/SegmentCommentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
  client/js/components/procedure/admin/DpNewProcedure/CoupleTokenInput.vue
  client/js/components/procedure/admin/DpNewProcedure/DpNewProcedure.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
  client/js/components/procedure/basicSettings/AutoSwitchProcedurePhaseForm.vue
  client/js/components/procedure/basicSettings/ExportSettings.vue
  client/js/components/procedure/basicSettings/ParticipationPhases.vue
  client/js/components/procedure/listSubscriptions/ListSubscriptions.vue
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/listOriginalStatements/ListOriginalStatements.vue
  client/js/components/statement/publicStatementLists/DpPublicStatement.vue
  client/js/components/statement/publicStatementModal/StatementModal.vue
  client/js/components/statement/publicStatementModal/StatementModalRecheck.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/components/statement/statement/DpVersionHistory.vue
  client/js/components/statement/statement/StatementPublish.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_flash.scss
Labels: review:frontend

#4197 fix(BEAA2-19): remove label from the pictogram
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend, quick-win

#4195 fix(BEAA2-14): add required attribute to the fileupload component
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend

#4209 fix(DPLAN-13108): datapicker css issue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_a11y-datepicker.scss
Labels: review:frontend

#4185 f adjut translation key text
  translations/messages+intl-icu.de.yml
Labels: quick-win

#4164 chore: fix deprecation in InputBag::get
  demosplan/DemosPlanCoreBundle/Controller/Procedure/AuthorizedUsersController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureExportController.php
  demosplan/DemosPlanCoreBundle/Controller/Report/DemosPlanReportAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAPIController.php
  demosplan/DemosPlanCoreBundle/Logic/JsonApiActionService.php
Labels: review:backend

#4152 chore: fix test permission for non-root users
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadFileData.php
Labels: review:backend, quick-win

#4166 chore: unlazy Transformer services
  config/services.yml
Labels: review:backend

#4208 fix (DPLAN-12327) Remove CUSTOMER_MASTER_USER aka Mandanten-Admin fro…
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Logic/OwnsProcedureConditionFactory.php
Labels: type:bug

#4220 fix: Move Sass-loader settings to the right place
  client/fe/webpack/moduleRules.js
  client/fe/webpack/plugins.js
Labels: type:bug, review:frontend

#4219 fix(DPLAN-13108): add tags import hint
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, quick-win

#4222 chore: add addon hook isEnabled
  demosplan/DemosPlanCoreBundle/Addon/AddonInfo.php
Labels: review:backend

#4228 Improve API Error logging
  demosplan/DemosPlanCoreBundle/EventListener/ApiControllerListener.php
Labels: review:backend, quick-win

#4229 build(refs DPLAN-12968, #AB21840): bump demosplan-ui to v0.3.43
  package.json
  yarn.lock
Labels: review:frontend

#4198 feat(refs DPLAN-12968, #AB21840): use DpSearchField for custom search
  CHANGELOG.md
  client/js/components/procedure/SegmentsList/CustomSearch.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_form.scss
Labels: review:frontend

#4221 fix: display messagebag from vuex-json-api
  client/js/store/core/initStore.js
Labels: type:bug, review:frontend

#4240 chore (refs DPLAN-14787): Remove duplicate role entry for planning agency admin
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadProcedureData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadRolesData.php
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData/LoadUserData.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/01/Version20250120151616.php
Labels: type:bug, review:backend

#4235 chore: add additional check during user login for valid orga
  demosplan/DemosPlanCoreBundle/Logic/User/UserService.php
Labels: review:backend

#4230 chore: provide a symfony toolbar entry for addons
  config/services.yml
  demosplan/DemosPlanCoreBundle/DataCollector/AddonInfoDataCollector.php
  templates/bundles/DemosPlanCoreBundle/data_collector/addon_info.html.twig
Labels: review:backend

#4239 fix(DPLAN-12935): improve the UX by changing the separator
  demosplan/DemosPlanCoreBundle/Resources/client/scss/objects/_list.scss
Labels: review:frontend, quick-win

#4241 fix: Find the lost whitespace in slicing tagging
  client/js/components/statement/splitStatement/CardPaneCard.vue
  client/js/components/statement/splitStatement/SegmentationEditor.vue
Labels: type:bug, review:frontend

#4246 Fix(DPLAN-14776): formatting issue after the spit statement view - release_ewm
  client/js/components/statement/splitStatement/SegmentationEditor.vue
Labels: review:frontend

#4248 fix(refs dplan-14561, dplan-13108, dplan-13082): Get fixes from main
  client/js/store/core/initStore.js
  demosplan/DemosPlanCoreBundle/Resources/client/scss/components/vendor/_a11y-datepicker.scss
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_tags.html.twig
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#3665 chore (refs DPLAN-12415): adjust Hooks/Selectors for gisLayer links.
  client/js/components/document/DpMapSettingsPreview.vue
Labels: review:frontend, quick-win, type:enhancement

#4237 feat(refs DPLAN-12780,#AB21086): Make own component for orga competence
  client/js/components/user/orgaDataEntry/OrganisationCompetence.vue
  client/js/components/user/orgaDataEntry/OrganisationDataForm.vue
  client/js/components/user/orgaDataEntry/PaperCopyPreferences.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#4212 feat DPLAN-12292 Update street orga field comming from Keycloak
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
  client/js/components/user/orgaDataEntry/OrganisationDataForm.vue
  demosplan/DemosPlanCoreBundle/Entity/User/Orga.php
  demosplan/DemosPlanCoreBundle/Logic/OzgKeycloakUserDataMapper.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/OrgaResourceType.php
  demosplan/DemosPlanCoreBundle/ValueObject/CommonUserData.php
  demosplan/DemosPlanCoreBundle/ValueObject/KeycloakUserData.php
  demosplan/DemosPlanCoreBundle/ValueObject/KeycloakUserDataInterface.php
  demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakUserData.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_data_entry.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, review:backend, type:story

#4244 f allow csv-text files
  config/allowedMimeTypes.yml
Labels: quick-win

#4254 DPLAN-3263 refactor demos plan admin controller
  demosplan/DemosPlanCoreBundle/Controller/Admin/DemosPlanAdminController.php
  demosplan/DemosPlanCoreBundle/Controller/Forum/DemosPlanReleaseController.php
  demosplan/DemosPlanCoreBundle/Logic/CsvHelper.php
  demosplan/DemosPlanCoreBundle/Logic/Platform/Statistics/StatisticsGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php
  demosplan/DemosPlanCoreBundle/ValueObject/Statistics.php
  tests/backend/core/Csv/CsvHelperTest.php
Labels: review:backend, type:enhancement, type:story

#4257 fix DPLAN-13034 remove unneeded code
  demosplan/DemosPlanCoreBundle/Entity/User/Role.php
Labels: review:backend

#4255 feat (DPLAN-3263) statistics per customer
  demosplan/DemosPlanCoreBundle/Controller/Admin/DemosPlanAdminController.php
  demosplan/DemosPlanCoreBundle/DataGenerator/CustomFactory/StatementFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Platform/Statistics/StatisticsGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
  demosplan/DemosPlanCoreBundle/Repository/StatementRepository.php
  demosplan/DemosPlanCoreBundle/ValueObject/Statistics.php
  tests/backend/core/Procedure/Functional/ProcedureServiceTest.php
Labels: review:backend, type:story

#4266 feat: tracking slicing tagging
  client/js/components/statement/splitStatement/SideBar.vue
  client/js/components/statement/splitStatement/SplitStatementView.vue
  client/js/lib/prosemirror/utilities.js
Labels: review:frontend, type:enhancement

#4268 build(refs DPLAN-12969, #AB21841): bump demosplan-ui to v0.3.44
  package.json
  yarn.lock
Labels: review:frontend

#4269 fix(refs DPLAN-14833, #AB5589): use correct prop name
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: type:bug, review:frontend

#4258 B dplan 13034 upgrade resource type
  demosplan/DemosPlanCoreBundle/ResourceTypes/AdministratableUserResourceType.php
Labels: review:backend

#4275 fix(refs DPLAN-14848): check content type
  client/js/store/core/initStore.js
Labels: type:bug, review:frontend

#4274 feat (DPLAN_12292) Log additional fields coming from Keycloak
  demosplan/DemosPlanCoreBundle/ValueObject/CommonUserData.php
  demosplan/DemosPlanCoreBundle/ValueObject/OzgKeycloakUserData.php
Labels: review:backend, type:enhancement

#4280 fix(refs DPLAN-12498): check for length of object keys
  client/js/components/document/DpMapSettingsPreview.vue
Labels: type:bug, review:frontend

#4281 refac(DPLAN-12013): some frontend adjustements
  client/js/components/tags/TagListEditForm.vue
  client/js/components/tags/TagsList.vue
Labels: review:frontend

#4207 chore: improve router performance
  demosplan/DemosPlanCoreBundle/Logic/Router.php
  demosplan/DemosPlanCoreBundle/Repository/ProcedureRepository.php
Labels: review:backend

#2679 fix: fix phpunit test after refactoring
  demosplan/DemosPlanCoreBundle/Controller/Base/BaseController.php
  demosplan/DemosPlanCoreBundle/Security/Authentication/Authenticator/LoginFormAuthenticator.php
  tests/backend/base/FunctionalTestCase.php
  tests/backend/core/Core/Functional/DynamicTransformerTest.php
Labels: review:backend

#4201 feat(refs DPLAN-12969): Add filters to institution list
  CHANGELOG.md
  client/js/bundles/procedure/administrationSegmentsList.js
  client/js/bundles/procedure/institutionTagManagement.js
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/SegmentsList/FilterFlyoutCheckbox.vue
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionTagManagement.vue
  client/js/store/procedure/FilterFlyout.js
  client/js/store/procedure/SegmentFilter.js
Labels: review:frontend, type:story

#4288 chore (refs AB#19470): routes are not allowed to have / suffix
  client/js/store/core/VuexApiRoutes.js
  demosplan/DemosPlanCoreBundle/Controller/AssessmentTable/DemosPlanStatementFragmentUpdateAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Base/APIDocumentationController.php
  demosplan/DemosPlanCoreBundle/Controller/Faq/FaqCategoryApiController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/DemosPlanStatementAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Statement/TagTopicAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanDepartmentAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanRoleAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanUserAPIController.php
Labels: review:frontend, review:backend
