Repository demos-europe/demosplan-core, pull requests merged in 2025-03, with the labels that each got.

#4416 chore: adjust csrf tokens. Pass them as strings
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_view.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_view.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_import.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new_master.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/list_subscriptions.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statement_fragments.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/alternative_login.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/citizen_register_form.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_data_entry.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/orga_register_form.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_user.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/user_set_password.html.twig
Labels: type:bug, review:frontend

#4303 fix(refs DPLAN-14901): Catch mapSettings-Request
  client/js/store/map/ProcedureMapSettings.js
Labels: type:bug, review:frontend

#4399 f_DPLAN-14956 remove STX (start of text) special chars from STN/Segment texts before exporting them.
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Labels: type:bug

#4418 DPLAN-15167 remove duplicated lines
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Labels: review:backend

#4420 ADO-24228 attempt to fix email attachments - at least enhance logging
  demosplan/DemosPlanCoreBundle/Logic/MailService.php
Labels: type:bug

#4419 fix(refs dplan-14909): Always send assignee and place in pair
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/report/DpReportListing.vue
Labels: type:bug, review:frontend

#4425 fix(refs DPLAN-15179): reset filters in localStorage
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
Labels: type:bug, review:frontend

#4426 Bug(refs DPLAN-15155): New stn select user
  client/js/components/assessmenttable/DpNewStatement.vue
  client/js/components/user/DpOrganisationList/DpOrganisationFormFields.vue
Labels: review:frontend

#4424 Bug(refs DPLAN-15149) faq item delete
  client/js/components/faq/DpFaqItem.vue
Labels: review:frontend

#4407 feat DPLAN-14864 EWM integration into diplanfest
  CHANGELOG.md
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMeta.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaAttachments.vue
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaFinalEmail.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/assessmentTable/DetailView/DetailViewFinalEmailBody.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceStorage.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/RpcStatementEmailSender.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementEmailSender.php
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/StatementResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementResourceType.php
Labels: review:backend, type:story

#4436 f DPLAN-15186 get only accepted planning offices
  demosplan/DemosPlanCoreBundle/Repository/OrgaRepository.php
Labels: review:backend, quick-win

#4438 f DPLAN- 15167 remove duplicated line
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
Labels: review:backend, quick-win

#4428 DPLAN-15064 fix placement of setter
  demosplan/DemosPlanCoreBundle/Repository/TagTopicRepository.php
Labels: type:bug, quick-win

#4437 f DPLAN-15195 allow master customer user to get and edit procedure te…
  demosplan/DemosPlanCoreBundle/Entity/User/User.php
  demosplan/DemosPlanCoreBundle/Logic/OwnsProcedureConditionFactory.php
Labels: review:backend

#4432 fix(refs DPLAN-15170, #AB22463): persist flyout and filter option selection
  client/js/components/procedure/SegmentsList/FilterFlyout.vue
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionList.vue
Labels: type:bug, review:frontend

#4439 fix DPLAN-15211 Set default email body
  client/js/components/procedure/StatementSegmentsList/StatementMeta/StatementMetaFinalEmail.vue
Labels: type:bug, review:frontend

#4441 fix DPLAN-15223: Check if permission is enable before making request
  client/js/store/map/ProcedureMapSettings.js
  config/permissions.yml
Labels: type:bug, review:frontend

#4383 F dplan 14783 extend report entries
  CHANGELOG.md
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/Controller/Document/DemosPlanDocumentController.php
  demosplan/DemosPlanCoreBundle/Controller/Procedure/DemosPlanProcedureController.php
  demosplan/DemosPlanCoreBundle/Controller/Report/DemosPlanReportAPIController.php
  demosplan/DemosPlanCoreBundle/Controller/Report/DemosPlanReportController.php
  demosplan/DemosPlanCoreBundle/Entity/Document/Elements.php
  demosplan/DemosPlanCoreBundle/Entity/Document/SingleDocument.php
  demosplan/DemosPlanCoreBundle/Entity/Report/ReportEntry.php
  demosplan/DemosPlanCoreBundle/Event/CreateReportEntryEvent.php
  demosplan/DemosPlanCoreBundle/EventSubscriber/ReportSubscriber.php
  demosplan/DemosPlanCoreBundle/Logic/Document/ElementsService.php
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphService.php
  demosplan/DemosPlanCoreBundle/Logic/Document/SingleDocumentService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ExportService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/PrepareReportFromProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ElementReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ExportReportService.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ParagraphReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Report/PlanDrawReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ProcedureReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ReportMessageConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Report/SingleDocumentReportEntryFactory.php
  demosplan/DemosPlanCoreBundle/Repository/ElementsRepository.php
  demosplan/DemosPlanCoreBundle/Repository/SingleDocumentRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ElementReportEntryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/ParagraphReportEntryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/PlanDrawChangeReportEntryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/SingleDocumentReportEntryResourceType.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/SingleDocumentResourceType.php
  demosplan/DemosPlanCoreBundle/Tools/ServiceImporter.php
  tests/backend/core/Document/Functional/ElementsServiceTest.php
  tests/backend/core/Document/Functional/ParagraphServiceTest.php
  tests/backend/core/Document/Unit/DocumentBundleImporterTest.php
  tests/backend/core/Procedure/Functional/BoilerplateServiceTest.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#4387 chore: provide a command to list known files
  demosplan/DemosPlanCoreBundle/Command/FilesListCommand.php
Labels: review:backend

#4440 feat DPLAN-14864 Add base test
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/MailTemplateFactory.php
  tests/backend/core/Statement/Functional/StatementEmailSenderTest.php
Labels: review:backend

#4447 fix(refs DPLAN-14909, DPLAN-14846): Send recommendation text again
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#4446 fix(refs DPLAN-15146): Pass propper Values to orgafilter and orgaRequest
  client/js/bundles/user/listOrgas.js
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
Labels: type:bug, review:frontend

#4459 chore(refs DPLAN-15021): Enhance upload tags form
  client/js/components/tags/TagsImportForm.vue
Labels: type:bug, review:frontend, type:enhancement

#4461 bug: Remove demosplan-ui link from package.json
  package.json
  yarn.lock
Labels: review:frontend

#4422 fix(refs dplan-14909): Prevent multiple fetches of the same Ressoruce (Place/AssignableUser)
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#4367 B dplan 15041 remove one edit option
  client/js/components/tags/TagListEditForm.vue
Labels: review:frontend

#4444 F(refs DPLAN-15156) alignment input fields
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: review:frontend

#4014 feat: Extract the initialization of styles for segment export
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/StyleInitializer.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  tests/backend/core/SegmentExport/StyleInitializerTest.php
Labels: review:backend, type:enhancement

#4469 bug(refs DPLAN-15148): Add spacing for inline notifications
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_masters.html.twig
  templates/bundles/DemosPlanCoreBundle/UI/inline-notification.html.twig
Labels: type:bug, review:frontend

#4478 chore: use current eslint command to fix reviewdog
  .reviewdog.yml
Labels: review:frontend

#4483 chore(refs DPLAN-15169): bump demosplan-ui from v0.4.6 to v0.4.7
  package.json
  yarn.lock
Labels: review:frontend

#4475 fix(refs DPLAN-15169): enable vue 3 render function api
  client/js/InitVue.js
Labels: type:bug, review:frontend

#4458 chore: do not send a not existing hash to the frontend
  demosplan/DemosPlanCoreBundle/EventSubscriber/TusUploadEventSubscriber.php
Labels: review:frontend, review:backend, quick-win

#4457 F create deletion report entry when procedure is deleted
  CHANGELOG.md
  demosplan/DemosPlanCoreBundle/Logic/Procedure/PrepareReportFromProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureService.php
  demosplan/DemosPlanCoreBundle/Logic/Report/ProcedureReportEntryFactory.php
Labels: review:backend

#4490 feat(refs:dplan-13111) censored export
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  client/js/components/statement/StatementExportModal.vue
  client/js/components/statement/listStatements/ListStatements.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4491 test(refs DPLAN-15256): fix export modal test
  client/js/components/statement/assessmentTable/AssessmentTableFilter.vue
  client/js/components/statement/assessmentTable/DpEditSelectedItemsMenu.vue
  client/js/components/statement/assessmentTable/DpMapModal.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsFragments.vue
  client/js/components/statement/assessmentTable/DpSelectedItemsStatements.vue
  client/js/components/statement/assessmentTable/DpTable.vue
  client/js/components/statement/assessmentTable/ExportModal.vue
  client/js/components/statement/assessmentTable/TocView/SearchAndSorting.vue
  client/js/components/statement/originalStatementsTable/OriginalStatementsTable.vue
  client/js/store/statement/Statement.js
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_filter.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_original_view.html.twig
  tests/frontend/unit/ExportModal.spec.js
Labels: review:frontend

#4495 chore: bumb demosplan-ui 0.4.8
  package.json
  yarn.lock
Labels: dependencies:yarn

#4487 DPLAN-14783 set relations coorectly in LoadElementsData fixture setup
  demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData/LoadElementsData.php
  tests/backend/base/FunctionalTestCase.php
  tests/backend/core/Document/Functional/ParagraphServiceTest.php
Labels: review:backend

#4494 feat (refs DPLAN-15242): null is a valid return type
  demosplan/DemosPlanCoreBundle/Logic/Document/ParagraphService.php
Labels: type:bug, review:backend

#4476 feat (refs DPLAN-13111): docx wihtout submissions data
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
  demosplan/DemosPlanCoreBundle/Logic/Export/DocxExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  tests/backend/core/Statement/Functional/SegmentsByStatementsExporterTest.php
Labels: review:backend, type:story

#4498 F dplan 15329 adjust statement confirm mail
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementSubmissionNotifier.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/new_statement_confirm_email.html.twig
Labels: review:backend, quick-win

#4499 b(refs-DPLAN-13110) delete obscure option in new statement
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/assessment_table_new_statement.html.twig
Labels: review:frontend

#4505 feat (refs DPLAN-13111): Adding tests to cover censoring on export
  tests/backend/core/Statement/Functional/SegmentsByStatementsExporterTest.php
Labels: review:backend

#4501 DPLAN-4237 set NextValidExternalIdForProcedure on stn sync instead ofstrictly setting its source STN value
  demosplan/DemosPlanCoreBundle/Logic/StatementSynchronizer.php
Labels: type:bug, review:backend

#4510 use meaningful data-cy names instead of loop values
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/dhtml/v1/includes/assessment_table_pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_list_survey_comments.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_new_member_list_mastertoeblist.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_survey_form.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/includes/administration_publicagency_pageheader.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/DemosPlanAssessment/cluster_detail.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_original_statements.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_statements.html.twig
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/includes/mastertoeblist_pageheader.html.twig
Labels: review:frontend

#4513 refac(DPLAN-12672): adjust base page header hook
  templates/bundles/DemosPlanCoreBundle/DemosPlanCore/includes/base_pageheader.html.twig
Labels: review:frontend

#4515 refac(DPLAN-15295): splitStatement issue: properly remove segment from the array
  client/js/store/statement/SplitStatementStore.js
Labels: review:frontend
