Repository demos-europe/demosplan-core, pull requests merged in 2025-05, with the labels that each got.

#4588 feat(refs DPLAN-15338): display customFields in StatementSegmentList
  client/js/bundles/procedure/administrationStatementSegmentsList.js
  client/js/components/procedure/StatementSegmentsList/SegmentsRecommendations.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4607 feat(refs DPLAN-15340): display custom fields for segments
  client/js/bundles/procedure/administrationSegmentsList.js
  client/js/components/procedure/SegmentsList/SegmentsList.vue
Labels: review:frontend

#4579 F dplan 15340 segment custom fields values
  CHANGELOG.md
  client/js/bundles/procedure/administrationSegmentsList.js
  client/js/bundles/procedure/administrationStatementSegmentsList.js
  client/js/components/procedure/SegmentsList/SegmentsList.vue
  client/js/components/procedure/StatementSegmentsList/SegmentsRecommendations.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  config/packages/doctrine.yaml
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldValue.php
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldValuesList.php
  demosplan/DemosPlanCoreBundle/Doctrine/Type/CustomFieldValueType.php
  demosplan/DemosPlanCoreBundle/DoctrineMigrations/2025/04/Version20250415123411.php
  demosplan/DemosPlanCoreBundle/Entity/Statement/Segment.php
  demosplan/DemosPlanCoreBundle/Repository/CustomFieldConfigurationRepository.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/StatementSegmentResourceType.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/CustomFieldValueCreator.php
  translations/messages+intl-icu.de.yml
Labels: review:backend, type:story

#4625 F(dplan-15556): unable to edit text when split statement is active
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsEdit.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegmentsList.vue
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4621 fix(refs DPLAN-15569) Wrap DpTab in a slot
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionTagManagement.vue
Labels: review:frontend

#4633 fix(refs DPLAN-15340): re-add transkey
  translations/messages+intl-icu.de.yml
Labels: type:bug, review:frontend

#4634 fix(refs DPLAN-15199): catch and handle exception when screenshot info is missing
  demosplan/DemosPlanCoreBundle/Logic/Statement/DraftStatementService.php
Labels: review:backend

#4620 Feat dplan 15567 delete custom fields related to procedure
  demosplan/DemosPlanCoreBundle/DataGenerator/Factory/CustomFields/CustomFieldConfigurationFactory.php
  demosplan/DemosPlanCoreBundle/Logic/Procedure/ProcedureDeleter.php
  demosplan/DemosPlanCoreBundle/Services/Queries/SqlQueriesService.php
  tests/backend/core/Procedure/Functional/ProcedureDeleterTest.php
Labels: type:story

#4635 B DPLAN-15595 add prop for different usecases
  client/js/components/statement/publicStatementLists/DpPublicStatementList.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanStatement/list_draft.html.twig
Labels: type:bug, review:frontend

#4640 Fix(DPLAN-15601): rendering DpTreeList inside a DpTab that uses v-sho…
  client/js/components/procedure/admin/InstitutionTagManagement/InstitutionTagManagement.vue
  client/js/components/procedure/admin/InstitutionTagManagement/TagList.vue
Labels: review:frontend, quick-win

#4651 fix(DPLAN-15610): allow short layer names
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomerResourceType.php
Labels: review:backend

#4650 fix(refs dplan-15262): Update List even after searching AND filtering
  client/js/components/procedure/publicindex/DpSearchProcedureMap.vue
Labels: type:bug, review:frontend

#4649 fix(refs: DPLAN:15434): remove indentation of profile data on big screens
  templates/bundles/DemosPlanCoreBundle/DemosPlanUser/portal_user.html.twig
Labels: type:bug, review:frontend

#4636 refactor: Move segment export releated files.
  demosplan/DemosPlanCoreBundle/Controller/Segment/SegmentsExportController.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/ImageLinkConverter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/ImageManager.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/Export/SegmentExporterFileNameGenerator.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsByStatementsExporter.php
  demosplan/DemosPlanCoreBundle/Logic/Segment/SegmentsExporter.php
  tests/backend/core/Statement/Functional/ImageLinkConverterTest.php
  tests/backend/core/Statement/Functional/SegmentExporterFileNameGeneratorTest.php
Labels: review:backend, quick-win

#4662 f DS-43 remove JSON_FORCE_OBJECT flag :
  demosplan/DemosPlanCoreBundle/Logic/Map/CoordinateJsonConverter.php
Labels: review:backend, quick-win

#4608 feat (ADO-24467): use interface when dispatching events
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AbstractRpcStatementBulkAction.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/AssessmentTableServiceStorage.php
  demosplan/DemosPlanCoreBundle/Logic/AssessmentTable/RpcBulkCopyStatements.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxSegmentImport.php
  demosplan/DemosPlanCoreBundle/Logic/Statement/XlsxStatementImport.php
Labels: review:backend, type:story

#4665 ref(DPLAN-15552): adjust text
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4669 chore: run reviewdog on dependabot prs
  .github/workflows/reviewdog.yml
Labels: review:backend

#4667 Fix(dplan 15291): toggle all does not work
  client/js/components/procedure/StatementSegmentsList/SegmentsRecommendations.vue
Labels: review:frontend

#4668 B dplan 12654 link back to statements list
  translations/messages+intl-icu.de.yml
Labels: review:frontend

#4477 chore (refs DPLAN-15259): allow addons to place files in public/files
  client/fe/webpack/plugins.js
Labels: review:frontend

#4677 chore: fix dependabot syntax, @ needs to be quoted
  .github/dependabot.yml
Labels: review:backend

#4570 chore: Allow Addons to define permissions per entrypoint
  demosplan/DemosPlanCoreBundle/Addon/FrontendAssetProvider.php
Labels: review:backend, type:enhancement

#4658 DPLAN-13006: add institutionTags aka assignedTags to the InvitablePublicAgencyResourceType
  client/js/components/procedure/admin/DpAddOrganisationList.vue
  config/permissions.yml
  demosplan/DemosPlanCoreBundle/ResourceTypes/InvitablePublicAgencyResourceType.php
Labels: review:frontend, review:backend, quick-win, type:story

#4657 f DS-82 preserve underlined and strike through text
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Labels: review:backend

#4660 Ds 82 parse down text to preserve provided formatting
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/StatementFromRowBuilder.php
Labels: review:backend

#4655 feat-DPLAN-15554 change order of topics
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit.html.twig
Labels: review:frontend

#4672 ADO-17872: Update InvitablePublicAgencyResourceType to use EDT pattern
  demosplan/DemosPlanCoreBundle/ResourceConfigBuilder/InvitablePublicAgencyResourceConfigBuilder.php
  demosplan/DemosPlanCoreBundle/ResourceTypes/InvitablePublicAgencyResourceType.php
Labels: review:backend

#4675 feat(refs DPLAN-15341): enable custom fields in bulk edit
  client/js/bundles/procedure/administrationSegmentsBulkEdit.js
  client/js/components/procedure/SegmentsBulkEdit/SegmentsBulkEdit.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_segments_bulk_edit.html.twig
  translations/messages+intl-icu.de.yml
Labels: review:frontend, type:story

#4671 fix(DPLAN-15627): unable to add a new comment after drawing a point on map
  client/js/components/procedure/StatementSegmentsList/SegmentLocationMap.vue
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  client/js/components/shared/TextContentRenderer.vue
Labels: review:frontend

#4688 fix(refs: DPLAN:15188): Add spacing between btns
  templates/bundles/DemosPlanCoreBundle/DemosPlanProcedure/administration_edit_boilerplate_group.html.twig
Labels: type:bug, review:frontend

#4693 Fix(dplan-15489): openLayers interaction issue
  client/js/components/procedure/imageAnnotator/DpImageAnnotator.vue
  client/js/components/procedure/imageAnnotator/DpLabelModal.vue
Labels: review:frontend

#4673 B dplan-15641 enable unset custom value in segments
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldInterface.php
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldValue.php
  demosplan/DemosPlanCoreBundle/CustomField/CustomFieldValuesList.php
  demosplan/DemosPlanCoreBundle/CustomField/RadioButtonField.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/CustomFieldValueCreator.php
Labels: type:bug

#4631 fix DPLAN-15589: Return created object on POST request
  demosplan/DemosPlanCoreBundle/ResourceTypes/CustomFieldResourceType.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/AllAttributesTransformer.php
  demosplan/DemosPlanCoreBundle/Utils/CustomField/CustomFieldCreator.php
Labels: type:bug

#4695 fix(refs DPLAN-15661): refactor initPlaces and initAssignableUsers
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#4699 fix(refs DPLAN-15675): show not assigned in tooltip
  client/js/components/procedure/StatementSegmentsList/StatementSegment.vue
Labels: type:bug, review:frontend

#4705 fix(refs DPLAN-15558): Load branding/cssvars for orgas
  client/js/components/user/DpOrganisationList/DpOrganisationList.vue
Labels: type:bug, review:frontend

#4708 f-DPLAN-82 preserve marked text
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Labels: review:backend, quick-win

#4709 f-DPLAN-82 adjust closing tag
  demosplan/DemosPlanCoreBundle/Logic/Statement/AssessmentTableExporter/AssessmentTableXlsExporter.php
Labels: quick-win

#4721 Remove unused vuejs-datepicker dependency
  package.json
  yarn.lock
Labels: review:frontend

#4700 feat (refs DPLAN-15650): Remove error prone flushes.
  demosplan/DemosPlanCoreBundle/Logic/Document/ElementsService.php
  demosplan/DemosPlanCoreBundle/Repository/ParagraphRepository.php
Labels: review:backend

#4504 feat(refs dplan 15328): make submitter data always editable
  demosplan/DemosPlanCoreBundle/Logic/Statement/StatementService.php
  templates/bundles/DemosPlanCoreBundle/DemosPlanAssessmentTable/DemosPlan/shared/v1/assessment_statement_detail_statement_data.html.twig
Labels: review:frontend, review:backend

#4612 F dplan 12342 check orga type before enabling procedure creation
  demosplan/DemosPlanCoreBundle/Controller/User/DemosPlanOrganisationAPIController.php
  demosplan/DemosPlanCoreBundle/Logic/Permission/AccessControlService.php
  translations/messages+intl-icu.de.yml
Labels: review:backend

#4735 f DPLAN-15765 use Symfony's string component to provide Unicode handling, including whitespace and normalization functions
  demosplan/DemosPlanCoreBundle/Logic/Import/Statement/ExcelImporter.php
Labels: type:bug, review:backend, quick-win
